### ISSUE TITLE
Send notifications on circle invitation

### ISSUE THREAD

**Issue by t2d** [nextcloud/circles#103]
By now, a user is not notified when she has been invited in a private circle. This is something that I expected because Nextcloud sends mail about many activities.

**Comment by daita** [comment]
![selection_047](https://user-images.githubusercontent.com/1038617/28420649-12e34d6c-6d63-11e7-8d54-e2e2ae3df112.png)

Just made a test, it seems to work. If you are talking about sending a mail on that kind of event, this will be available on next major release 0.12.0
