### ISSUE TITLE
Return value of OCA\Circles\Model\Member::getCircle() must be an instance of OCA\Circles\Model\Circle, null returned in lib/Model/Member.php:672

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/circles#1049]
```
TypeError: Return value of OCA\Circles\Model\Member::getCircle() must be an instance of OCA\Circles\Model\Circle, null returned in /var/www/nextcloud/apps/circles/lib/Model/Member.php:672
Stack trace:
#0 /var/www/nextcloud/apps/circles/lib/Notification/Notifier.php(206): OCA\Circles\Model\Member->getCircle()
#1 /var/www/nextcloud/apps/circles/lib/Notification/Notifier.php(155): OCA\Circles\Notification\Notifier->prepareMemberNotification(Object(OC\Notification\Notification))
#2 /var/www/nextcloud/lib/private/Notification/Manager.php(376): OCA\Circles\Notification\Notifier->prepare(Object(OC\Notification\Notification), 'fr')
#3 /var/www/nextcloud/apps/notifications/lib/MailNotifications.php(196): OC\Notification\Manager->prepare(Object(OC\Notification\Notification), 'fr')
#4 /var/www/nextcloud/apps/notifications/lib/MailNotifications.php(166): OCA\Notifications\MailNotifications->sendEmailToUser(Object(OCA\Notifications\Model\Settings), Array, 'fr', 'Europe/Paris')
#5 /var/www/nextcloud/apps/notifications/lib/BackgroundJob/SendNotificationMails.php(49): OCA\Notifications\MailNotifications->sendEmails(500, 1654816013)
#6 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(79): OCA\Notifications\BackgroundJob\SendNotificationMails->run(NULL)
#7 /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php(95): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#8 /var/www/nextcloud/cron.php(150): OCP\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#9 {main}
```

The return type is indeed invalid as the `$circle` property can be `null`.
https://github.com/nextcloud/circles/blob/84f7b8940e452e161d52f53e2b791ffa3858a84b/lib/Model/Member.php#L668-L673

Also needs handling in this case when returning `null` in 
https://github.com/nextcloud/circles/blob/be8aca2b8aa9cba2e9fa458b14c92d6f4a2e1be9/lib/Notification/Notifier.php#L206

## System
* Nextcloud 23.0.4 (not fixed in latest patch version AFAIK)
* PHP 7.3

**Comment by ArtificialOwl** [comment]
do you remember what was the operation that was notified ? looks like an invitation, was it from a specific circle ? can you reproduce the issue ?

**Comment by tcitworld** [comment]
This done by the `SendNotificationMails` background timed job, so it's harder to debug. Added debug info for next time it passes.

**Comment by tcitworld** [comment]
Looking at the code again, I'd say it's just because we're in the cron and there's no current user.

In the call to `initCurrentUser`, there's no user in the user session, so we return without calling `setLocalCurrentUser`.
https://github.com/nextcloud/circles/blob/1ef6aee586597a150e87f32133c6f143b0874869/lib/Notification/Notifier.php#L179
https://github.com/nextcloud/circles/blob/694aef8a77203852af67de61672d1f19cd8decc3/lib/Service/FederatedUserService.php#L224-L231

Then `getMemberById` calls `mustHaveCurrentUser`, which *should* stop the flow, but doesn't for some reason (are you sure both of `hasCurrentEntity` and `hasRemoteInstance` need to be `false` ?).
https://github.com/nextcloud/circles/blob/be8aca2b8aa9cba2e9fa458b14c92d6f4a2e1be9/lib/Service/MemberService.php#L151
https://github.com/nextcloud/circles/blob/694aef8a77203852af67de61672d1f19cd8decc3/lib/Service/FederatedUserService.php#L329

Finally `getMemberById` calls `getMemberById` with `null` as a second argument, which makes the join on the `circles` table not be applied and it's not found later.
https://github.com/nextcloud/circles/blob/be8aca2b8aa9cba2e9fa458b14c92d6f4a2e1be9/lib/Service/MemberService.php#L153-L156
https://github.com/nextcloud/circles/blob/10961b46334a0ac1ec133df36d9f01f487ae1c23/lib/Db/MemberRequest.php#L332-L334

In any case, this is the content of the database for the matching notification, tell me if more information is required.

The notification looks like this:
| key | value |
|--------------------|-----------------|
|notification_id    | <an_id>|
|app                | circles|
|user               | adnvtt|
|timestamp          | 1654509108|
|object_type        | member|
|object_id          | <member_id>|
|subject            | invitation|
|subject_parameters | []|
|message            | |
|message_parameters | []|
|link               | |
|icon               | |
|actions            | [{"label":"refuse","link":"\/ocs\/v2.php\/apps\/circles\/circles\/<circle_id>\/leave","type":"PUT","primary":false},{"label":"accept","link":"\/ocs\/v2.php\/apps\/circles\/circles\/<circle_id>\/join","type":"PUT","primary":false}]|

The entry in `oc_circles_member` like this
| key | value |
|--------------------|-----------------|
id            | <an_id>
single_id     | <member_single_id>
circle_id     | <circle_id>
member_id     | <member_id>
user_id       | <user_id>
user_type     | 1
instance      | 
invited_by    | <another_member_id>
level         | 1
status        | Member
note          | {"invitedBy":{"id":"<another_member_id>","userId":"<another_user_id>","userType":1,"displayName":"<another_user_display_name>","instance":"<mine>","basedOn":{"id":"<another_member_id>","name":"user:<another_member_id>:<another_member_id>","displayName":"<another_user_display_name>","sanitizedName":"","source":1,"population":0,"config":1,"description":"","url":"\/apps\/contacts\/direct\/circle\/<another_member_id>","creation":1654509017,"initiator":null}}}
cached_name   | <user_id>
cached_update | 2022-06-06 09:52:06
contact_id    | 
contact_meta  | 
joined        | 2022-06-06 09:51:48

The `oc_circles_circle` like this

| key | value |
|--------------------|-----------------|
id                  | <an_id>
unique_id           | <circle_id>
name                | A name
display_name        | A name (9)
sanitized_name      | A name (24)
instance            | 
config              | 32
source              | 16
settings            | {"population":2,"populationInherited":2}
description         | 
creation            | 2022-06-06 09:51:11
contact_addressbook | 0
contact_groupname   |

**Comment by ychaouche** [comment]
Same error here.
PHP 7.3
NC 23.0.12.2
the error is triggered by the cron

```
root@cloud-prep[10.10.10.82/24] 11:04:12 ~ # runas_wwwdata php7.3 -f /var/www/nextcloud/cron.php
su - www-data -s /bin/bash -c php7.3 -f /var/www/nextcloud/cron.php
TypeError: Return value of OCA\Circles\Model\Circle::getOwner() must be an instance of OCA\Circles\Model\Member, null returned in /var/www/nextcloud/apps/circles/lib/Model/Circle.php:423
Stack trace:
#0 /var/www/nextcloud/apps/circles/lib/Model/ShareWrapper.php(682): OCA\Circles\Model\Circle->getOwner()
#1 /var/www/nextcloud/apps/circles/lib/Model/ShareWrapper.php(644): OCA\Circles\Model\ShareWrapper->setShareDisplay(Object(OC\Share20\Share), Object(OC\URLGenerator))
#2 /var/www/nextcloud/apps/circles/lib/ShareByCircleProvider.php(581): OCA\Circles\Model\ShareWrapper->getShare(Object(OC\Files\Node\LazyRoot), Object(OC\User\Manager), Object(OC\URLGenerator), true)
#3 [internal function]: OCA\Circles\ShareByCircleProvider->OCA\Circles\{closure}(Object(OCA\Circles\Model\ShareWrapper))
#4 /var/www/nextcloud/apps/circles/lib/ShareByCircleProvider.php(579): array_map(Object(Closure), Array)
#5 /var/www/nextcloud/lib/private/Share20/Manager.php(1375): OCA\Circles\ShareByCircleProvider->getSharedWith('bejaia', 7, NULL, -1, 0)
#6 /var/www/nextcloud/apps/files_sharing/lib/MountProvider.php(90): OC\Share20\Manager->getSharedWith('bejaia', 7, NULL, -1)
#7 /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php(118): OCA\Files_Sharing\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
#8 /var/www/nextcloud/lib/private/Files/Filesystem.php(424): OC\Files\Config\MountProviderCollection->addMountForUser(Object(OC\User\User), Object(OC\Files\Mount\Manager))
#9 /var/www/nextcloud/lib/private/Files/Filesystem.php(341): OC\Files\Filesystem::initMountPoints('bejaia')
#10 /var/www/nextcloud/lib/private/legacy/OC_Util.php(342): OC\Files\Filesystem::init(Object(OC\User\User), '/bejaia/files')
#11 /var/www/nextcloud/apps/quota_warning/lib/CheckQuota.php(312): OC_Util::setupFS('bejaia')
#12 /var/www/nextcloud/apps/quota_warning/lib/CheckQuota.php(129): OCA\QuotaWarning\CheckQuota->getStorageInfo('bejaia')
#13 /var/www/nextcloud/apps/quota_warning/lib/CheckQuota.php(89): OCA\QuotaWarning\CheckQuota->getRelativeQuotaUsage('bejaia')
#14 /var/www/nextcloud/apps/quota_warning/lib/Job/User.php(52): OCA\QuotaWarning\CheckQuota->check('bejaia')
#15 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(79): OCA\QuotaWarning\Job\User->run(Array)
#16 /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php(95): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#17 /var/www/nextcloud/cron.php(152): OCP\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#18 {main}
root@cloud-prep[10.10.10.82/24] 11:08:23 ~ # grep version /var/www/nextcloud/config/config.php
  'version' => '23.0.12.2',
root@cloud-prep[10.10.10.82/24] 11:08:26 ~ #
```

**Comment by tcitworld** [comment]
@ychaouche This should be fixed in newest versions, as I didn't encounter it lately. Please upgrade and tell us if the issue still happens.

**Comment by ychaouche** [comment]
I'm stucked with 23 as it won't support any upgrade with php 7.3
and it doesn't support 8.2 either,
not until nc26,
so I NEED to install 7.4 to do the upgrade.

**Comment by tcitworld** [comment]
> as I didn't encounter it lately

Famous last words, reopening.
