### ISSUE TITLE
Circles are gone

### ISSUE THREAD

**Issue by jgrete** [nextcloud/circles#108]

**Comment by jgrete** [comment]
After updating the app to the latest version (0.12.0?) I noticed that all circles are gone. Is circles still in beta stage? If not any hint before actually updating would have been welcome.
I cannot give much more info at this time because I'm on holiday - wanted to use circles as a base for sharing a couple of pictures ... not again

**Comment by daita** [comment]
Can you provide me with more data about the database used, and if you can create and use a new circle ?

**Comment by jgrete** [comment]
Systemdetails:
User: 24
Files: 2345371

PHP
Version: 5.6.30

Datenbank
Art: mysql/mariadb
Version: 10.1.25
Size: 1.1 GB

It looks like I'm able to create a circle and add members to it

**Comment by daita** [comment]
fixed next minor release (today or tomorrow)
