### ISSUE TITLE
Equal named, different types of circles. Bug or feature?

### ISSUE THREAD

**Issue by jgrete** [nextcloud/circles#109]
I'm not sure whether it is a bug or a feature and what the implications are:
I'm able to create two (or more?) circles with equal names but different types (closed/personal and personal/open).
Creation of two circles with the same name and type has been correctly rejected 
Vers.: 0.12.2, Nextcloud 12.0.0

**Comment by daita** [comment]
Feature specific to personal circles :)

The only limitation when creating a personal circle is that you can't have a duplicate name per user. Meaning that multiple users can have the same name for a personal circle. This is not possible for the other types of circles.
