### ISSUE TITLE
After update to 0.12.2 circles doesn't show members

### ISSUE THREAD

**Issue by t2d** [nextcloud/circles#110]
I upgraded to 0.12.2. When I select a circle, it doesn't show any members. But when I want to re-add a member, it says 

> The member 'xxx' could not be invited to the circle: This user is already a member of the circle

I'm also using the LDAP connector. Maybe that's important.

**Comment by daita** [comment]
Have you disable the app before upgrading to 0.12.2 ?

**Comment by t2d** [comment]
Oops, I thought, I had answered that. No, the app was not disabled. However, I have now re-created the circles.
