### ISSUE TITLE
Circle events do not get triggered

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/circles#1111]
The `SetupManager` of the nextcloud server expects circles to emit events when creating or removing a circle:
https://github.com/nextcloud/server/blob/41aa08330f9a2476e8110bcd3bda051a98046937/lib/private/Files/SetupManager.php#L557-L565

However the logger line i inserted there never get's triggered - no matter if i create the circle in contacts or via collectives.
In contrast to that sharing a file triggers the logger i inserted: https://github.com/nextcloud/server/blob/41aa08330f9a2476e8110bcd3bda051a98046937/lib/private/Files/SetupManager.php#L545

As a result of this sometimes the mount point cache does not get invalidated and the folders of new collectives are not available.

**Comment by max-nextcloud** [comment]
Here's the log from my nextcloud-docker-dev instance when creating a circle:
```
nextcloud_1          | 192.168.24.4 - - [12/Jul/2022:08:51:03 +0000] "POST /ocs/v2.php/apps/circles/circles HTTP/1.1" 200 1272 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
nextcloud_1          | 192.168.24.4 - - [12/Jul/2022:08:51:04 +0000] "GET /ocs/v2.php/apps/circles/circles/ru3PkCtaDaNHDeZrO11yuLBKzjyFtgS/members HTTP/1.1" 200 1432 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
nextcloud_1          | 192.168.24.4 - - [12/Jul/2022:08:51:04 +0000] "GET /ocs/v2.php/apps/user_status/api/v1/statuses/admin HTTP/1.1" 200 897 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
nextcloud_1          | 192.168.24.4 - - [12/Jul/2022:08:51:04 +0000] "GET /index.php/avatar/admin/88?v=0 HTTP/1.1" 200 7450 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
```
(I removed the proxy_1 log messages for better readability. They basically echo the requests to nextcloud_1

**Comment by mejo-** [comment]
I can reproduce the bug that @max-nextcloud described.

But it seems like the Circles events used in [`SetupManager.php`](https://github.com/nextcloud/server/blob/121dbf028d265c6f7581c6f69d99b16847dec9ca/lib/private/Files/SetupManager.php#L556-L561) are deprecated anyway: `onCircleCreation`, `onCircleDestruction`, `onMemberNew` and `onMemberLeaving` are from [`EventsService`](https://github.com/nextcloud/circles/blob/6e239c888f5187b0eb85478eb2b65877bdcc226a/lib/Service/EventsService.php#L48) which has been deprecated and replaced by the newer [`EventService`](https://github.com/nextcloud/circles/blob/master/lib/Service/EventService.php).

If I replace them with the newer events `CircleCreatedEvent`, `CircleDestroyedEvent`, `CircleMemberAddedEvent` and `CircleMemberRemovedEvent`, it works as expected:

```diff
diff --git a/lib/private/Files/SetupManager.php b/lib/private/Files/SetupManager.php
index 876514b473..7ed2888037 100644
--- a/lib/private/Files/SetupManager.php
+++ b/lib/private/Files/SetupManager.php
@@ -554,10 +554,10 @@ class SetupManager {
                });
 
                $genericEvents = [
-                       '\OCA\Circles::onCircleCreation',
-                       '\OCA\Circles::onCircleDestruction',
-                       '\OCA\Circles::onMemberNew',
-                       '\OCA\Circles::onMemberLeaving',
+                       'OCA\Circles\Events\CircleCreatedEvent',
+                       'OCA\Circles\Events\CircleDestroyedEvent',
+                       'OCA\Circles\Events\CircleMemberAddedEvent',
+                       'OCA\Circles\Events\CircleMemberRemovedEvent',
                ];
 
                foreach ($genericEvents as $genericEvent) {
```

@ArtificialOwl are the old events expected to be triggered at all anymore? Or is the server code wrong and the new events should be used anyways?

**Comment by mejo-** [comment]
Well, maybe I miss something, but in my tests only `CircleDestroyedEvent`, `CircleMemberAddedEvent` and `CircleMemberRemovedEvent` are triggered. `CircleCreatedEvent` is not triggered when I create a new circle :thinking:

**Comment by ArtificialOwl** [comment]
It should be called: https://github.com/nextcloud/circles/blob/1b5b453e91fb28db4ed7ae26b2e44307a0a21f96/lib/FederatedItems/CircleCreate.php#L149 

Also, I would advice to use `CreatingCircleEvent`, as `CircleCreatedEvent` is only called on master instance in a GS env.
Same with `DestroyingCircleEvent`, `AddingCircleMemberEvent` & `RemovingCircleMemberEvent`

Not sure the edit to SetupManager will works as Circles is not using GenericEvent anymore ?

**Comment by ArtificialOwl** [comment]
Ok, my bad, I linked the call to the wrong method, and you are right, it is not triggered on single instance setup; let me see if this is fixable

**Comment by mejo-** [comment]
> Also, I would advice to use CreatingCircleEvent, as CircleCreatedEvent is only called on master instance in a GS env.
> Same with DestroyingCircleEvent, AddingCircleMemberEvent & RemovingCircleMemberEvent

Thanks, that's a good advice. One question though: is `CreatingCircleEvent` triggered *before* or *after* the circle got created? Because I still think it's better to use an event that is triggered after the action happened.

> Not sure the edit to SetupManager will works as Circles is not using GenericEvent anymore?

I'm not sure what you mean by that. What do you mean with "Circles is not using GenericEvent anymore"? :wink:

**Comment by ArtificialOwl** [comment]
`CreatingCircleEvent` is called after the local creation of the Circle, but you have NO confirmation that the Circle have been generated on all instances (in case of GlobalScale). 
Same with other events, it is safe to assume that the action (linked to the event) is already done locally at the call of the event without knowledge of its [the action] status on other instances.
