### ISSUE TITLE
allow simple e-mail address entry field to add new members to circle

### ISSUE THREAD

**Issue by jolu89jolu89jolu89jolu89** [nextcloud/circles#116]
I solely can create or add members to a circle that do already have an account in our Nextcloud (=existing user e.g. from ldap or internal db). 
We would need functionality to add not existing user (aka non-ldap/external user) to a circle so that he/she do get updated or included for a file share which has been specified to be shared amongst the circle group.

**Comment by daita** [comment]
you are 2 hours too late :)
https://github.com/nextcloud/circles/commit/f2d984befa8c007bcbab5ab2551a0ed7473d43e8

However, in its current state, it will just add email to the list of the members: there is yet no link with the shared_by_mail app when sharing a file.

**Comment by jolu89jolu89jolu89jolu89** [comment]
cool - thanks for the very quick implementation ;) I will try the git version later.
