### ISSUE TITLE
Folders shared with circles can't be accessed by other circle members

### ISSUE THREAD

**Issue by datenzar** [nextcloud/circles#1167]
Hi there,

I couldn't find documentation about how circles are working for sharing files, so I assumed that folders/files that are shared with the cirle would show up in the members' root folder view (just as it is the case for shared files/folders with groups or individual users). However that doesn't seem to be the case. Even when I share a folder with the circle and provide circle members with the "internal link", these users cannot access the link (they get a "File not found" message). I experienced the behavior on NC23 and even a recent upgrade to NC24 didn't solve the problem.

Is that a bug or am I misunderstanding the concept of circles?

**Comment by ringe** [comment]
Can confirm.

Only subfolders show up in the members' root folder, so joining multiple circle shares is failing.

**Comment by smlanger** [comment]
Currently having the same issue with NC25.

But we found that files/folders shared with a circle will show up for circle moderators and up. Only regular circle members can't see shared files/folders.
Also once a user has received the share by being moderator they will keep the access to it even when being demoted to regular user or being removed from the circle.

Still don't know if either of that is expected behavior.

**Comment by astrojuanlu** [comment]
I confirm this happens with NC Hub II (which [I guess](https://help.nextcloud.com/t/nextcloud-hub-ii-brings-major-overhaul-introducing-nextcloud-office-p2p-backup-and-more/128244/8) means NC 23), and that promoting members to Moderators is a good workaround.

Would be good to have a word from the dev team to clarify whether this is a feature or a bug.

**Comment by gonzalo** [comment]
finally I found the problem and fix the issue. Please check my solution at the bug report mentioned above

**Comment by joshtrichards** [comment]
> I couldn't find documentation about how circles are working for sharing files, so I assumed that folders/files that are shared with the cirle would show up in the members' root folder view (just as it is the case for shared files/folders with groups or individual users). However that doesn't seem to be the case. 

Confirmed that this works as expected in current v29. 

> Even when I share a folder with the circle and provide circle members with the "internal link", these users cannot access the link (they get a "File not found" message).

Confirmed this also works too today.

Are you still seeing these behaviors in >=v28?

**Comment by joshtrichards** [comment]
Closing as tested fine and no follow-up received.
