### ISSUE TITLE
During upgrade to 12.0.2: an exception occurred while executing 'INSERT INTO oc_circles_members message

### ISSUE THREAD

**Issue by radoeka** [nextcloud/circles#117]
The output in the web interface after upgrade to 12.0.2:

After upgrade from 12.0.1 to 12.0.2, access the web interface.  The web interface state that a 
upgrade of circles is to performed, output:

Upgrade to 12.0.2

Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO oc_circles_members (circle_id, "user_id", level, status, note, joined) SELECT circle_id, user_id, level, status, note, joined FROM __temp__oc_circles_members': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_circles_members.user_type
Detailed logs ￼
Prepare Update
Debug logniveau instellen
Enable maintenance mode
Databaseschema update
Database updated
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO oc_circles_members (circle_id, "user_id", level, status, note, joined) SELECT circle_id, user_id, level, status, note, joined FROM __temp__oc_circles_members': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_circles_members.user_type
De update is mislukt. Meld dit probleem aan de Nextcloud community.

**Comment by radoeka** [comment]
Put the server back to NC-12.0.1 instance.  It's running again.
I now see that there is update available for circles to version 0.12.4
I assume the problem is with this update.

Advice how to continue, please. I would like to update circles to 0.12.4 first and than upgrade NC to 12.0.2, but I need to know that upgrading circles to 0.12.4 does not result in the above mentioned problem.

**Comment by daita** [comment]
I am pretty sure that you can upgrade circles to 0.12.4 and then upgrade NC to 12.0.2. The issue is when you upgrade everything at the same time.

**Comment by irgsmirx** [comment]
I experienced the same issue about 10 minute ago. 
I manually added the column user_type to the oc_circles_members table with a default value of 0 and the upgrade passed.

**Comment by daita** [comment]
@irgsmirx you were upgrade to nc12.0.2 at the same time ?

**Comment by radoeka** [comment]
@irgsmirx
> I manually added the column user_type to the oc_circles_members table with a default value of 0

Can you provide the (exact) commands that you used?

**Comment by daita** [comment]
>      ALTER TABLE `oc_circles_members` ADD `user_type` SMALLINT(6) NOT NULL DEFAULT '0';

**Comment by irgsmirx** [comment]
> @irgsmirx you were upgrade to nc12.0.2 at the same time ?

No, I am still at 12.0.1. The upgrade of the circles app failed anyway.

>  ALTER TABLE `oc_circles_members` ADD `user_type` SMALLINT(6) NOT NULL DEFAULT '0';

Yes, that's it. But actually I used phppgadmin for the job.

**Comment by radoeka** [comment]
@daita no other values to be inserted into the various users?
At then moment I've a circle with five members.  The user_type for those already existing users should be '0'?

**Comment by daita** [comment]
should be 1; but it is changed to 1 by a Repair/Migration script on upgrade.

**Comment by radoeka** [comment]
OK.  Thanks.
Will you release a new version of circles soon?  If yes, I'll wait for this new version.

**Comment by daita** [comment]
which version are you using ? is it working right now ?

**Comment by radoeka** [comment]
I'm using 0.12.2 at NC-12.0.1  This is indeed working.
Although I know now how to fix the issue.  When you provide a new shortly I rather wait for that one.

**Comment by daita** [comment]
0.12.4 won't give you anything more, you can patiently wait for 0.13.0

**Comment by putt1ck** [comment]
Upgrade notification received on NC 12.02 for circles 0.12.2 to 0.12.4. Attempt at upgrade returns "An exception occurred while executing 'ALTER TABLE oc_circles_members ADD "user_type" SMALLINT NOT NULL': SQLSTATE[23502]: Not null violation: 7 ERROR: column "user_type" contains null values".

Just wait for 0.13 is best option?

**Comment by putt1ck** [comment]
Also is there a recommended way to downgrade (upgrade left that error and then required "occ app:disable circles" before NC was available again)

**Comment by daita** [comment]
Not sure that 0.13 will fix this but if you can execute SQL request, you should try to run manually:

>      ALTER TABLE `oc_circles_members` ADD `user_type` SMALLINT(6) NOT NULL DEFAULT '0';

If you have the same error it might be because you already have a user_type field in your database; you will need to run those 2 requests:

>       UPDATE `oc_circles_members` SET user_type='1';
>       ALTER TABLE `oc_circles_members` CHANGE `user_type` `user_type` SMALLINT(6) DEFAULT '0' NOT NULL;

If you cannot (or don't want) run SQL request manually, the cleaner/safer way will be to make a small app that fix that upgrade process.

**Comment by radoeka** [comment]
@daita how come that the upgrade to circles 0.12.4 is resulting in this error?  What is the root cause?
Is this a problem in the NC core (DB) upgrade functionality, or this is a problem with 0.12.4?

I added the missing table while running at circles 0.12.2, the upgrade to circles 0.12.4 went fine after that.

**Comment by ArmyOfMonkies** [comment]
I think im experiencing the same issue, or a closely related one. It first started while i was running 12.0.0 and just uppdated the Circles app from within the nextcloud gui. I was then redirected to the upgrade webbpage, where the uppgrade failed.

I then tried to finnish the uppgrade via commandline and occ but got the same error message. Only solution i found to allow me to get into Nextcloud again was to disable the circles app.

I then uppgraded Nextcloud to 12.0.2 thinking the that might be the issue, using the web based uppgrader. The Uppgrade went fine, but the same error appeared when i enabled the circles app.

The error i get is.

`An exception occurred while executing 'INSERT INTO oc_circles_members ("circle_id", "user_id", level, status, note, joined) SELECT circle_id, user_id, level, status, note, joined FROM __temp__oc_circles_members': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_circles_members.user_type`

So it seems its the same error, and i get it on both 12.0.0 and now 12.0.2.

Is there any safe way to fix this or should i just keep circles disabled for the time beeing, and await further investigation and fixes ?

cheers.

**Comment by daita** [comment]
Ok, I will release a small app that fix this. within the next few days.

@radoeka: I have no clue. I created a new database field in prevision of 0.13.0 but it seems it make some upgrade to fail. I was able to reproduce the bug on one of my instance but with no 'simple' fix but running the SQL request.

**Comment by radoeka** [comment]
@daita If I'm not mistaken the new table is added by putting it characteristics in the appinfo/database.xml
Is there anything else needed to have the table (user_type) added to an existing database or
from this point onwards the NC DB upgrade functionality should take care of adding the table to the database?

Perhaps the upgrade code becomes confused due to the change in the used_id from 64 to 128?
`+++ circles-0.12.4/appinfo/database.xml 2017-08-17 11:52:51.000000000 +0200
@@ -102,7 +102,14 @@
                        <field>
                                <name>user_id</name>
                                <type>text</type>
-                               <length>64</length>
+                               <length>128</length>
+                               <notnull>true</notnull>
+                       </field>
+
+                       <field>
+                               <name>user_type</name>
+                               <type>integer</type>
+                               <length>1</length>
                                <notnull>true</notnull>
                        </field>
`
In case it's a problem with the NC DB upgrade functionality a bug should be opened for this.

**Comment by nickvergessen** [comment]
You need to set a default value, or remove the notnull = true condition

**Comment by daita** [comment]
https://github.com/nextcloud/circles/commit/4dee22245ff9201ac81603c93e20a9078c380ba3

I will release a 0.12.5 that fix this (hopefully)

**Comment by putt1ck** [comment]
<standing by to test> :)

**Comment by radoeka** [comment]
@nickvergessen ain't this missing functionality in the DB upgrade code (if there is such thing as DB upgrade code).

When the DB declaration in appinfo/database.xml contains
  &lt;notnull>true&lt;/notnull>
and there is no default value, shouldn't the generic nextcloud code bail out (assert, refuse) the database.xml file?  Call it database.xml sanity check.

**Comment by nickvergessen** [comment]
No, because we don't know what value is a valid one

**Comment by radoeka** [comment]
That makes the check still possible and valuable.  Like in this case the tag &lt;default> was not present at all.  Resulting in a no longer usable NC instance.  The check/audit/verification can just check for the &lt;default> tag.  When missing the new version can not be accepted.  When the tag is present, it must be assumpted that the right default value is provided.

**Comment by daita** [comment]
Can you try this ?

https://github.com/nextcloud/circles/releases/download/v0.13.0/circles-0.13.0.tar.gz

**Comment by daita** [comment]
Please upgrade to 0.13.0. 

Open a new ticket if you still have issue.

**Comment by ArmyOfMonkies** [comment]
Hi!

I have tried it ant it works like a charm.

cheers Kalle
