### ISSUE TITLE
sharing failed after adding a new user to a circle

### ISSUE THREAD

**Issue by b-lsa** [nextcloud/circles#118]
if I add a new member into a circle then all shares of the circle aren't usable for this new user. The preview is shown in the user's folder but if the user wants to download the file, the server is reporting a HTTP ERROR 503.
additional info: we've enabled encryption

**Comment by daita** [comment]
I you share a file when the user is in the circle, is it working ?

**Comment by b-lsa** [comment]
yes. if the user is already in a circle all shares are working. only if I add a new user into an existing circle, the share is failing

**Comment by daita** [comment]
Well. you're right, this is an issue resulting from the encryption. When you create a new share to a group/circle, encryption will create a new key for members. When a new user is joining the group/circle, he will not have access to the generated key.

**Comment by b-lsa** [comment]
is it possible to fix it? may be it's possible to share all existing shares from the (old) circle with the new (added) user before adding the new username to the circle. this should solve she encryption issue (I hope ;))

**Comment by b-lsa** [comment]
I've tested it and it works in the webclient:
1. have an existing share with the file example.jpg with a circle/group.
2. share the file example.jpg with the new user
3. add the new user to your circle/group
4. remove the share for the new user
5. the new user has still access to the share (because he's in the group now)
if these steps could be automated in the process of 'add a new circle member', all is fine I guess

**Comment by daita** [comment]
Well, no. Unfortunately.

- Regenerate the shares on new user will destroy all rename on the shared files.
- The generation of a key when the new member will try to reach the file will fail.

The only thing that will work is that to ask the owner of the encrypted file to manually share/unshare the needed file to the fresh new memberso a key is generated.

Sharing an encrypted file can be slightly hard sometimes :-)

**Comment by daita** [comment]
In case you really want to encrypt your file, having a master_key helps a lot.
