### ISSUE TITLE
Circles does not install correctly on NC 24

### ISSUE THREAD

**Issue by earendil1** [nextcloud/circles#1199]
Actual behavior: installing latest Circles on NC 24 results in Circles not having an icon and not showing its icon anywhere in NC
Desired behavior: should install properly
Reproduce: Try to install with the following configuration

Tried disabling and enabling with no avail. Screenshot:
![Schermata 2022-10-31 alle 16 27 51](https://user-images.githubusercontent.com/76689803/199045773-2c592833-0d9f-4ccc-9554-fc64d5746dd5.png)

Thanks!

Mac
Monterey
12.6

Chrome
Versione 106.0.5249.119 (Build ufficiale) (arm64)

**Comment by AxelMeineke** [comment]
Same here. no Circles available in my NC24 installation.

**Comment by baluballa** [comment]
My issue seems related...

I lost circle icon too after upgrade of NC. Disabled the Circles app, then removed the circle folder under ./apps.

Then downloaded and reinstalled the circle app. Circle app seems now to work, but it somehowe causes the File app to break. After enabling circles, this message comes up in the GUI:

![bilde](https://user-images.githubusercontent.com/7481653/200190248-ad9ab1be-0665-4fec-83da-dc4d09ccd93a.png)

disable the Circles app bring the File app up again.

This the log message:
`"Message":"Class \"OCP\\User\" not found in file '/xx/xxx/xx/x/nextcloud/apps/circles/files/list.php' line 3"

**Comment by mejo-** [comment]
Dear @earendil1. The Circles apps frontend moved to the Contacts app with Nextcloud 22. So it's expected that you don't see a Circles icon in Nextcloud 24. Enable the Contacts app and you will be able to administrate your circles there :relaxed:

**Comment by earendil1** [comment]
Hi @mejo- it was indeed as you described. It would be really helpful if this information was available in NC24 where the apps/Circles app is as an addendum to the description of the app for example (see pic) or where this piece of information is likely to be found. The icon in the apps list is still invisible even with contacts installed, but I do not know whether it is meant to be like that.
I am amazed at the good work that is being done. Thanks a million to all the contributors!
![Schermata 2022-11-12 alle 15 15 05](https://user-images.githubusercontent.com/76689803/201478208-2a3d615d-4b12-4481-8072-3920d5e154df.png)
