### ISSUE TITLE
Breaking change from circles to 0.12.2 to 0.12.4

### ISSUE THREAD

**Issue by felux** [nextcloud/circles#121]
Hi,

today, we updated our nextcloud instance from version 12.0.0 to 12.0.2 and circles from 0.12.2 to 0.12.4.

Afterwards, a share using a circle disappeared and deleted the files in the directory of the users to that circle. The files were still accessible through the user they belonged to. The circle itself also disappeared. 

Looking at the databases, I found out that the table `oc_circles_shares` is empty. That was also the case before the update. After playing around with the circles app I found out that the new version adds here some information about the shares. I also discovered, that the col `share_with` in the table `oc_shares` contained the `id` field from `oc_circles_circles`. Now it contains the first nine letters of the `unique_id` field when adding a new share with a circle. 

For us, the impact was small but in a bigger environment this bug/change could have a serious impact. Is there a script to migrate the database change in a working environment?

**Comment by daita** [comment]
Have you seen any error message from 0.12.2 to 0.12.4 ? 

The oc_circles_shares is not used when sharing a file. And yes you are right that the first 14 chars of the unique_id of a circles is used in the oc_shares.

**Comment by felux** [comment]
No, there weren't any error messages. Before the update the col `share_with` already contained the `id` from `oc_circles_circles`.

**Comment by daita** [comment]
ok, thanks for your report. Next major release will have some tools to fix this kind of issue that appears when migrating/upgrading.
