### ISSUE TITLE
Cant list active or disabled users in Admin panel with Nextcloud 25.0.1 with Circles 25.0.0 enabled.

### ISSUE THREAD

**Issue by donty** [nextcloud/circles#1218]
When accessing Users in admin, it simply reports

'An error ocurred during the request. Unable to proceed'

and refuses to list active users. Can't find a matching error in the logs relating directly to the app - just on timing the only unaccounted error was ;

```
 Debug    no app in context  OC\Authentication\Exceptions\InvalidTokenException: Token does not exist: token    
                              does not exist at .../Authentication/Token/PublicKeyTokenProvider.php line 115 
```
It does display all Groups and Admins just no users. 

Disable Circles app and all works fine

Happy to find data/logs if there is a way to capture useful stuff!

**Comment by joshtrichards** [comment]
Hi @donty - Clearing out some old issues. This one hasn't seen any additional reports. Are you still experiencing this?

**Comment by donty** [comment]
Hi Josh 

Thanks for checking. I'm not currently using circles so it isnt something I have continued following up. Happy to close it and move on! ;) 

D
