### ISSUE TITLE
Crash if Circles is disabled in Nextcloud 25

### ISSUE THREAD

**Issue by GreggGreen** [nextcloud/circles#1226]
I had just upgraded to NC25. Circles was disabled. After the upgrade occ crashed with this error.

OCP\AutoloadNotAllowedException: Autoload path not allowed:  /usr/local/nextcloud/apps/circles/lib/circlesmanager.php in /usr/local/nextcloud/lib/autoloader.php:141

It is impossible to disable Circles. I have to rename the folder circles folder.

**Comment by joshtrichards** [comment]
Likely PHP caching. Restart mod_php or FPM after updating.
