### ISSUE TITLE
please, documentation needed

### ISSUE THREAD

**Issue by punkyard** [nextcloud/circles#1228]
hi
since install, we are experiencing issues with Collectives and Circles, though we like it and use it, so many logs, issues, data loss.. so it is a misconfiguration of our set-up

but our issue is : where to find doc and solutions to evolve our situation ^^

when using **occ circles:check**, we are facing:
```
### Checking loopback address.
. The loopback setting is mandatory and can be checked locally.
. The address you need to define here must be a reachable url of your Nextcloud from the hosting server itself.
. By default, the App will use the entry 'overwrite.cli.url' from 'config/config.php'.

* testing current address: https://localhost
- GET request on https://localhost/index.php/csrftoken: **fail**

- You do not have a valid loopback address setup right now.

Please write down a new loopback address to test: localhost
format must be http[s]://domain.name[:post][/path]
Please write down a new loopback address to test: https://sub.domain.net
* testing address: https://sub.domain.net
- GET request on https://sub.domain.net/index.php/**csrftoken**: fail

In CirclesCheck.php line 264:
  **Your Circles App is not fully configured.** 
```

anything else hasn't worked.
also it's not possible to remove users from a circle or delete a circle.

1. what is and where is index.php/csrftoken?
2. could you provide info on how to properly configure server for loopback?
(i've checked /etc/hosts and config.php, got confirmed it was correctly setup but maybe not)
3. could you provide documentation for the command occ circles:check?

we are truly hoping to make our situation evolve and be able to use Circles/collectives in the right way

thanks a lot to your team for the useful piece of work you're doing ✌️

**Comment by susnux** [comment]
> what is and where is index.php/csrftoken?

If is just the API endpoint to query the current CSRF token, e.g. you can see it if you browse to `YOUR_SERVER_ADDRESS/index.php/csrftoken`.

> could you provide info on how to properly configure server for loopback?

How did you install nextcloud? If you use docker everything should work as expected.
If not make sure you can reach you nextcloud instance using the loopback address, here it depends on your setup.

You should make sure that you can reach your server on `localhost`, if you use a custom port or other custom setup you probably have to configure the `overwrite.cli.url`, [see here](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html).

**Comment by punkyard** [comment]
thanks a lot @susnux for your information

i've installed nextcloud with a zip, on my very first VPS. I did several installs and reinstalls and things seemed to work correctly, then logs kept appearing, probably after ubuntu server updates/upgrades.

I don't understand yet what to do about the loopback address.
in my /etc/hosts there is: 

127.0.0.1       localhost
127.0.1.1       panel.domain.net nextcloud.domain.net

I'm using 'pretty URL' rewriting in config.php
and i'm using 'overwrite.cli.url' => 'https://nextcloud.domain.net',

**Comment by punkyard** [comment]
hi (my answer did not print)
thank you very much for your answer.

i installed NC with a zip file.
I don't understand yet what to do about the loopback thing ..

in /etc/hosts i have: 
```
127.0.0.1       localhost
127.0.1.1       panel.domain.net nextcloud.domain.net
```

i'm using pretty URL rewriting in config.php
and i'm using 'overwrite.cli.url' => 'https://nextcloud.domain.net',

occ circles:check returns:
```
### Checking loopback address.
. The loopback setting is mandatory and can be checked locally.
. The address you need to define here must be a reachable url of your Nextcloud from the hosting server itself.
. By default, the App will use the entry 'overwrite.cli.url' from 'config/config.php'.

* testing current address: https://nextcloud.domain.net
- GET request on https://nextcloud.domain.net/index.php/csrftoken: fail

- You do not have a valid loopback address setup right now.

Please write down a new loopback address to test: 
```

this is where I am, i don't know what to do from there.

**Comment by punkyard** [comment]
trying to solve this loopback thing, i've also set:

 'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'nextcloud.domain.net',
    2 => 'my.IP',
    3 => '127.0.0.1',
    4 => '127.0.0.53',
  ),

**Comment by susnux** [comment]
Can you access the csrftoken endpoint using e.g. curl?

E.g. does this work: `curl -i https://sub.domain.net/index.php/csrftoken`

or `curl -i localhost/index.php/csrftoken`

**Comment by punkyard** [comment]
I can in my browser
https://nextcloud.net/index.php/csrftoken returns:
`token":"..."}`

but in CLI, both curl commands returned:
`curl: (7) Failed to connect to nextcloud.domain port 443 after 0 ms: Connection refused`

should i launch them from a specific folder or with a specific user?

**Comment by punkyard** [comment]
i've tried with different user and from nextcloud folder, didn't do any difference.

iptables has set
` Allow     WEB     TCP     80,443       0.0.0.0/0`

**Comment by susnux** [comment]
so both commands fail? But the same url works in the browser? Weird.
Sorry but I have no clue, but I recommend you to ask on the community for help: https://help.nextcloud.com/

**Comment by punkyard** [comment]
thanks for your time @susnux  🙏

**Comment by joshtrichards** [comment]
Hi @punkyard - Hope you got this web server configuration matter worked out. If this issue is no longer needed, please close it out. Thanks!

**Comment by punkyard** [comment]
NC AIO changed the game ;)
thank you all
