### ISSUE TITLE
Limit search requests

### ISSUE THREAD

**Issue by blizzz** [nextcloud/circles#123]
## steps

1. Go to Circle app
2. Select an existing circle
3. Click on "Add a member"
4. Type "foobar"

## expected

One request to NC searching for "foobar"

## actual

Several requests to NC searching for "f", "fo", "foo", "foob", "fooba" and "foobar". Displayed result can be confusing.

It can hammer the server and further services connected to it (e.g. LDAP) which can result in slow responses → bad UX.

## suggestion

delay the search for a small amount of time, cancel previous calls. 

Quick fix:

```diff
diff --git a/js/circles.app.navigation.js b/js/circles.app.navigation.js
index 9f667e5..f858a68 100644
--- a/js/circles.app.navigation.js
+++ b/js/circles.app.navigation.js
@@ -60,12 +60,18 @@ var nav = {
                return;
            }
 
-           actions.searchMembersRequest(search);
-           if (elements.membersSearchResult.children().length === 0) {
-               elements.membersSearchResult.fadeOut(curr.animationMenuSpeed);
-           } else {
-               elements.membersSearchResult.fadeIn(curr.animationMenuSpeed);
+           if(!_.isUndefined(elements.searchID)) {
+               clearTimeout(elements.searchID);
            }
+           elements.searchID = _.delay(function () {
+               actions.searchMembersRequest(search);
+               if (elements.membersSearchResult.children().length === 0) {
+                   elements.membersSearchResult.fadeOut(curr.animationMenuSpeed);
+               } else {
+                   elements.membersSearchResult.fadeIn(curr.animationMenuSpeed);
+
+               }
+           }, 200);
        }).blur(function () {
            setTimeout(function () {
                elements.membersSearchResult.fadeOut(curr.animationMenuSpeed);
```

I did not look at other places where search might occur. I came accross this while thinking about https://github.com/nextcloud/server/issues/2443.

On a sidentoe, ideally all the JS objects would not be in the global namespace, but within ``OCA.Circles``.

**Comment by daita** [comment]
I can implement it, or prefer to PR ?

**Comment by blizzz** [comment]
I am not sure whether there are other places where a search is triggered like this. If you know more, you can do it faster. If this is all, I can turn it into a PR easily.

**Comment by daita** [comment]
it should do the job, you can PR. If needed i will fix it
