### ISSUE TITLE
LDAP Backend with circles

### ISSUE THREAD

**Issue by ghost** [nextcloud/circles#1249]
Hi , i noticed thats circles dosen't work perfectly with LDAP groups.

Lets's say i have to groups group1 (created in nextcloud) &  group2(imported from LDAP). and i created a circle to add them to it
 
group1 members will see the circle in their list but group2 won't, when i change the visibility it dosen't show that the group2 are members of it . 

seeing the database LDAP groups are on a different table than the others. < might be the cause ?

if there is any info that might help would be appreciated 

this issue might be related to this [#1166](https://github.com/nextcloud/circles/issues/1166) not sure

**Comment by elephantastyczny** [comment]
This have to be fix right away!
voting for it!

**Comment by elephantastyczny** [comment]
> 

Ghost, can you please share - how did you approached and fixed this?
Any screenshots or tutorials?

**Comment by mjess** [comment]
Will this be fixed/improved? I need to use Collectirves (which requires Circles) and I want to use LDAP groups for the user/group management. Would be great to have Circles working with LDAP groups

**Comment by elephantastyczny** [comment]
Hi Devs, any plans to make it work?
Not pushing, just asking ;)

**Comment by mejo-** [comment]
This issue might get solved by https://github.com/nextcloud/circles/pull/1421. Could you please apply this patch against the circles app and see whether it solves the issue for you?
