### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by samdakap** [nextcloud/circles#1263]
Hi, 
I am a bit confused while reading this github's readme. It is mentioning NC22 and we're now at NC25.
I had the app on my NC "just in case", and now that I need it, I can't find any info on it, but it is still a "Featured" App.
Basically, I wanted to be able to share tasks between multiple people, and assign some people to them.
But I was not able to do it using Tasks, and so I was counting on Circles to help me with this.
If this is not even a good use case of it, please let me know so I can have one less app in my NC instance.
Thanks.

**Comment by CarlSchwan** [comment]
It is still maintained, just the readme is outdated. Feel free to send a pull request to fix that 😜
