### ISSUE TITLE
No circles are shown on start of circles menu

### ISSUE THREAD

**Issue by jgrete** [nextcloud/circles#127]
Entering the circles page I cannot see any of my circles although the left hand selection menu shows "all circles" and the filter menu shows "no filter". Actually I've one circle of each type so I would expect to see all of these. Going through all of the left hand menu options I only see my "personal circle", no other (filter still shows "No filter"). 
Selecting filter "show all circles you are a member of" or "show all circles you are owning" leads to the expected behaviour.
So, I think the actual behaviour is not intuitive, as I would expect "no filter" and "all circles" should actually show all circles.
Regards
Jürgen

Nextcloud 12.0.2, circles 0.12.4

**Comment by daita** [comment]
it should works like this, no filter shoud display all circles from the selected categorie.

All Circles should display all circles :)

**Comment by jgrete** [comment]
Hm, but it does not. Look at this screenshot. That's how it looks when I'm starting to use circles:
![2017-09-07 12_22_56-kreise - nr17](https://user-images.githubusercontent.com/14105933/30159016-81203b2a-93c7-11e7-8626-03a27a3bd3e8.png)

My native language is german, but I think it's clear so far.
Now I'm choosing personal circles:
![2017-09-07 12_27_15-kreise - nr17](https://user-images.githubusercontent.com/14105933/30159213-28b9c39c-93c8-11e7-8735-ce58ba1dba6b.png)
That's what I would expect.
Now I'm choosing a different type and then the same type with no filter:
![2017-09-07 12_37_44-kreise - nr17](https://user-images.githubusercontent.com/14105933/30159667-a6b4965e-93c9-11e7-852d-b2815874fc4f.png)
That's not what I'm expecting. Now the same type with a filter:
![2017-09-07 12_40_58-kreise - nr17](https://user-images.githubusercontent.com/14105933/30159708-d82699c6-93c9-11e7-90e2-968ab0dfc1f6.png)

As you can see, "no filter" does not mean "all circles" but "no circles".
Is this the intended way?

Regards
Jürgen

**Comment by jgrete** [comment]
I forgot to mention that "secret circles" behave like "personal circles", i.e. they show the circles with "no filter" set

**Comment by daita** [comment]
Was it working fine before ? did you change anything then, or created a new Circle ?

Do you have any javascript error in the console ? (Ctrl-Shift-K on firefox)

**Comment by jgrete** [comment]
I could not tell whether it worked before or whether it worked before. I'm not doing systematic test (which is one of my professions) but merely a casual usability check. I do this because I'm administrating a small (~200 accounts) nextcloud instance for non IT people. Circles would perfectly fit their needs but has to be "bulletproof".

Error msg (only in german, tell me, if you need a translation)
On entering circles:
`Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.  (unbekannt)
Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.[Weitere Informationen]  circles
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/  core.js:4:14346
Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.[Weitere Informationen]  img
Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.[Weitere Informationen]  files
Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.[Weitere Informationen] notifications
Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.[Weitere Informationen]  getOrder
Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.[Weitere Informationen] getcolor.php
Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.[Weitere Informationen]  circles
TypeError: s is null[Weitere Informationen]  merged-template-prepend.js:1194:2
Strict-Transport-Security: Die Verbindung zur Website ist nicht vertrauenswürdig, daher wurde die angegebene Kopfzeile ignoriert.[Weitere Informationen]  settings
        `
On clicking on circle type or filter just the message "Strict-Transport-Security..." is repeated each time.

**Comment by daita** [comment]
at the end of your report: 

`[...] circles TypeError: s is null[Weitere Informationen] merged-template-prepend.js:1194:2[...]`

You should have an arrow on the left of the line, can you click on the arrow and screenshot the details on this bug ?

**Comment by jgrete** [comment]
Sorry, that was at my company and windows, now I'm at home - only linux. I'll try to reproduce it anyway tomorrow

**Comment by jgrete** [comment]
Now I was able to reproduce it:

![spectacle x17326](https://user-images.githubusercontent.com/14105933/30237194-3f211264-952d-11e7-9c99-0871c29d8a57.png)

the link "Weitere Informationen" (engl.: "further information") leads to
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Fehler/Unexpected_type

Hopew this helps
Regards
Juergen

**Comment by daita** [comment]
On that selected line, on the left; between a red cross and 'TypeError' there is a small gray arrow. Can you click on it and make another screen shot ?

**Comment by jgrete** [comment]
![screenshot_20170910_062208](https://user-images.githubusercontent.com/14105933/30246106-7facffc8-95f0-11e7-9cb8-545f27d709b1.png)

**Comment by jgrete** [comment]
![screenshot_20170910_062208](https://user-images.githubusercontent.com/14105933/30246185-d779e552-95f2-11e7-9c10-237f470f8a72.png)

**Comment by daita** [comment]
Alright, can you execute 2 commands in the Javascript console ?

>       var foo = function(res) { console.log(JSON.stringify(res)); };
>       OCA.Circles.api.listCircles(15, '', 1, foo);

Please, type them at the bottom line of the console, and send me the result of the second command: maxence@nextcloud.com

Have you delete an account on the cloud lately ?

**Comment by jgrete** [comment]
Ok, I've sent the output to you. The last account deletion may a couple of weeks ago, not sure...

**Comment by daita** [comment]
Thanks a lot for your report, seems like deleting a user that create a circle generate that issue.

**Comment by jgrete** [comment]
Ok, thank you for your work.
I like circles and the idea behind it (self-organizing users)
Regards
Juergen
