### ISSUE TITLE
lists render with additional line breaks

### ISSUE THREAD

**Issue by miezebieze** [nextcloud/circles#1279]
i wanted to make a list of hosts. these include dots as in "a.b.c" without a dot at the end.
but having an item like "a.b.c" in a bulleted, numbered or todo list renders an extraneous line break, resulting in a (very ugly and confusing) empty line.

i checked the markup file itself and there's no empty line there.
full stops and continuous sentences work without error.

edit: i installed the app "Plain text editor" and it has the same issue.

**Comment by mejo-** [comment]
Dear @miezebieze. The issue you describe probably belongs to Nextcloud Text and got resolved recently. It will be fixed with the upcoming point releases of Nextcloud 25, 26 and 27.
