### ISSUE TITLE
Return value of OCA\\Circles\\Model\\Circle::getInitiator() must be an instance of OCA\\Circles\\Model\\Member()

### ISSUE THREAD

**Issue by kariburger** [nextcloud/circles#1284]
I'm using 25.0.**6** with Circles 25.0.0

When I want to display the users of nextcloud, I get an error message in browser and the nginx-errror log:
`"GET","url":"/nextcloud/ocs/v2.php/cloud/users/details?offset=0&limit=25&search=","message":"Return value of OCA\\Circles\\Model\\Circle::getInitiator() must be an instance of OCA\\Circles\\Model\\Member, null returned in file '/var/local/nextcloud/nextcloud/apps/circles/lib/Model/Circle.php' line 593"`

I didn't change any circles related settings since a long time. The error occured since some updates to NC and/or Circles.

EDIT:
`occ user:list` works fine --> the error is only triggered by `/nextcloud/settings/users` view in the browser.
The backtrace shows, that the request: `GET /nextcloud/ocs/v2.php/cloud/users/details?offset=0&limit=25&search= HTTP/2.0` leads to `/var/local/nextcloud/nextcloud/lib/private/AppFramework/App.php` in line 172, which triggers `/var/local/nextcloud/nextcloud/apps/circles/lib/Model/Circle.php` in line 591 --> the function `getInitiator()`.
I don't understand, why this method is called even if both the initiator and directInitiator are null just for listing all registered users of the nextcloud installation.

I added `error_log((new Exception())->getTraceAsString());` at the corresponding line of the code, which results in the following backtrace:
`"user":"FOOOO","app":"no app in context","method":"GET","url":"/nextcloud/ocs/v2.php/cloud/users/details?offset=0&limit=25&search=","message":"Class 'OCA\\Circles\\Model\\Exception' not found in file '/var/local/nextcloud/nextcloud/apps/circles/lib/Model/Circle.php' line 591","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0","version":"25.0.6.1","exception":{"Exception":"Exception","Message":"Class 'OCA\\Circles\\Model\\Exception' not found in file '/var/local/nextcloud/nextcloud/apps/circles/lib/Model/Circle.php' line 591","Code":0,"Trace":[{"file":"/var/local/nextcloud/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/local/nextcloud/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: FOOO.FIIII.de, request: "GET /nextcloud/ocs/v2.php/cloud/users/details?offset=0&limit=25&search= HTTP/2.0", upstream: "fastcgi://unix:/var/run/fpm-nextcloud.sock:", host: "FOOO.FIIII.de"`

I hope, somebody understand the reason for this call chain.

Bye,
Achim

**Comment by BOFH90** [comment]
Same here with NC version 26.
We use the LDAP integration and the first 2 pages of users are displayed, then the error occours.

**Comment by kariburger** [comment]
Are there too few people to get this bug fixed? - I am currently forced to deactivate the Circles App in Nextcloud to be able to administrate the users of nextcloud. This bug is still active with the latest stable 25.0.8.

**Comment by kariburger** [comment]
Maybe my problem was cause by a wrong config setting for the variable '**overwrite.cli.url**' in 'config/config.php'
Since I tested with '**occ circles:check**' I realized, that my previous setting was wrong. Since I fixed this setting and restartet nginx, I am able to view/edit the nextcloud users with the Circles-App in active state.

So please enhance the documentation and guide admins to this 'occ circles:check' function, to fix the setup in case of problems.

**Comment by skerbis** [comment]
Have the same Problem as @kariburger can't fix ist. What did you do. Had run occ circles:check without any changes. Can't access the user management.

**Comment by kariburger** [comment]
> Have the same Problem as @kariburger can't fix ist. What did you do. Had run occ circles:check without any changes. Can't access the user management.

Did "**occ circles:check**" report any error?
Do you get no problem messages, or don't you find a solution to fix the error message from this check?
In my reported problem case, the problem was obviously caused by my misconfiguration, which didn't cause any other problem outside of circles-app.

**Comment by skerbis** [comment]
This doesn't help

Error: 
OCA\Circles\Model\Circle::getInitiator(): Return value must be of type OCA\Circles\Model\Member, null returned in file '/var/www/vhosts/xxxx/httpdocs/apps/circles/lib/Model/Circle.php' line 591

**Comment by skerbis** [comment]
help please
