### ISSUE TITLE
Add circle hooks

### ISSUE THREAD

**Issue by dtygel** [nextcloud/circles#129]
We believe that Circles App should offer hooks for key events, like:

*  circle creation
*  circle destruction
*  join circle
*  leave circle
*  invite to circle
*  change circle settings (like rename, etc)
*  change member permissions in circle

We at https://github.com/coletivoEITA/ would like to implement these hooks and create a Pull Request. Is this a feature of interest?

**Comment by viniciuscb** [comment]
Please ignore PR #130 . I've made a proposal in PR #131

**Comment by daita** [comment]
@viniciuscb : is it fine to close this request ?

**Comment by viniciuscb** [comment]
@daita Yes, now we have hooks in circles! Nice!

**Comment by daita** [comment]
Obrigado, fika drete :+1:
