### ISSUE TITLE
Change Circle Type

### ISSUE THREAD

**Issue by viniciuscb** [nextcloud/circles#132]
It should have an option to change a circle type, from closed to public and vice-versa.

**Comment by daita** [comment]
I will see if this does not generate conflicts

**Comment by wiswedel** [comment]
@daita Have you checked this yet? Seems a legit request.

**Comment by michag86** [comment]
It makes also sense to make it possible to change a circle type, from closed to a secret and vice-versa.

**Comment by rsmithlal** [comment]
I'm also interested in this functionality. Can someone walk me through the mechanism for the circle type so I can take a look and see about implementing this? I'm using the Collectives app that depends on Circles, but it by default creates secret circles and I'd like the ability to change the circle type after it creates a circle, or at the very least have the option of changing the type of circle that it creates by default or per Collective.

**Comment by crobarcro** [comment]
> It makes also sense to make it possible to change a circle type, from closed to a secret and vice-versa.

Why exactly? Seems like a perfectly sensible thing you might want to do. I've come to this issue because I am also experimenting with the Collectives App.

**Comment by daita** [comment]
This will be implemented in Circles 22.

**Comment by joshtrichards** [comment]
Fixed in #551
