### ISSUE TITLE
Nextcloud 28 compatibility

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/circles#1377]
Right now `circles.files.list.js` tries to extend the file list prototype which does not exist anymore:

![grafik](https://github.com/nextcloud/circles/assets/97337118/6837e565-faf2-42f5-8248-90573110fc27)

**Comment by skjnldsv** [comment]
For simplicity, I suggest we move that view to server.

- Step 1: add backend API in the [existing `ShareApiControler`](https://github.com/nextcloud/server/blob/2693bdf4c1e3f573c4ff1336c0d390e48f31e789/apps/files_sharing/lib/Controller/ShareAPIController.php#L986-L1018)
- Step 2: add frontend service and view
  - https://github.com/nextcloud/server/blob/4e60b3c61e8e0699e341fb62f9f109d2525be5ab/apps/files_sharing/src/services/SharingService.ts
  - https://github.com/nextcloud/server/blob/4e60b3c61e8e0699e341fb62f9f109d2525be5ab/apps/files_sharing/src/views/shares.ts

**Comment by sorbaugh** [comment]
Aligned with @ArtificialOwl . This one can be closed.
