### ISSUE TITLE
Update to 0.13.3 failed

### ISSUE THREAD

**Issue by jgrete** [nextcloud/circles#140]
The update failed with
_An exception occurred while executing 'CREATE TABLE `oc_circles_clouds` (`cloud_id` VARCHAR(64) NOT NULL, `address` VARCHAR(128) NOT NULL, `status` SMALLINT NOT NULL, `note` VARCHAR(255) DEFAULT NULL, `created` DATETIME DEFAULT NULL, PRIMARY KEY(`cloud_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1813 Tablespace for table '`owncloud_db`.`oc_circles_clouds`' exists. Please DISCARD the tablespace before IMPORT._
I'll try to DISCARD the tablespace now - but, why can't the app do this for me? Or at least ask to do it or not and show the proper commands to do it. Most people do not want to mess with databases which structure they do not know.
Regards

**Comment by daita** [comment]
Can you first try to disable/remove and re-enable the app from the Apps Interface ?

**Comment by jgrete** [comment]
I was not successful removing the table, but now missing the frm-file from the mysql directory.
Anyway, it's still not in production.
I now removed the app and verified that the app vanished from the apps directory, downloaded and copied the app to the app-directory. Result the same as above...

**Comment by daita** [comment]
Looks like an issue with your db, is it a restored backup ?

**Comment by jgrete** [comment]
No, the DB ist not a restored backup. I started - as usual - updating as admin using the apps frontend. After facing the error message above I tried to reinstall the app and try to DISCARD the tablespace - which was not successful...
I even moved away the app itself and the database files from their respective directories - no success (installation ok, activation -> error message)
Is there any possibility to **really** **completely** remove all artifacts of circles from the system to try new installation?

It's not a problem at the moment. it's my private cloud. But I'm also responsible for a nextcloud installation in my company which I won't update without a clear path how to solve such issues.

**Comment by daita** [comment]
To totally remove Circles, disable the app and execute those SQL:

>     DROP TABLE `oc_circles_circles`, `oc_circles_clouds`, `oc_circles_groups`, `oc_circles_links`, `oc_circles_members`, `oc_circles_shares`;
>     DELETE FROM `oc_appconfig` WHERE `appid` = 'circles'

**Comment by jgrete** [comment]
I'm getting the same error after applying the SQL statements to my owncloud db. I also tried to DISCARD the tablespace for the table oc_circles_circles following the suggestion made by the error message. But that gave me a 
"Table 'owncloud_db.oc_circles_circles' doesn't exist" 
Hmmm...
I also had a look into the directory /var/lib/mysql/owncloud_db and move away an orphan (?) oc_circles_circles.ibd file. Did not help.
I repeated this with some variations and as a last action I reinstalled the app again, after applying the SQL statements above, cleaning up the /var/lib/mysql/owncloud_db from any circles artifacts, checking for existing of any oc_circles_* db files, restarted apache and mysql, copied the circles app into the apps directory again and tried to activate it in nextcloud. I've got:
```
An exception occurred while executing 'CREATE TABLE `oc_circles_clouds` (`cloud_id` VARCHAR(64) NOT NULL, `address` VARCHAR(128) NOT NULL, `status` SMALLINT NOT NULL, `note` VARCHAR(255) DEFAULT NULL, `created` DATETIME DEFAULT NULL, PRIMARY KEY(`cloud_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB'
: SQLSTATE[42S01]: Base table or view already exists: 1050 Table '`owncloud_db`.`oc_circles_clouds`' already exists
```
`Looking into /var/lib/mysql/owncloud_db:

```
ls -l oc_circles*
-rw-rw---- 1 mysql mysql 25471 22. Okt 05:14 oc_circles_circles.frm
-rw-rw---- 1 mysql mysql 98304 22. Okt 05:14 oc_circles_circles.ibd
-rw-rw---- 1 mysql mysql 65536 22. Okt 05:14 oc_circles_clouds.ibd
-rw-rw---- 1 mysql mysql  2180 22. Okt 05:14 oc_circles_groups.frm
-rw-rw---- 1 mysql mysql 98304 22. Okt 05:14 oc_circles_groups.ibd
-rw-rw---- 1 mysql mysql  2471 22. Okt 05:14 oc_circles_members.frm
-rw-rw---- 1 mysql mysql 98304 22. Okt 05:14 oc_circles_members.ibd
```
It looks like the oc_circles_clouds.frm is missing because mysql assumes that the table still exists (therfore no need for creating one). I guess there's an mysql-internal table which still has an entry for that frm-file.
Before I'm destroying my mysql installation ... Do you have a hint where to look for that entry and whether it's save to delte that entry (and repeat the whole story above)?
Regards

**Comment by jgrete** [comment]
Sorry closing was not my intention...

**Comment by daita** [comment]
Sorry for your lost; but if there is a solution for this issue, you should find it on google.
