### ISSUE TITLE
Activity added to non-member of circles.

### ISSUE THREAD

**Issue by freezxp** [nextcloud/circles#144]
Steps to reproduce

Using account A, create a circle Circle0, set UserB as member. Create Circle1 set UserC as member.
Share folder to Circle0, create/upload any files inside that shared folder.
Login using UserC, check the activity, A create/upload file will be shown inside.
Expected behaviour

By right UserC cant see activity related to Circle0 since UserC belong to Circle1. Is it?

Actual behaviour

UserC can see other circles's activity

Server configuration

Operating system:
Ubuntu 16.04
Web server:
Apache2
Database:
Mariadb 10.2.9
PHP version:
PHP7.0
Nextcloud version: (see Nextcloud admin page)
12.0.3.3
Where did you install Nextcloud from:
Download from nextcloud
Signing status:

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed

paste the results here.
No errors have been found.

**List of activated apps:**
Activity
Circle
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

**Nextcloud configuration:**

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
Insert your Nextcloud log here

#### Browser log
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...

**Comment by daita** [comment]
Thanks for this report !

**Comment by daita** [comment]
Fixed in 0.13.5
