### ISSUE TITLE
Rename circle does not check other circles' names

### ISSUE THREAD

**Issue by viniciuscb** [nextcloud/circles#145]
When I try to create a circle with the same name as one existent, an CircleAlreadyExistsException is thrown. 

When I create a circle with any other name, and then renames to a name of another already existent circle, no error/exception is thrown, and I start having two circles with the same name. In this case, shoudn't an exception be thrown?

**Comment by joshtrichards** [comment]
Fixed in e851038a384348587e8091868c936742f5a2f93d
