### ISSUE TITLE
Ideas about Circles

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/circles#1456]
I am asked more and more by prospects and customers the following question: how can I create a workspace for people to collaborate together, with files, a chat, maybe a knowledge base, a calendar, etc. ?

To date, my answer is the following:
0. go to the Contacts app
1. create a circle
2. add people to the circle
3. go to Files, create and name a folder, share it with the circle
4. go to Talk, create and name a room, share it with the circle
5. go to Collectives, create and name a collective, share it with the circle
6. go to Deck, create and name a board, share it with the circle
7. go to Calendar... 

And while showing this, I am thinking that from a user point of view, it is not trivial, you need first to find the location of the Circles feature which is a bit hidden under the Contacts app...
Then, I have to navigate to each other app, retype 3 or 4 pr 5 times more or less the same phrase "project 1234567", "customer XYZ", "case 123" to name the folder, the Talk room, the deck board, with probability of making typos in the names...
Then, once I've created the Talk room, I must pay attention to share further items with the circle, not with the Talk room which I can alos share items too...

That makes me ask id we could we rethink the way how Circles works to :
0. Go to a dedicated Circles app (or find it a brighter place :)
1. create a circle
2. add people to the circle (btw, I am also thinking it would be great to be able to invite guests users also directly from circles, but that might be anotehr topic 🙂)
3. tick a few checkboxes to select what items you want to be automatically created and shared with your Circle (a folder, maybe a groupfolder at some point?), a Talk room, a collective, and so on...)

Thinking of this makes me also think about the long standing project idea in Nextcloud, where maybe the app could display a list of related resources directly from within one circle's overview. Like the overview of the members, there could be an overview of the linked items (folder, calendar, deck, talk room, etc...)

**Comment by jancborchardt** [comment]
> 3. tick a few checkboxes to select what items you want to be automatically created and shared with your Circle (a folder, maybe a groupfolder at some point?), a Talk room, a collective, and so on...)

I like this part, and it would fix many of the points in the steps that need to be taken, nice! :) 

> 0. Go to a dedicated Circles app (or find it a brighter place :)

We specifically moved Circles to Contacts some releases ago because we already have too many places to manage people-related things. Especially since these are not places which are used on a daily basis, it’s good to consolidate.

**Comment by mejo-** [comment]
Thanks for raising this @maximelehericy! We started a similar discussion around Collectives, Circles and Tables in the office team recently and should definitely align. Cc @juliushaertl @max-nextcloud @datenangebot to put them in the loop.

**Comment by mejo-** [comment]
One problem we have to consider is the problem of "collective ownership". If you merely "share" a resource with a circle, it still is owned by your user. So if the user who originally started the "project" somehow disappears (or their account gets disabled/deleted), the project is in trouble.

To my knowledge, only Collectives and Groupfolders provide a solution to this problem so far, as their resources are not owned by a particular user. Instead, they put them in `appdata` and mount them into the homefolders of all members.

**Comment by maximelehericy** [comment]
I would be happy to bring a small contribution to the collective thinking process here ! :)

**Comment by juliushaertl** [comment]
FYI we've considered that feedback and summarized the outcome in https://github.com/nextcloud/server/issues/42433 to be now further moved on for 29. I'll close this one here for the other overview ticket to address the actual implementation details.
