### ISSUE TITLE
Renaming circles to 'Teams'

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/circles#1505]
Task from https://github.com/nextcloud/server/issues/42433

In order to make the concept of user defined groups more understandable we want to move to the wording of "Team" and "Teams" so we should rename this in any user facing part.

Useful regex for finding translation strings: `/['"\s>]t\(('collectives',\s)?'(.*)circle(.*)'\)/i`

- [x] Circles app itself https://github.com/nextcloud/circles/pull/1512
- [x] UI in contacts (FYI @ChristophWurst) https://github.com/nextcloud/contacts/pull/3818
- [x] Document in app upgrade guide @juliushaertl https://github.com/nextcloud/documentation/pull/11585
- [x] UI in apps that share with circles
  - [x] deck https://github.com/nextcloud/deck/pull/5611
  - [x] collectives https://github.com/nextcloud/collectives/pull/1124
  - [x] groupware (calendar attendees) -> fixed by server icon class adjustment
  - [x] files https://github.com/nextcloud/server/pull/44007 (FYI @sorbaugh)
  - [x] talk (FYI @nickvergessen) https://github.com/nextcloud/spreed/issues/11607
  - [x] Clients (mobile/desktop files+talk) (FYI @tobiasKaminsky @nickvergessen)
      - [x] https://github.com/nextcloud/talk-ios/issues/1544
      - [x] https://github.com/nextcloud/talk-android/issues/3651

FYI @ArtificialOwl

**Comment by ChristophWurst** [comment]
> UI in apps that share with circles

I think this change would be worth a mention on https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_29.html

**Comment by juliushaertl** [comment]
>  groupware (calendar attendees)

@ChristophWurst I couldn't find any user facing string mentioning circle(s) Anything concrete you'd be aware of?

**Comment by ChristophWurst** [comment]
![image](https://github.com/nextcloud/circles/assets/1374172/979985ed-16f2-44a7-9383-ed735479e0b7)

It would only affect the icon, not a string :+1:

**Comment by juliushaertl** [comment]
All right, will be fixed byy https://github.com/nextcloud/server/pull/44007 as it uses the icon class

**Comment by CoreyBurger** [comment]
Can I add a comment here - Teams is a truly terrible name for this project. Assuming it survives trademark issues with MS, I strongly suggest you rename it back to Circles. Why?

There are three groups looking for information under the term "Nextcloud Teams"
1. People looking to integrate Nextcloud with Teams (the MS one that everybody just calls teams)
2. People looking to compare Teams (the MS one) to Nextcloud
3. People looking for information on Nextcloud Teams

All 3 are going to be tripping all over each other and be massively confused.

Circles was unique. Nobody used it, why it worked so well.

Please rename this back
