### ISSUE TITLE
Circles makes server unstable

### ISSUE THREAD

**Issue by l3ochan** [nextcloud/circles#1539]
Hi, I need to enable circles to use collectives but I'm getting this error 
![image](https://github.com/nextcloud/circles/assets/81470534/ccb17bee-1ffe-475f-b3df-97de24f6340d)
I'm encountering lots of errors made by the Activity app because of this app. If you need any information, ask

**Comment by l3ochan** [comment]
I want to add that this generates thousands of errors in minutes.

**Comment by joshtrichards** [comment]
The log entries generated server-side when this is happening would be useful to see.

**Comment by l3ochan** [comment]
weird thing is that it got somewhat fixed in the last NC hub update
