### ISSUE TITLE
onCircleDestruction not fired for private circles

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/circles#155]
I´m using the Nc sharing autocomplete api to get the users / groups / circles to share with. The problem is that the api gives me personal circles which is great but the [onCircleDestruction](https://github.com/nextcloud/circles/blob/master/lib/Service/EventsService.php#L145) doesn´t allow me to listen for deleteion of private circles. This way my acl table will have orphaned entries once personal circles get deleted. And documentation about the different hooks would be great 😁

Repo: https://github.com/splitt3r/mindmaps/blob/feature/rework-js/lib/AppInfo/Application.php#L79-L94

**Comment by daita** [comment]
Are you using the hook to manage shares between circles ?

**Comment by splitt3r** [comment]
For now i simply insert the circles unique id in my acl table and query the mindmap list like https://github.com/splitt3r/mindmaps/blob/feature/rework-js/lib/Db/MindmapMapper.php#L102-L140. Planning to have a look at https://github.com/nextcloud/circles/wiki/PHP-API-v1#circlessharetocirclecircleid-source-type-array-payload-broadcaster to make it more elegant.

**Comment by daita** [comment]
yes, using the API will allow to share your data throw federated circles.

I am aware that the API is still beta, but tell me if you need anything
