### ISSUE TITLE
Request:  Allow Descriptions for Circles

### ISSUE THREAD

**Issue by sunjam** [nextcloud/circles#157]
Right now I just see the names of Circles + owner and users.  It'd be great if owners were able to add a  general description as well.  I'm only able to figure out so much info from the name of the Circle.

**Comment by daita** [comment]
You should be able to add a description in the settings page of a circle.

**Comment by daita** [comment]
re-open the issue with more information if the current description is not enough

**Comment by sunjam** [comment]
Hi @daita,

Not sure if you meant for me to open a new issue.  For further details.... the add description setting is buried when it would make sense to optionally add as part of the original circle creation.  Even when accessing the circle as an admin, you have no idea the description is there unless you click on the Settings icon.
    
- Create circle (no option to add description) -- This would be the perfect place!
- Browse to circle (not automatically opened up)
- Click on Settings icon in top right
- Add a description
    
I opened this issue because I'm connected to almost 50 circles created by various users and none of them have figured out how to add a description -- they assume they have to rely on the Circle title alone.
    
Thanks for reading!

**Comment by daita** [comment]
The UI needs some rework, I will keep this details in mind when working on it.
