### ISSUE TITLE
Share provider does not report access list preventing to chat on a file using talk

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/circles#1575]
Ref https://github.com/nextcloud/circles/blob/e2b38d8a2c65e30c7335b0d4c670ab9e92bb6294/lib/ShareByCircleProvider.php#L650-L658

**Comment by ArtificialOwl** [comment]
https://github.com/nextcloud/circles/pull/1591

**Comment by nickvergessen** [comment]
Thanks, testing the branch in https://github.com/nextcloud/spreed/pull/12462

**Comment by nickvergessen** [comment]
Fixed by #1591
