### ISSUE TITLE
No confirmation when creating a new circle

### ISSUE THREAD

**Issue by sunjam** [nextcloud/circles#160]
There is currently no confirmation given when creating a new circle.  If you attempt to press create again, you receive:
![error-circle-creation](https://user-images.githubusercontent.com/1787238/33917097-1ae41292-df61-11e7-8702-874c51963ed7.png)
This is confusing when connected to a larger group of users since it seems as though someone already made the circle.  After searching under _All Circles_ I realized I actually had made and owned the circle on my original attempt.
    
Upon creation, I recommend some sort of confirmation displayed that the circle does in fact exist.

Edit: **it would make sense for Circles to automatically switch into a newly created circle**.

**Comment by daita** [comment]
This is was I have after clicking on 'Creation', green notification and opening the newly created circle:

![selection_132](https://user-images.githubusercontent.com/1038617/34292541-d754a036-e6f0-11e7-87fa-6d22c65333a0.png)

Please check the console log for any error message

**Comment by joshtrichards** [comment]
> it would make sense for Circles to automatically switch into a newly created circle.

This is now what happens today.
