### ISSUE TITLE
Delete file: Error: OCA\Circles\Model\ShareWrapper::getCircle(): Return value must be of type OCA\Circles\Model\Circle

### ISSUE THREAD

**Issue by Hardexit** [nextcloud/circles#1689]
Hello,

when i try to delete one of my own files i get the following error message:

```
[webdav] Error: OCA\Circles\Model\ShareWrapper::getCircle(): Return value must be of type OCA\Circles\Model\Circle, null returned
	DELETE /remote.php/dav/files/USER/Software/SOFTWARE/SOFTWARE%20Win%20x64%20Test.zip
	from 212.211.191.216 by 98a4e33e-bb0c-1033-9cd7-a7755f636c69 at 11.09.2024, 10:07:54
```

**Comment by Bitgug** [comment]
Same here. Disabling Circles fixes the issue. Activating Circles leads to the problem again.

**Comment by Hardexit** [comment]
I've just realized that there is no longer a circles app, so I'm reporting it here again: https://github.com/nextcloud/contacts/issues/4126

**Comment by Bitgug** [comment]
It's now part of the Nextcloud core. It's still being developed but no longer as a standalone app.
