### ISSUE TITLE
Huge load CPU with undergoing query

### ISSUE THREAD

**Issue by sjvh** [nextcloud/circles#170]
For last weeks I noticed higher load on my cpu. For last few days the cpu load became irrationally high (load avarage of 30 cpu would be doing 1000%).
After checking the process list I noticed that this query is being launched for all users all the time:

```
Query   |    0 | Copying to tmp table | SELECT DISTINCT `s`.`id`, `s`.*, `f`.`fileid`, `f`.`path`, `f`.`permissions` as `f_permissions`, `f`.`storage`, `f`.`path_hash`, `f`.`parent` as `f_parent`, `f`.`name`, `f`.`mimetype`, `f`.`mimepart`, `f`.`size`, `f`.`mtime`, `f`.`storage_mtime`, `f`.`encrypted`, `f`.`unencrypted_size`, `f`.`etag`, `f`.`checksum`, `c`.`type` as `circle_type`, `c`.`name` as `circle_name`, `st`.`id` AS `storage_string_id`, `mo`.`user_id` AS `circle_owner`, `s`.`file_source`, `s`.`file_target`, `s2`.`id` AS `parent_id`, `s2`.`file_target` AS `parent_target`, `s2`.`permissions` AS `parent_perms`, `src_m`.`level` AS `initiator_circle_level`, `src_g`.`level` AS `initiator_group_level` FROM `oc_share` `s` LEFT JOIN `oc_filecache` `f` ON `s`.`file_source` = `f`.`fileid` LEFT JOIN `oc_share` `s2` ON (`s`.`id` = `s2`.`parent`) AND (`s2`.`share_with` = 'username666') LEFT JOIN `oc_circles_members` `src_m` ON (`s`.`uid_initiator` = `src_m`.`user_id`) AND (`src_m`.`user_type` = '1') AND (`s`.`share_with` = `src_m`.`circle_id`) LEFT JOIN `oc_group_user` `src_ncgu` ON `s`.`uid_initiator` = `src_ncgu`.`uid` LEFT JOIN `oc_circles_groups` `src_g` ON (`src_g`.`level` >= '1') AND (`src_ncgu`.`gid` = `src_g`.`group_id`) AND (`s`.`share_with` = `src_g`.`circle_id`) LEFT JOIN `oc_storages` `st` ON `f`.`storage` = `st`.`numeric_id`, `oc_circles_circles` `c` LEFT JOIN `oc_circles_members` `mo` ON (`mo`.`circle_id` = SUBSTR(`c`.`unique_id`, 1, 14)) AND (`mo`.`user_type` = '1') AND (`mo`.`level` = '9') LEFT JOIN `oc_circles_groups` `g` ON (`g`.`circle_id` = SUBSTR(`c`.`unique_id`, 1, 14)) AND (`g`.`level` >= '1') LEFT JOIN `oc_group_user` `ncgu` ON `ncgu`.`gid` = `g`.`group_id`, `oc_circles_members` `m` WHERE (`s`.`share_type` = '7') AND ((`s`.`item_type` = 'file') OR (`s`.`item_type` = 'folder')) AND (`s`.`share_with` = SUBSTR(`c`.`unique_id`, 1, 14)) AND (((`m`.`user_id` = 'username666') AND (`m`.`user_type` = '1') AND (`m`.`circle_id` = SUBSTR(`c`.`unique_id`, 1, 14)) AND (`m`.`level` >= '1')) OR (`ncgu`.`uid` = 'username666')) LIMIT 18446744073709551615 OFFSET 0 |    0.000 |
```

After disabling circles app the load drops to typical 2-4 on avarage. I have fairly large instance of few thousand users

**Comment by gurussia** [comment]
sjvh  comment what are the commands so other users who have the same problems they can trace it.

**Comment by SMA2018** [comment]
Hi,

we can see the same behavior since upgrading to NextCloud 13.

Our surroundings:
1 HAProxy
3 Apache application servers with NextCloud 13 and Redis (4 cores and 8GB Ram)
1 DB Server (4 cores, 16 GB Ram)
300 active users

As soon as the app is activated, Nextcloud will be very slow. This is due to a large number of database queries, which use the server to 100% capacity.

> SELECT DISTINCT `s`.`id`, `s`.*, `f`.`fileid`, `f`.`path`, `f`.`permissions`...

If I deactivate the application Nextcloud runs again very powerful.

salutations
Swen

**Comment by SMA2018** [comment]
Hi,

after the last update from Circle to version 0.14.0 my behavior is no longer reproducible. In the meantime I have also installed NextCloud version 13.0.4. Both could have helped.

Thank you very much for your efforts.
Swen

**Comment by anicoa** [comment]
@daita we have exactly the same issue in our installation with nc 15.0.8 and circles 0.16.6 can you give us some informations how the original issue was solved? should we open a new issue for that?
