### ISSUE TITLE
asynchron synchronisation test fails for nextcloud in subdirectory

### ISSUE THREAD

**Issue by schlagi123** [nextcloud/circles#174]
Hi get the following error message when i want to test the asynchron synchronisation:

{"error":"Client error response [url] https:\/\/host\/index.php\/apps\/circles\/admin\/testAsync [status code] 403 [reason phrase] Forbidden"}

The test connects to the url _https:\/\/host\/index.php\/apps\/circles\/admin\/testAsync_ but my nextcloud is in a subdirectory so the url must be _https:\/\/host\/_**_nextcloud\/_**_index.php\/apps\/circles\/admin\/testAsync_.

**Comment by joshtrichards** [comment]
URLs are generated differently today. Closing.
