### ISSUE TITLE
Adding users for circels

### ISSUE THREAD

**Issue by PiotrIr** [nextcloud/circles#186]
This is a bit of a strange issue. Basically have stated adding people to the circles. However, after maybe 5-10 additions it just stops adding them. I have to close the brower and reopen and then it works again for another 5 or so people , and repeats the same again. Happens for all users in organization on different browsers.

**Comment by PiotrIr** [comment]
I've recorded video of the issue:

[IMG_4222.zip](https://github.com/nextcloud/circles/files/1851690/IMG_4222.zip)

**Comment by happyreacer** [comment]
I think i have the same error but an other situation. When i will add a Name from my contacts, i click on the selection but the user isn't added. But i have a solution... when you search with the first letters and have a scallbar, scroll up and down and the select the contact -> then the contact is added.

**Comment by thammerbacher** [comment]
Same issue here!

**Comment by joshtrichards** [comment]
Cleaning out some old issues. This is a really old one and the UI is completely different these days. If this is still happening, please provide the browser console output. Closing since this issue hasn't seen traffic in >6 years. :)
