### ISSUE TITLE
Feature Request: Edit and Remove individual users in circle

### ISSUE THREAD

**Issue by sunjam** [nextcloud/circles#196]
Hi.  There is currently afaik no way to edit or remove a user in a circle.  I'm finding this extremely problematic while managing circles with multiple people....

- Entire circle must be deleted and re-created from scratch
- Any typos in the ID of a user cannot be changed

**Comment by fgsl** [comment]
For removing a user in a circle you select "kick this member" in status column.

**Comment by sunjam** [comment]
Hmm, could you post a screenshot

**Comment by happyreacer** [comment]
@sunjam click on the status from the member/contact and you open a drop down with "kick this member"

**Comment by sunjam** [comment]
Thanks so much for the suggestions and info.  Here are my thoughts, and I hope this is helpful.

@happyreacer Ah, I see.  Glad this is an option, and want to note kicking members from _Status_ makes very little sense as it is.

![how-do-i-know-to-click](https://user-images.githubusercontent.com/1787238/39642220-d6c63212-4f85-11e8-9a22-f702bf1aff30.png)
- Adding the word _Kick_ or _Remove_ next to _Status_ would make this option clearer.
- Adding a pop up tool tip bubble to the word Status saying "Remove a member via their Status"
- Combining _Joined_ and _Status_ into just _Joined as "Status"_.
        **2018-05-04 17:06:50 (Mail Address)**
Not sure on why time/seconds displayed.
        **2018-05-04 (Mail Address)**
- Kicking a member from Username and/or Join makes more sense.  Clicking on either has no function at this time.
- Adding some color or other indicator that you can click on things for more options, rather than just seeing black text on a white background.
![kick-options](https://user-images.githubusercontent.com/1787238/39642003-085f18b2-4f85-11e8-893f-d36405a591b4.png)

I would also find it helpful to be able to click on a username and edit it rather than kick, especially when it is just a small typo.

Question:  [Is it possible to add a federated user by "remote" or by being on a Trusted Server](https://docs.nextcloud.com/server/12/admin_manual/configuration_files/federated_cloud_sharing_configuration.html) rather than mail address?  I'm unsure of whether I can add federated users who have not set up mail on their Nextcloud.  Should they receive a notification as they would when being sent a federated folder to share?

**Comment by hmt** [comment]
I would have never found out about this without this issue. Please add some visual guide to remove users.

**Comment by wiswedel** [comment]
Let me close this one in favor of https://github.com/nextcloud/circles/issues/549.

Thanks everybody here for paving the way.
