### ISSUE TITLE
A single user can create a circle with all users of an instance and thus spam them

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/circles#206]
* having circles app installed
* user creates a circle with all users of the instance in it
* user shares to that circle
* all users get a notification

We should have a mechanism in place to detect this abusive usage of the circles app.

@nextcloud/designers @daita Do you have an idea how to solve this?

**Comment by jancborchardt** [comment]
We could have some arbitrary restrictions, like warning the admin if a user creates a circle with more than X users? Or even blocking it above Y users? But that’s not very elegant.

But really it seems that this should be possible, no? Maybe we should also have some kind of warning in place for the person doing it, like when you make a circle with more than X people to let them know that every single one of them will be notified on a share.

Or when you share to a big circle/group, Nextcloud could ask if you really want to send the notification mail? But that could make for inconsistent experience.

Any other ideas?

**Comment by MorrisJobke** [comment]
IMO the check for the count makes somehow sense. Maybe need a review by an admin for circles with more than 50 users. We could also say, that this can be enforced in the admin settings like we do for sharing (enforce share end dates etc)

**Comment by fgsl** [comment]
Commit below is the implementation for this issue?

https://github.com/nextcloud/circles/commit/3dd39d06a728bbe8dce8dc406a8bcd867794cdff

**Comment by jancborchardt** [comment]
@daita could you confirm if this is fixed by the commit mentioned by @fgsl?

**Comment by daita** [comment]
Yes, this was fixed by this commit. Please re-open the issue if not.
