### ISSUE TITLE
Exception in constructor of ShareByCircleProvider

### ISSUE THREAD

**Issue by fgsl** [nextcloud/circles#208]
After merge of [PR 203](https://github.com/nextcloud/circles/pull/203) I built the app for testing and found this error:

`:{"Exception":"TypeError","Message":"Argument 4 passed to OCA\\Circles\\Db\\CoreRequestBuilder::__construct() must be an instance of OCA\\Circles\\Service\\TimezoneService, instance of OCA\\Circles\\Service\\MiscService given, called in \/var\/www\/html\/server\/apps\/circles\/lib\/ShareByCircleProvider.php on line 106",...`

It occurs because constructor of CoreRequestBuilder was changed. It is needed to add timezone argument in parent call from ShareByCircleProvider.

**Comment by daita** [comment]
thanks for your PR
