### ISSUE TITLE
Make the app translateable

### ISSUE THREAD

**Issue by oparoz** [nextcloud/circles#21]
The app needs to be translatable.

- [ ] Make sure there are no hardcoded messages
- [x] Add Transifex support

Morris can help with Transifex.

**Comment by daita** [comment]
is it the customgroups entry in transifex ?

**Comment by oparoz** [comment]
No, this will need to be started from scratch, unless you have the same strings?

**Comment by MorrisJobke** [comment]
Transifex included via #22 and https://github.com/nextcloud/docker-ci/commit/551d455da87c10046de4162d58549aea44925b79

**Comment by MorrisJobke** [comment]
And it's on transifex: https://www.transifex.com/nextcloud/nextcloud/circles/

**Comment by daita** [comment]
I think we're good, I'll close the ticket after some test. just waiting for some translation to fit in first.

**Comment by oparoz** [comment]
It's working
