### ISSUE TITLE
Cannot update description for existing circle

### ISSUE THREAD

**Issue by diplodata** [nextcloud/circles#213]
When I try to edit the Description for an existing secret circle and save I get the following error:

`Issue while saving settings: A circle with that name exists`

Steps:
1. create a circle
2. access circle in app and click settings icon
3. edit description and click 'save settings`
4. voila:

![image](https://user-images.githubusercontent.com/25770724/42894985-500e0f9a-8ab0-11e8-8447-99e8e7512548.png)

**Comment by daita** [comment]
fixed next release

**Comment by joshtrichards** [comment]
Fixed long ago. And double-checked it works in the new UI today. Closing. :)
