### ISSUE TITLE
Incompatible with NC14

### ISSUE THREAD

**Issue by rullzer** [nextcloud/circles#215]
We needed to add some functions to the share provider interface.

For circles this means we should add those functions (even if they don't do anything for now). Else php does :boom:

**Comment by juliushaertl** [comment]
@daita

**Comment by daita** [comment]
fixed next release.

**Comment by juliushaertl** [comment]
@daita Is the patch public already? I'd like to do some fixes on the admin settings, but the app is broken on master atm.

**Comment by daita** [comment]
I was just heading to the admin settings thing, but if you want to take care of it, please do.

I will release a branch with some other thing later today.

**Comment by juliushaertl** [comment]
Yes I'll sure I'll to that once master so ready for 14 :+1:

**Comment by moblesmarti** [comment]
With the new version 0.15.0 the problem has been solved.
Thank you!

**Comment by moblesmarti** [comment]
Sorry! I apologize for my previous message. It can be installed but it still does not work correctly...
Class OCA\Circles\ShareByCircleProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Share\IShareProvider::restore) at /var/www/nextcloud/apps/circles/lib/ShareByCircleProvider.php#64

**Comment by daita** [comment]
Can you confirm you have this line in lib/ShareByCircleProvider.php:

https://github.com/nextcloud/circles/blob/a1361a7f2b7fb258038ebca4f37f0bee7f6e4f40/lib/ShareByCircleProvider.php#L718

**Comment by moblesmarti** [comment]
If I confirm that it is.
With 0.15.1 we have been able to install the app but we can not add members.
Thanks!

**Comment by moblesmarti** [comment]
He deleted and reinstalled the application and now it allows me to add mienbros...

**Comment by joshtrichards** [comment]
Fixed in 934b4e1f5fbc3115228b2d2dd56d88134e8bbf69 and elsewhere.
