### ISSUE TITLE
Problem when setting expiration date

### ISSUE THREAD

**Issue by giorgiopaolucci** [nextcloud/circles#220]
Hello everybody.
I'm using nextcloud 12.0.5 with circles 0.14.1. on a debian stretch 64bit.
When I try to share a file to a circle and set an expiration date, the calendar pops up as usual, but when I try to select a date nothing happens and an "invalid date" strings appears on the expiration date field.
Expiration date works with no problems using normal users or groups.....

Any clues?

Thanks in advance.

**Comment by fgsl** [comment]
Hi, @giorgiopaolucci. I couldn't reproduce this bug.
Can you send log of backend and browser generated along this action?

**Comment by joshtrichards** [comment]
Closing due to a lack of follow-up info provided >5 years ago. :)
Also, #286
