### ISSUE TITLE
Allow complete inheritance of class ProviderParser

### ISSUE THREAD

**Issue by fgsl** [nextcloud/circles#223]
Class ProviderParser has three private methods: setSubject, setRichSubject and setParsedSubject.
If they can be changed to protected, it is possible reuse them in new parser classes.

Motivation is issue #163, that has to be refactored. For refactoring, I will combine #163 with #202, so audit of action will include registering of activities. For that, I am writing a new parser class and I want to avoid repeating code.

**Comment by joshtrichards** [comment]
Fixed in #224
