### ISSUE TITLE
Test on more environments

### ISSUE THREAD

**Issue by oparoz** [nextcloud/circles#23]
We currentl only run tests on 7.0 and sqlite.
We need to test on PHP 5.6 and 7.1 and using MySQL and PostgreSQL.

It should be simply a case of adding all these elements to the matrix in the Drones config file.

**Comment by daita** [comment]
should I cross test php/sql ? or I just run mysql on php5.6 and pgsql with php7.1 ?

**Comment by oparoz** [comment]
Ideally, you should run the whole matrix, but focusing on MySQL and sqlite is OK.

Here is an example:
https://travis-ci.org/nextcloud/gallery

pgsql for 7 and 7.1 is missing in this example, but is easy to add.
