### ISSUE TITLE
Adding member to circle by selection does not work

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/circles#230]
After creation of a circle I can't add members by searching and selecting from results. Entering the correct username in the search field and pressing Enter works. But I can't use the search result: If selecting an entry from the results list, the list disappears, but the user is not added. There is no message in the console and no xhr request is sent, it looks like the event handler isn't executed.
I tryed to find the error using Firebug, it  shows the correct data-type="1" and data-ident="username" in result, also the event listener. If I set the "members_search_result" container to "display: block" after a search (I cant stop the fading out, its started when switching to the debugger) and clicking on an search result is working and adds the user to the circle. 
Maybe the click on the search result is intercepted somewhere earlier ?

I'm using NC 12.0.10 with LDAP, Circles 0.14.1 and Firefox 61.0.2

**Comment by daita** [comment]
please install last version of Circles

**Comment by alx-tuilmenau** [comment]
Ok, 0.14.2 fixed the problem. Thank you.

**Comment by va-sak** [comment]
I am using NC 14, circles app v0.15.2 but when i choose a member the drop down menu dissapears without any of my selection
