### ISSUE TITLE
Error: Class 'OCA\Circles\Api\v1\Circles' not found

### ISSUE THREAD

**Issue by ynjo** [nextcloud/circles#234]
Hi,

after upgrading to NC 14, and consequently, upgrading many apps using the web interface, when I activate circles I get several of that:
"Error | index | Error: Class 'OCA\Circles\Api\v1\Circles' not found"

and the server stops working (for example I can't use File).
A similar error (missing class) was just solved in the app "Terms of service".

**Comment by fgsl** [comment]
Which are the version of Circles?
