### ISSUE TITLE
json error code3

### ISSUE THREAD

**Issue by Jock-TNT** [nextcloud/circles#236]
I install cirles plugin but it give an alarm on log.It seems to be a coding error, but I see that it is uft-8 coding as well as other files.Does anyone know why?

netxcloud version: nextcloud-13.0.5
mariadb version: 5.5.60
php version:7.2
Warning | l10n | Failed to load /var/www/nextcloud/apps/circles/l10n/zh_CN.json - json error code: 3
-- | -- | --

**Comment by fgsl** [comment]
This error code is JSON_ERROR_CTRL_CHAR.
It seems that file is ill-formed. 
Do you validate this file?
I couldn't reprodute this error when I change language.

**Comment by joshtrichards** [comment]
Fixed long ago, in 5b42201.

There was an error in that JSON around that time. https://github.com/nextcloud/circles/blob/817fe937849183fe1625095feebeb8de6e550b92/l10n/zh_CN.json
