### ISSUE TITLE
Sharing problem

### ISSUE THREAD

**Issue by Thomas301263** [nextcloud/circles#237]
Hi,
today I activated circles on nextcloud. If I try to share files with members or contacts I will get a mail that tells me that there is something I can look about but I cannot open it.
I get a mail which shows me:

XXXXX hat »20180530_115454.jpg« mit 'test' geteilt.
Zum Öffnen auf die untenstehende Schaltfläche klicken.

If I try to open that file I get:

Interner Serverfehler

Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.
Technische Details

    Entfernte Adresse: xxx.xxx.xxx.xxx
    Anfragekennung: pvPP5GhPDu3TNdFUikZ6

The error message of nextcloud is:

Nextcloud log:

Error | PHP | Undefined index: circle_owner at /var/www/sielstetten.selfhost.me/nextcloud/apps/circles/lib/ShareByCircleProvider.php#651 | 2018-10-01T17:20:32+0200
-- | -- | -- | --
Error | PHP | Undefined index: circle_type at /var/www/sielstetten.selfhost.me/nextcloud/apps/circles/lib/ShareByCircleProvider.php#650 | 2018-10-01T17:20:32+0200
Error | PHP | Undefined index: circle_name at /var/www/sielstetten.selfhost.me/nextcloud/apps/circles/lib/ShareByCircleProvider.php#649

**Comment by fgsl** [comment]
Which are the versions of Nextcloud and Circles?

**Comment by Thomas301263** [comment]
Nextcloud 14.0.1
Circles 0.15.1

**Comment by daita** [comment]
what is the type of circle you're using when sharing a file. Do you have the same issue with every type of circles ?

**Comment by Thomas301263** [comment]
I tried to use official types or private types the result in any case was the same.

**Comment by HeadCrash66** [comment]
Same problem here. Upgraded from 14 to 15 an installed Circles.

It seams that the in needed the array "$data", which is passed to the function "assignShareObjectSharesProperties", does not contain "circle_name", "circle_type" and "circle_owner".

The array seams to be build from an database query, maybe there are some column missing in the database?

Array
(
    [id] => 34
    [share_type] => 7
    [share_with] => 181a4dd330e3c7
    [password] => 
    [uid_owner] => user
    [uid_initiator] => user
    [parent] => 
    [item_type] => folder
    [item_source] => 913
    [item_target] => 
    [file_source] => 913
    [file_target] => /KreisShareTest
    [permissions] => 31
    [stime] => 1549627042
    [accepted] => 0
    [expiration] => 
    [token] => 70124e8d60ca602
    [mail_send] => 0
    [share_name] => 
    [password_by_talk] => 0
    [note] => 
    [hide_download] => 0
    [label] => 
)

**Comment by HeadCrash66** [comment]
I found some kind of crude workaround by adding this to my mysql database.
I'm sure that this will *NOT* work in any cases but for new shares it removes the error.

`-- Install

ALTER TABLE `oc_share` ADD `circle_name` VARCHAR(255) NULL DEFAULT NULL AFTER `label`;
ALTER TABLE `oc_share` ADD `circle_type` INT NULL DEFAULT NULL AFTER `circle_name`;
ALTER TABLE `oc_share` ADD `circle_owner` VARCHAR(255) NULL DEFAULT NULL AFTER `circle_type`;

delimiter //
CREATE TRIGGER circle_name BEFORE INSERT ON oc_share FOR EACH ROW
 BEGIN
  IF NEW.circle_name IS NULL THEN
   SET NEW.circle_name = (SELECT oc_circles_circles.name FROM `oc_circles_circles` WHERE SUBSTRING(oc_circles_circles.unique_id, 1, 14) = NEW.share_with);
  END IF;
 END; //

CREATE TRIGGER circle_type BEFORE INSERT ON oc_share FOR EACH ROW
 BEGIN
  IF NEW.circle_type IS NULL THEN
   SET NEW.circle_type = (SELECT oc_circles_circles.type FROM `oc_circles_circles` WHERE SUBSTRING(oc_circles_circles.unique_id, 1, 14) = NEW.share_with);
  END IF;
 END; //

CREATE TRIGGER circle_owner BEFORE INSERT ON oc_share FOR EACH ROW
 BEGIN
  IF NEW.circle_owner IS NULL THEN
   SET NEW.circle_owner = NEW.uid_owner;
  END IF;
 END; //
delimiter ;


-- Remove

DROP TRIGGER circle_name;
DROP TRIGGER circle_type;
DROP TRIGGER circle_owner;

ALTER TABLE `oc_share` DROP `circle_name`;
ALTER TABLE `oc_share` DROP `circle_type`;
ALTER TABLE `oc_share` DROP `circle_owner`;
`

**Comment by small1** [comment]
I have the same problem.  Clicking on a link from an email throws an internal sever error. 

This is on 15.0.5 and circles 0.16.1

Would be good with a proper fix.

**Comment by GoetheG** [comment]
Unfortunately there are several problems with the Circles app. Me for example, I cannot use this app at all within Nextcloud 14.0.8.

**Comment by joshtrichards** [comment]
Fixed in #266
