### ISSUE TITLE
NC14.0.1 & Circles 0.15.1: "App is not compliant"

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/circles#240]
`occ app:check-code circles`
```
Analysing /var/www/html/apps/circles/files/list.php
 2 errors
    line    3: OCP\User - Static method of deprecated class must not be called
    line    3: OCP\User::checkLoggedIn - Method of deprecated class must not be called
Invalid language file found: l10n/zh_CN.json: Control character error, possibly incorrectly encoded
App is not compliant
```
What does this mean?
Thank you!

**Comment by joshtrichards** [comment]
#236 for the zh_CN json matter.

The rest of the stuff is just for app developers to help identify usage of older APIs, private APIs, etc. 

Closing since there's nothing actionable here and this command doesn't exist any longer since this is handled in a different way now.
