### ISSUE TITLE
Circle members pagination

### ISSUE THREAD

**Issue by maliskovik** [nextcloud/circles#245]
Bug/Feature request?

Environment:
- nextcloud:  14.0.3
- Circles: 0.15.1

Problem  Description:
When viewing the circle members, there is no pagination. All users are displayed at the same time, but not all can be seen. There list does not extend the window, and there is no scroll bar, so the bottom users cannot be viewed unless you:

- Increase screen resollution
-  Zoom out of the webpage ( browser functionality ctrl + - )

2 possible sollutions:

- Add a scroll bar
- add pagination with x users displayed at once.

Note:
If possible, sort users so that the new ones are at the top(including the pending join requests).

**Comment by yennor** [comment]
I've got the same problem.
A simple solution would be, add
    height: 100%
to #memberslist in file

css/navigation.css

**Comment by daita** [comment]
fixed next release
