### ISSUE TITLE
NC-15.0.0 pulls in Circles-0.15.2 and this one does not work

### ISSUE THREAD

**Issue by radoeka** [nextcloud/circles#251]
I just upgraded to NC-15.0.0, that was successful, but the circles app.
 
I can't enable the circle app anymore after the upgrade.  
 
The version that's installed during the upgrade is circles-0.15.2.  
 
According the information at webpage https://apps.nextcloud.com/apps/circles circles is compatibale with NC-15.

After downgrading Circles-0.15.2 to 0.15.1 I was able to enable the circles app again.

It's a bit scary that the NC-15.0 upgrade pulls in a non functional (Circles) app.
 
Information from the logs:
```
Error	index		TypeError: Return value of OC\Http\Client\Response::getHeader() must be of the type string, null returned					2018-12-26T14:44:47+0100
Error	PHP		Undefined offset: 0 at /srv/www/vhosts/<domain/nextcloud-15.0.0/lib/private/Http/Client/Response.php#74	2018-12-26T14:44:47+0100
Info	updater	\OC\Updater::incompatibleAppDisabled: Disabled incompatible app: circles															2018-12-26T14:41:31+0100
```

**Comment by daita** [comment]
Thanks for your report,

please test v0.16.0

**Comment by radoeka** [comment]
Is there no database change between 0.15.1 and 0.16.0 in other words I can safely go forward, but it is also possible to go back to 0.15.1 without problem?

**Comment by daita** [comment]
you should have no issue with 0.16.0, no major change. Just a new version for NC15
