### ISSUE TITLE
Circle description is not readable in dark theme mode

### ISSUE THREAD

**Issue by radoeka** [nextcloud/circles#252]
I think that the screenshot says it all:

![image](https://user-images.githubusercontent.com/2937666/50449230-3985fb80-0926-11e9-87f6-5dc77765a73d.png)

**Comment by radoeka** [comment]
BTW: one has to be the owner of the circle to see this and Nextcloud must be set in dark mode.

**Comment by sunjam** [comment]
My dark theme has a slightly lighter shade of grey and the words "Make a New Circle"  are not readable as they are so light.  Same with "Select a Circle Type" and "Creation".  Use of the dark theme in Circles app is confusing as version 0.16.3 in Nextcloud 15.0.6
![dark-theme](https://user-images.githubusercontent.com/1787238/56628752-dc623400-65ff-11e9-8656-72ba3df7bac8.png)

![dark-theme](https://user-images.githubusercontent.com/1787238/56628455-b8522300-65fe-11e9-8b63-c561b9150e81.gif)

**Comment by dysonsphere-startmail** [comment]
Came to say same here.
No issue with Breeze Dark:
![circleBreezeDark](https://user-images.githubusercontent.com/22195888/121717744-88508d00-caaf-11eb-9da4-1ace7533e899.png)

**Comment by joshtrichards** [comment]
No longer applicable. :) Closing this old issue.
