### ISSUE TITLE
Hard to use the circles configuration on my mobile phone - unable to scroll in web page

### ISSUE THREAD

**Issue by perphilip** [nextcloud/circles#259]
Hi,

I don´t know if this is an issue with circles in particular och the nextcloud web gui in general. When trying to approve a users request to join a circle today I could not scroll the view far enough to reach the member column and select approve with my phone (tried safari/chrome/firefox all with the same behaviour), only on my desktop browser. Any hints?

Also, are only the creator allowed to approve members, I thought admins and maybe even moderator could approve requests to join?

Thanks in advance!
//Per-Philip

**Comment by joshtrichards** [comment]
Item 1 is no longer applicable with the UI changes.

Item 2: Yes, moderates can approve requests (though I don't recall the state 5 years ago).
