### ISSUE TITLE
"Shared to Circles" Menu not working

### ISSUE THREAD

**Issue by OscarXvita** [nextcloud/circles#261]
Reproduce Steps:
Nextcloud 15.0.5 + Circles 0.16.1
Create a public circle "test", then go back and share a folder to test circle.

Then Click "Shared to Circles" Menu in the left panel,
Filter by test,
The progress ring never stop spinning...
nothing is coming out.

Also, chrome has an error thrown
```
if (!filter || (!filter.systemTagIds && _.isUndefined(filter.favorite))) { 
	throw 'Missing filter argument';
}
```

**Comment by asadbm** [comment]
Hi ..

i'm facing the same issue, the progress ring keeps loading with no result. Any advise or fix ..

**Comment by daita** [comment]
This is fixed in NC16.
