### ISSUE TITLE
Missing icons... (reprise)

### ISSUE THREAD

**Issue by noci2012** [nextcloud/circles#264]
Circle version = 0.16.x (According to the CHANGELOG.md)
I only see an Icon for adding users, when hovering to the right of it there are spots that indicate a delete / edit should be possible.
The icon doesn't show though.  

the icon_add_users does show, there is a add_user.svg in the img directory
there is no delete.svg , 
the delete button has no background_image url attribute.  and obviously only shows some transparent data or it is behind the background.

**Comment by joshtrichards** [comment]
No long applicable, but thanks for the original report! :)
