### ISSUE TITLE
Design Integration

### ISSUE THREAD

**Issue by daita** [nextcloud/circles#27]
Apply nextcloud design to the app (cf. Contact)

**Comment by daita** [comment]
And mobile support

**Comment by juliushaertl** [comment]
The app should use the the default app-navigation, and a content list: https://docs.nextcloud.com/server/13/developer_manual/design/list.html

**Comment by wiswedel** [comment]
cc @nextcloud/designers

**Comment by locness3** [comment]
Yes. The app currently doesn't blend in with other nextcloud apps. Some inconsistensies I noticed, as a user :
- The main side navigation is on the bottom-left. Other apps all put their settings there.
- No way to collapse the navigation menu.
- Form items in circle settings have labels on their left, aligned to the right. Everywhere else, they are either on top of the inputs, or to the left, but aligned to the left. BTW, maybe it's just me, but the inputs in circle settings are off-screen by default.

In Circles :
![image](https://user-images.githubusercontent.com/37651007/107920423-3d918f00-6f6d-11eb-8d26-3773c561290a.png)
In Theming :
![image](https://user-images.githubusercontent.com/37651007/107920396-34082700-6f6d-11eb-9f92-d8145d45508b.png)

- Maybe it's a bug, but dropdowns don't have arrows. I wouldn't guess these below were dropdowns, before clicking on them.
![image](https://user-images.githubusercontent.com/37651007/107920325-10dd7780-6f6d-11eb-91f4-f4a0c36e7429.png)

**Comment by daita** [comment]
Hey !
We can close this issue as this is addressed as a priority task to someone from the designer team and the complete UI will be rewritten from scratch for 22.

**Comment by wiswedel** [comment]
@daita Could you please reference that rework task here so the community can catch up and contribute?

**Comment by daita** [comment]
I should have more information within the next few days.

**Comment by locness3** [comment]
But, why is the app inconsistent in the first place? And why is it only being worked on now?

**Comment by skjnldsv** [comment]
@locness3, I don't think this is the place to discuss this 🤔
But in any case, lack of engineers, different focus... But it's good to see some more work on this again, no? :)

**Comment by wiswedel** [comment]
> I don't think this is the place to discuss this 

@skjnldsv Could you please help @locness3 and the community then finding the right place to discuss topics like this?

**Comment by skjnldsv** [comment]
@wiswedel I actually don't think there is a matter to discuss, asking why an app is inconsistent doesn't make sense. Open an issue and point the inconsistencies and provide a suggestion on how to improve. Not just discussing this in a random ticket :shrug: 

Regarding the lack of updates, forum.
