### ISSUE TITLE
Add Scrutinizer

### ISSUE THREAD

**Issue by oparoz** [nextcloud/circles#3]
Scrutinizer is helpful in detecting common pattern and formatting mistakes.

**Comment by oparoz** [comment]
First test run.:
https://scrutinizer-ci.com/g/nextcloud/teams/inspections/c28cb1d9-04d1-4a96-9df2-687dd63d570d

A few issues to fix.

**Comment by MariusBluem** [comment]
Done with https://github.com/nextcloud/circles/commit/397c2ec7d3e0cc6884f5a89354242d668c4ac1da?

**Comment by oparoz** [comment]
Fixed via https://github.com/nextcloud/circles/pull/4
