### ISSUE TITLE
Circles 0.17.3 is incompatible with NC16.0.1?

### ISSUE THREAD

**Issue by duub** [nextcloud/circles#305]
I've updated to NC16 from NC15, and in the update page said that all the apps were compatible, but after updating... some of the apps were disabled because are detected as incompatible.

Can I manually enable Circles 0.17.3 to be used with NC16?

**Comment by duub** [comment]
Updating the page makes the message dissapear, the behaviour during the process is still failing.

I don't see the message anymore so I can't attach the message, I could enable the app without any issue.

**Comment by sunjam** [comment]
Version 16 has changed apps so you can run them regardless of their officially supported reason.

To re-enable, just browse to /settings/apps

**Comment by joshtrichards** [comment]
Closing due to age and because Circles is now a shipped app.
