### ISSUE TITLE
Circles not listed in sharing list of mobile & desktop client

### ISSUE THREAD

**Issue by jbchurn** [nextcloud/circles#308]
Hi,

I am able to create and share to circles successfully from Nextcloud web.

However, when sharing to circles using mobile (Android) and Desktop (windows) clients, my circles is not listed in the sharing list along with users like what I experience in web. As a result, we are unable to make use of circles as a good app/features for sharing.

**Nextcloud**: 15.0.5.3
**MySQL** : 5.7.25
**Circles**: 0.16.4
**Mobile client (Android):** 3.6.2
**Desktop client (Windows):** 2.5.2

Between, I hope to know whether this is an issue (which it suppose to work) Or sharing to circles is yet supported/available in mobile & desktop client.

**Comment by joshtrichards** [comment]
Added long ago. Closing. :)

Specifically:

- Android: Fixed in nextcloud/android#5688
- Desktop: Fixed in nextcloud/desktop#1838
