### ISSUE TITLE
circle shares did not respect forced password for sharebymail

### ISSUE THREAD

**Issue by michag86** [nextcloud/circles#325]
Since 0.13 it is possible to add mail addresses to a circle. After sharing a folder with a circle, email users get a email share for the shared folder.

This share is created without password protection despite "enforce password protection" for share by mail is enabled.

Tested with:
Nextcloud 15.0.10 
Circles 0.16.9 
share by mail 1.5.0

**Comment by noelmartinon** [comment]
Same issue for me and I don't want to share by mail without password so I don't use circles but it would be so useful.

Nextcloud 16.0.4
Circles 0.17.7
Share by mail 1.6.0

**Comment by daita** [comment]
should be implemented in the last release of Circles.
