### ISSUE TITLE
Circles UI does not resize when right sidebar exists

### ISSUE THREAD

**Issue by acinonyx** [nextcloud/circles#339]
Circles 0.17.8
Nextcloud 16.0.5
JavaScript XMPP Chat 3.4.4

The XMPP client creates a right collapsable sidebar. Nevertheless, CIrcles UI does not resize to accommodate the sidebar, effectively hiding buttons for adding members, deleting circles, accepting invitations.

**Comment by joshtrichards** [comment]
Closing since many things have changed and Circles no longer has a dedicated UI. If you still experience this within Nextcloud today, report it and we'll take a look. Thanks for originally reporting. :)
