### ISSUE TITLE
Update Circles	0.17.7 -> 0.17.8 failed:

### ISSUE THREAD

**Issue by gen2** [nextcloud/circles#340]
An exception occurred while executing 'CREATE TABLE oc_circles_links ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, status SMALLINT NOT NULL, circle_id VARCHAR(64) NOT NULL COLLATE BINARY, unique_id VARCHAR(64) DEFAULT NULL COLLATE BINARY, address VARCHAR(128) NOT NULL COLLATE BINARY, token VARCHAR(64) NOT NULL COLLATE BINARY, "key" VARCHAR(64) NOT NULL COLLATE BINARY, creation DATETIME DEFAULT NULL, PRIMARY KEY(id))': SQLSTATE[HY000]: General error: 1 table "oc_circles_links" has more than one primary key

**Comment by hkzlab** [comment]
Suffering from the same issue. I also tried to disable, remove and reinstall the application, but I get the same exception when trying to install it from scratch.

**Comment by daita** [comment]
can you specify the used database ?

**Comment by hkzlab** [comment]
In my case, the default used by this docker image: https://github.com/nextcloud/docker
That is, SQLite

**Comment by gen2** [comment]
> can you specify the used database ?

The admin interface says:
```
Database
Type: sqlite3
Version: 3.29.0
Size: 1.1 MB
```

**Comment by trapeznikov-ap** [comment]
> An exception occurred while executing 'CREATE TABLE oc_circles_links ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, status SMALLINT NOT NULL, circle_id VARCHAR(64) NOT NULL COLLATE BINARY, unique_id VARCHAR(64) DEFAULT NULL COLLATE BINARY, address VARCHAR(128) NOT NULL COLLATE BINARY, token VARCHAR(64) NOT NULL COLLATE BINARY, "key" VARCHAR(64) NOT NULL COLLATE BINARY, creation DATETIME DEFAULT NULL, PRIMARY KEY(id))': SQLSTATE[HY000]: General error: 1 table "oc_circles_links" has more than one primary key


In my case, this table was empty. I deleted the empty table, started the update manually and turned off maintenance mode.

**Comment by daita** [comment]
should be fixed in 0.17.10

**Comment by FieryCod** [comment]
@daita Still I'm able to reproduce it with 0.17.10.

`An exception occurred while executing 'CREATE TABLE oc_circles_links ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, status SMALLINT NOT NULL, circle_id VARCHAR(64) NOT NULL COLLATE BINARY, unique_id VARCHAR(64) DEFAULT NULL COLLATE BINARY, address VARCHAR(128) NOT NULL COLLATE BINARY, token VARCHAR(64) NOT NULL COLLATE BINARY, "key" VARCHAR(64) NOT NULL COLLATE BINARY, creation DATETIME DEFAULT NULL, PRIMARY KEY(id))': SQLSTATE[HY000]: General error: 1 table "oc_circles_links" has more than one primary key
`
