### ISSUE TITLE
Add group doesn't work with member limit -1|0

### ISSUE THREAD

**Issue by genestouxguy** [nextcloud/circles#342]
Hi,

Apps version : 0.17.8
Nextcloud version : 17.0.0

I tried 3 ways :

1. param Maximum member to 0
2. param Maximum member to -1
3. param Maximum member to 100

For 1 & 2, I obtained the error :
`Group contains too many members`

For 3 the group added.

For information, the param by default (admin) for Max member is 300 and the groups contain 1 to 3 members for now.

Sorry for my english.

**Comment by croessner** [comment]
I can confirm this.

NC 17.0.1 and NC 16.0.5 both with current latest Circle app installed

**Comment by codejp3** [comment]
Same here. 
NC 17.01
Circles 0.17.10

**Comment by s3r3ndipit** [comment]
Same here, even with 0 member inside the group trying to link with a circle.

NC 18.0.2
Circles 0.18.3
