### ISSUE TITLE
add users without confirmation in a closed group

### ISSUE THREAD

**Issue by duub** [nextcloud/circles#360]
Why I can't add a user directly in a closed group? Is it possible to add a third option to the existing two?

1- invitation-acceptance
2- join-acceptance protocol 
3- an Admin adds a user without confirmation (same  functionality existing in secret groups)
I prefer to lose the first option, than the third... if simplicity is a preference...

**Comment by duub** [comment]
I'm having a user case where i want to add users directly to a group and at the same time let them create shared links from the shared folder... So i would like to change the functionality here or #359

**Comment by Art4** [comment]
In NC 17 you can go to Admin settings -> group ware to configure the circles app. There you can active the option "Skip invitation step to closed circles". I hope this will solve your issue.

**Comment by joshtrichards** [comment]
Fixed in #416
