### ISSUE TITLE
Circles App allows sharing via email w/o expiration date or password 

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/circles#370]
The Circles App allows to enter mail addresses as Circle-Member and shares content with the respective persons via a link.

For sharing via link we've set an fixed expiration date of 40 days in future and force password protection. If you can use mail addresses in circles, this circumvents these security settings, since neither an expiration date nor a password constraint can be set.
In the settings of the circles app under Settings / Groupware I could not prevent the inclusion of mail addresses in circles.

Either there's a possibility to prevent adding mail addresses I've just not found or this seems to be a bug.

**Comment by Volker-K** [comment]
After more than one year: Lots of circles I've found exist of mail addresses isntead of user IDs because their owners are searching the members-to-be by entering their mail address and when the respective user ID is shown hitting ENTER and adding the mail address instead of the user ID to the circle. 
So I must have a chance to disable adding mail addresses to prevent this.
Is there already a configuraion parameter?

**Comment by wiswedel** [comment]
@daita Can you please check and confirm for @Volker-K if that's still gonna be the case after https://github.com/nextcloud/circles/pull/551?

**Comment by Volker-K** [comment]
btw any mail address entered as  circle member is, as far as I get it, nonsense because such member can't access files shared with the circle before being added and can't share own objects with the circle. After being added the receive a mail that files have been shared with them but get no link to access them.

**Comment by daita** [comment]
You should be able to limit the creation of External members using `occ config:app:set --value '1' circles accounts_only`

@Volker-E in fact, when adding an external member, a mail is generated with the list of already shared files

@wiswedel about the next version of Circles, while this is not implemented, the code is already written in a way to allow a filter on the type of members that can be generated.

**Comment by Volker-K** [comment]
> occ config:app:set --value '1' circles accounts_only

Thank you, it works fine. Is there any documentation of configuraiton parameters?

> in fact, when adding an external member, a mail is generated with the list of already shared files. A password can also be enforced

Well, in our case the mail sent after adding the memeber by mail address doesn't contain any links. Maybe it's becaus I couldn't migrate to NC20 right now. Anyway, we don't want to enable anonymous shares in this way, so my problem is solved by switching off those mail address feature.

Thank you!

**Comment by daita** [comment]
> > occ config:app:set --value '1' circles accounts_only
> 
> Thank you, it works fine. Is there any documentation of configuraiton parameters?

No, anyone willing to help is welcomed :D

> > in fact, when adding an external member, a mail is generated with the list of already shared files. A password can also be enforced
> 
> Well, in our case the mail sent after adding the memeber by mail address doesn't contain any links. Maybe it's becaus I couldn't migrate to NC20 right now. Anyway, we don't want to enable anonymous shares in this way, so my problem is solved by switching off those mail address feature.
> 
> Thank you!

Glad I could help you
