### ISSUE TITLE
Create OCS endpoint

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/circles#377]
To allow clients add/change circles an OCS endpoint is needed.

(Currently I would only need this for testing, as I can then automatically create a new circle)

**Comment by marinofaggiana** [comment]
Yes, we need to implement it in client, @tobiasKaminsky did you do something ?

**Comment by tobiasKaminsky** [comment]
Library: https://github.com/nextcloud/android-library/pull/414
App: https://github.com/nextcloud/android/pull/5688

**Comment by marinofaggiana** [comment]
Thx but where a documentation is not available ?

**Comment by daita** [comment]
@marinofaggiana do you need OCS to create circles and members right now ?

**Comment by marinofaggiana** [comment]
yes, read/create bla bla bla :-)

**Comment by tobiasKaminsky** [comment]
@marinofaggiana please let us first focus on sharing to circle, and then later discuss if and when we want to add circle management to mobile (#featureParity)

**Comment by daita** [comment]
Implemented in Circles 22
