### ISSUE TITLE
Circles does not install on nextcloud 18

### ISSUE THREAD

**Issue by RealSnoopyDog** [nextcloud/circles#383]
If I activate the circles app in the nextcloud Apps manager, I only get the error message

"There is no table with name 'username.oc_circles_circles' in the schema."

which is correct, because this table should be created during the installation and/or activation of the Circles app. 
This problem was present also with nextcloud 17.
Database is postgres

**Comment by iggapres** [comment]
Hi,
I have a quite similar issue here.
Nextcloud is 18.0.4 and Circles doesn't want to activate with error :

```
 An exception occurred while executing 'ALTER TABLE oc_circles_tokens ADD member_id VARCHAR(15) DEFAULT NULL, ADD accepted SMALLINT DEFAULT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

It worked fine with Nextcloud version up to 17. The upgrade to 18.x.y broke it.

**Comment by joshtrichards** [comment]
@iggapres: I don't recall the details in 2020, but this seems to reflect current manual: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#mysql-utf8mb4

@RealSnoopyDog No idea why you experienced that at the time. Maybe a really old version was installed previously but removed or something? It's too long ago to know with any certainty. If you experience this today, let us know.
