### ISSUE TITLE
occ circles:manage:create throws error

### ISSUE THREAD

**Issue by h-alf** [nextcloud/circles#420]
Hi,

if you run "occ circles:manage:create owner closed circlename" throws the following error message:
```
Error: Call to undefined method OCA\Circles\Db\MembersRequest::token() in .../apps/circles/lib/Db/MembersRequest.php:454
Stack trace:
#0 .../apps/circles/lib/Service/CirclesService.php(168): OCA\Circles\Db\MembersRequest->createMember(Object(OCA\Circles\Model\Member))
#1 .../apps/circles/lib/Command/CirclesCreate.php(133): OCA\Circles\Service\CirclesService->createCircle(4, 'tabuAbi2022-D-V...', 'Kreismanager')
#2 .../3rdparty/symfony/console/Command/Command.php(255): OCA\Circles\Command\CirclesCreate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 .../core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 .../3rdparty/symfony/console/Application.php(915): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 .../3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Circles\Command\CirclesCreate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 .../3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 .../lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 .../console.php(99): OC\Console\Application->run()
#9 .../occ(11): require_once('...')
#10 {main}
```
The circle is created but with out an owner.

It can just be deleted by "occ circles:manage:destroy circleID".

Nextcloud version: 18.0.3

How can I get the cli command to work?

cheers
Harald

**Comment by daita** [comment]
looks like you are running the version from the repository, please run `composer install`

**Comment by dnorak** [comment]
I think i encounter the same issue.
When i try to create a cicle from CLI i have : 

`./occ circles:manage:create dnorak public exemple`
> An unhandled exception has been thrown:
> Error: Call to undefined method OCA\Circles\Db\MembersRequest::token() in /var/www/html/custom_apps/circles/lib/Db/MembersRequest.php:469
> Stack trace:
> #0 /var/www/html/custom_apps/circles/lib/GlobalScale/CircleCreate.php(76): OCA\Circles\Db\MembersRequest->createMember(Object(OCA\Circles\Model\Member))
> #1 /var/www/html/custom_apps/circles/lib/Service/GSUpstreamService.php(140): OCA\Circles\GlobalScale\CircleCreate->manage(Object(OCA\Circles\Model\GlobalScale\GSEvent))
> #2 /var/www/html/custom_apps/circles/lib/Service/CirclesService.php(193): OCA\Circles\Service\GSUpstreamService->newEvent(Object(OCA\Circles\Model\GlobalScale\GSEvent))
> #3 /var/www/html/custom_apps/circles/lib/Command/CirclesCreate.php(133): OCA\Circles\Service\CirclesService->createCircle(8, 'exemple', 'dnorak')
> #4 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Circles\Command\CirclesCreate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #5 /var/www/html/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #6 /var/www/html/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #7 /var/www/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Circles\Command\CirclesCreate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #8 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #9 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #10 /var/www/html/console.php(100): OC\Console\Application->run()
> #11 /var/www/html/occ(11): require_once('/var/www/html/c...')


But !
When i try to delete it :

 `./occ circles:manage:destroy 429b02f02adeb3`
An unhandled exception has been thrown:
> Error: Call to undefined method daita\MySmallPhpTools\Model\Request::setProtocols() in /var/www/html/custom_apps/circles/lib/Service/GSUpstreamService.php:235
> Stack trace:
> #0 /var/www/html/custom_apps/circles/lib/Service/GSUpstreamService.php(146): OCA\Circles\Service\GSUpstreamService->confirmEvent(Object(OCA\Circles\Model\GlobalScale\GSEvent))
> #1 /var/www/html/custom_apps/circles/lib/Service/CirclesService.php(430): OCA\Circles\Service\GSUpstreamService->newEvent(Object(OCA\Circles\Model\GlobalScale\GSEvent))
> #2 /var/www/html/custom_apps/circles/lib/Command/CirclesDestroy.php(91): OCA\Circles\Service\CirclesService->removeCircle('429b02f02adeb3', true)
> #3 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Circles\Command\CirclesDestroy->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #4 /var/www/html/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #5 /var/www/html/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #6 /var/www/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Circles\Command\CirclesDestroy), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #7 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #8 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #9 /var/www/html/console.php(100): OC\Console\Application->run()
> #10 /var/www/html/occ(11): require_once('/var/www/html/c...')


And : when i try to create it from web interface, the cicle is not accessible and i think it's for the same reason : they can't be deleted, unable to connect to it...

I'm on Alpine docker version of nextcloud version 19.0
I installed cicle from web interface

I try composer install :
`/var/www/html/custom_apps/circles $ composer install`

> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating optimized autoload files

**Comment by joshtrichards** [comment]
This code no longer exists today. Closing.
