### ISSUE TITLE
 0.18.7 has broken migrations

### ISSUE THREAD

**Issue by ndurchx** [nextcloud/circles#434]
On Update vom  0.18.5 to  0.18.7, the following fatal errors occur:

Failed to load repair step for circles: Repair step 'OCA\Circles\Migration\GenerateUniqueIdOnCreatedCircle' is unknown
Failed to load repair step for circles: Repair step 'OCA\Circles\Migration\UsingShortenUniqueIdInsteadOfCircleId' is unknown

So the app and every other function using a circle is not usable anymore. Example on calendar:

```
[webdav] Fatal: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT DISTINCT `c`.`unique_id`, `c`.`id`, `c`.`name`, `c`.`description`, `c`.`settings`, `c`.`type`, `contact_addressbook`, `contact_groupname`, `c`.`creation`, `u`.`user_id` AS `viewer_userid`, `u`.`status` AS `viewer_status`, `u`.`member_id` AS `viewer_member_id`, `u`.`level` AS `viewer_level`, `o`.`user_id` AS `owner_userid`, `o`.`status` AS `owner_status`, `o`.`level` AS `owner_level` FROM `oc_circle_circles` `c` LEFT JOIN `oc_circle_members` `u` ON (`u`.`circle_id` = `c`.`unique_id`) AND (`u`.`user_id` = ?) AND (`u`.`user_type` = ?) LEFT JOIN `oc_circle_members` `o` ON (`o`.`circle_id` = `c`.`unique_id`) AND (`o`.`level` = ?) AND (`o`.`user_type` = ?) LEFT JOIN `oc_group_user` `ncgu` ON `ncgu`.`uid` = ? LEFT JOIN `oc_circle_groups` `g` ON (`ncgu`.`gid` = `g`.`group_id`) AND (`g`.`circle_id` = ``c``.``unique_id``) WHERE (`c`.`unique_id` = ?) AND ((`c`.`type` = ?) OR ((`c`.`type` = ?) AND ((`u`.`level` >= ?) OR (`c`.`name` = ?) OR (`c`.`unique_id` = ?) OR (`g`.`level` >= ?))) OR (`c`.`type` = ?) OR (`c`.`type` = ?))' with params ["ndurchx", 1, 9, 1, "ndurchx", "c71763ac82d537", 1, 2, 1, "", "c71763ac82d537", 1, 4, 8]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'c``.``unique_id``) WHERE (`c`.`unique_id` = 'c71763ac82d537') AND ((`c`.`type...' at line 1 at <<closure>>
```

**Comment by kroerig** [comment]
I think this part is the problem:

`(`g`.`circle_id` = ``c``.``unique_id``)`

The are two backticks too much. But where is this in the source code?

I tried this query manually in MySQL-client it worked with just single backticks:

`(`g`.`circle_id` = `c`.`unique_id`)`

**Comment by jolly-jump** [comment]
I found the same Problem, update from nextcloud 18.0.5 to 18.0.7 which updates from and to the ( probably) same versions the above author states. And after that the Repair Error occur and circles are gone.

**Comment by timm2k** [comment]
`GenerateUniqueIdOnCreatedCircle.php` and `UsingShortenUniqueIdInsteadOfCircleId.php` had been removed from lib/Migrations but are still referenced in `appinfo/info.xml`.

**Comment by daita** [comment]
anyone from here willing to test https://github.com/nextcloud/circles/releases/tag/v0.18.8 ?

**Comment by ndurchx** [comment]
Updated to 0.19 with Nextcloud 19. Bug is not present.
