### ISSUE TITLE
Cannot sync calendar shared with a circle in third-party app

### ISSUE THREAD

**Issue by chikamichi** [nextcloud/circles#441]
Hi,

With a fresh Nextcloud 19.0.0.12 setup and only the DAV, Calendar and Circles apps enabled, I get an error running the following scenario:

1. Create a public circle, invite a `member, member` to it
2. Create a calendar, share it (read-write) with the public circle
3. In a third-party app (any will reproduce the server-side error I guess; tested with Thunderbird/TbSync and KOrganizer), add the Nextcloud instance's DAV endpoint
4. Sync

It triggers the following error in Nextcloud logs:

```
[...]
172.30.0.2 - - [18/Jun/2020:01:12:12 +0000] "PROPFIND /remote.php/dav/calendars/95998cb2-3964-103a-951d-1d6b4ce8dd30/REDACTED_shared_by_453f4ba6-4528-103a-8efb-ef8587f3a42f/ HTTP/1.1" 401 1747 "-"  "Thunderbird CalDAV/CardDAV Lightning/68.9.0"
172.30.0.2 - REDACTED@DOMAIN.TLD [18/Jun/2020:01:12:12 +0000] "PROPFIND /remote.php/dav/calendars/95998cb2-3964-103a-951d-1d6b4ce8dd30/REDACTED_shared_by_453f4ba6-4528-103a-8efb-ef8587f3a42f/ HTTP/1.1" 500 1489 "-" "Thunderbird CalDAV/CardDAV Lightning/68.9.0"
[...]
```

[TBSync](https://addons.thunderbird.net/fr/thunderbird/addon/tbsync/) is nice enough to report the actual error log:

```
WARNING: 500 (URL: https://nextcloud.DOMAIN.TLD/remote.php/dav/calendars/95998cb2-3964-103a-951d-1d6b4ce8dd30/REDACTED_shared_by_453f4ba6-4528-103a-8efb-ef8587f3a42f/ (PROPFIND) Request: <d:propfind xmlns:d="DAV"><d:prop><d:resourcetype /><d:displayname /></d:prop></d:propfind> Response: <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>TypeError</s:exception> <s:message>Argument 2 passed to OCA\Circles\Db\CirclesRequest::getCircle() must be of type string, null given, called in /var/www/html/custom_apps/circles/lib/Service/CirclesService.php on line 248</s:message> </d:error> )
```

Ie. error is _Argument 2 passed to OCA\Circles\Db\CirclesRequest::getCircle() must be of type string, null given, called in /var/www/html/custom_apps/circles/lib/Service/CirclesService.php on line 248_.

[Here's the code](https://github.com/nextcloud/circles/blob/8e3c403ce82d416c1522850ad0897e2e1ab42aad/lib/Service/CirclesService.php#L248). 2nd argument is `$this->userId`.

Unfortunately I don't have the stacktrace, but I guess it's possible to trace the calls starting from remote.php/dav/calendars.

With that shared-with-a-circle calendar still up and running:
- syncing with another, non-shared calendar, works just fine
- syncing with another, shared-with-a-regular-group, works just fine

So failed sync is limited to calendars shared with a circle.

**Comment by chikamichi** [comment]
@ndurchx are you experiencing the same issue?

**Comment by ndurchx** [comment]
Yes, it is the same. A calendar shared over a private circle cannot be synced with Dav5x anymore. Same error message.

**Comment by hogshead-revival-widow** [comment]
This bug also affects querying the principal. This has the effect, that on macOS the standard calendar app can't get a list of calendars, so they are not accessible at all.

See for yourself:

```

from datetime import datetime
import sys
import caldav

client = caldav.DAVClient(url=CALDAV_SERVER,
                              username=CALDAV_USERNAME,
                              password=CALDAV_PASSWORD)
calendars = client.principal().calendars()

```

Throws error:

```

File "/Users/kristophsachsenweger/Desktop/test.py", line 54, in <module>
    get_calendar()
  File "/Users/kristophsachsenweger/Desktop/test.py", line 32, in get_calendar
    calendars = client.principal().calendars()
  File "/usr/local/lib/python3.7/site-packages/caldav/objects.py", line 432, in calendars
    return self.calendar_home_set.calendars()
  File "/usr/local/lib/python3.7/site-packages/caldav/objects.py", line 308, in calendars
    data = self.children(cdav.Calendar.tag)
  File "/usr/local/lib/python3.7/site-packages/caldav/objects.py", line 92, in children
    response = self._query_properties(props, depth)
  File "/usr/local/lib/python3.7/site-packages/caldav/objects.py", line 130, in _query_properties
    return self._query(root, depth)
  File "/usr/local/lib/python3.7/site-packages/caldav/objects.py", line 171, in _query
    raise error.exception_by_method[query_method](errmsg(ret))
caldav.lib.error.PropfindError: 500 Internal Server Error

b'<?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>TypeError</s:exception>\n  <s:message>Argument 2 passed to OCA\\Circles\\Db\\CirclesRequest::getCircle() must be of the type string, null given, called in /var/www/cloud.systemli.org/nextcloud-19.0.0/apps/circles/lib/Service/CirclesService.php on line 248</s:message>\n</d:error>\n'
```

**Comment by daita** [comment]
Hello,

Please, you should create a ticket on @nextcloud/calendar repository.

**Comment by georgehrke** [comment]
@daita See the error message posted above. The actual error is triggered in `/apps/circles/lib/Service/CirclesService.php on line 248`

**Comment by daita** [comment]
Can you try this patch ? https://github.com/nextcloud/circles/pull/444

**Comment by desser-code** [comment]
I've the same problem. Please fix these issue.
