### ISSUE TITLE
Sharing with circles throws Error "Fehler beim Erstellen der Freigabe" but in fact works

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/circles#443]
Nextcloud 18.0.3
Circles App 18.08

After sucessful migration to Nextcloud 18 and Upgrade of Circles app sharing with crcles shows an error: 

![image](https://user-images.githubusercontent.com/34368929/86242087-63b41b80-bba4-11ea-9f63-b0da7d924918.png)

Nothing to find about it in Apache or Nextcloud log.

After reloading the page it suddly is shared:
![image](https://user-images.githubusercontent.com/34368929/86244607-86483380-bba8-11ea-8bc1-4bf8f696423b.png)

Any Ideas?

**Comment by terrysxm** [comment]
Nous avons le même problème ! Une fois le cercle privé choisi pour le partage, il y a un temps mort puis la pop-up apparaît signalant une erreur lors du partage ... mais si on rafraîchit la page, on voit que finalement le partage a eu lieu. Quelqu'un peut-il apporter une aide sur ce bug ? ... nous ne pouvons mettre en PROD Nextcloud à cause de ce bug.

**Comment by Siruv** [comment]
Hello,

I have the exact same problem, when I share a file or a folder to a circle.

In the nextcloud log I have the errors in attachments.

Thanks for your help.

Regards,


Nextcloud version: 19.0.1
Circle version: 0.19.4
![Capture d’écran de 2020-08-12 11-33-00](https://user-images.githubusercontent.com/2051135/90000864-fd391780-dc90-11ea-8e82-b1fa63e64b65.png)

**Comment by Volker-K** [comment]
Disappeared.
