### ISSUE TITLE
Uncaught ReferenceError: escapeHTML is not defined

### ISSUE THREAD

**Issue by azul** [nextcloud/circles#446]
When using the current master branch of circles app with the current master branch of nextcloud server `escapeHTML` is not available anymore. This leads to uncaught reference errors:
```
Uncaught ReferenceError: escapeHTML is not defined
    at Object.generateTmplCircle (circles.app.elements.js:427)
    at listCirclesResult (circles.app.results.circles.js:159)
    at Circles.onCallback (circles.v1.js:72)
    at Object.<anonymous> (circles.v1.circles.js:60)
    at l (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at M (jquery.js:8757)
    at XMLHttpRequest.<anonymous> (jquery.js:9123)
generateTmplCircle	@	circles.app.elements.js:427
listCirclesResult	@	circles.app.results.circles.js:159
onCallback	@	circles.v1.js:72
(anonymous)	@	circles.v1.circles.js:60
l	@	jquery.js:556
fireWith	@	jquery.js:556
M	@	jquery.js:556
(anonymous)	@	jquery.js:556
load (async)		
send	@	jquery.js:556
ajax	@	jquery.js:556
listCircles	@	circles.v1.circles.js:51
displayCirclesList	@	circles.app.navigation.js:224
(anonymous)	@	circles.app.elements.js:205
dispatch	@	jquery.js:556
v.handle	@	jquery.js:556
```

I triggered this by creating a circle and then looking ofr it in the circle list.
The ajax request to fetch the circle will work just fine and the response is okay.
But the rendering is aborted due to the error printed above.

**Comment by mejo-** [comment]
Probably you have to import escapeHTML manually now:

```
import escapeHTML from 'escape-html'
```

I'm unsure what's the correct place to do this import though.

**Comment by azul** [comment]
@mejo- yes... there's no build process and therefore no way to include things for the circles app. I think i will work around this by just defining `escape-html` in the circle apps js like in the npm package: https://github.com/component/escape-html/blob/master/index.js

**Comment by azul** [comment]
https://github.com/nextcloud/circles/tree/workarounds-nc20 fixes the issues i am seeing.

**Comment by mejo-** [comment]
This problem still exists with latest NC and circles master branches. The patch by @azul results in *all* circles being listed to any user, regardless of e.g. whether it's a secret circle where the user isn't member.

**Comment by joshtrichards** [comment]
Fixed awhile ago.
See #489
