### ISSUE TITLE
Cannot sync calendar shared with a circle in third-party app 

### ISSUE THREAD

**Issue by desser-code** [nextcloud/circles#454]
Hello, there is the following problem:
If I create a calendar and share it with a circle. The users who are members of this circle can see the shared calendar in the web interface, but it's not possible to integrate it into thunderbird, for example.
The following error message is returned:

An error occurred while writing to calendar test 2! Further information can be found below.
Status code: 2147746065, The request cannot be processed.
Server Replied with 500

Can someone help me?

**Comment by desser-code** [comment]
there is progress here

**Comment by joshtrichards** [comment]
We'd need to see the server-side logs that are generating that 500 error.

**Comment by joshtrichards** [comment]
Closing due to lack of needed info.
