### ISSUE TITLE
Add a Member function is not working

### ISSUE THREAD

**Issue by SLYtiger16** [nextcloud/circles#465]
Nextcloud version: 19.0.0
Circles version: 0.19.3

### Steps to Reproduce 
1.  Create a circle of any kind
2.  click a user from the add user drop down

### Expected Behavior
User is added to the circle

### Actual Behavior
After about 5-10 seconds the user is listed and a Green notification pops up saying the user has been added. Then hit refresh or change to another circle and come back and the user is not there anymore. Also if I try to adjust their role I get the error that the user does not exist.
**Adding user**
![image](https://user-images.githubusercontent.com/36513817/87606560-e79bf680-c6c0-11ea-9122-1239c35022ce.png)
**Changing Role**
![image](https://user-images.githubusercontent.com/36513817/87606619-0bf7d300-c6c1-11ea-9b43-ef6ff110dad7.png)
**After Page Refresh or navigation away and back**
![image](https://user-images.githubusercontent.com/36513817/87606658-2467ed80-c6c1-11ea-8df7-2fd2a6b7f556.png)

**Comment by SLYtiger16** [comment]
Also - There are no logs and server restart has no effect.

**Comment by daita** [comment]
In your `config/config.php` there should be a list of _trusted_domains_; is the first one from the list a valid domain (or IP) that is reachable from the https hosting your Nextcloud ?

**Comment by gerryvaz** [comment]
@daita 
Changing the first entry in the config.php _trusted_domains_ block to the nextcloud domain resolved issue in my instance.

> 'trusted_domains' => 
> array (
> **_0 => 'nextcloud.example.com',_**
> ),


Thanks.

**Comment by SLYtiger16** [comment]
@daita
Changing the first entry in the config.php trusted_domains block to the nextcloud domain Does Not resolve the issue in my instance.

'trusted_domains' =>
array (
0 => 'cloud.mysite.com',
1 => '192.168.xxx.xxx'
),

Thanks.

**Comment by daita** [comment]
is https://cloud.mysite.com/ available locally from your httpd ?

**Comment by Camui87** [comment]
I have the same problem, complete new instance of Nextcloud 19.0.1 with PHP7.4 and PostgreSQL12
I can create a circle and for a few seconds everything looks fine when members are added, but they weren't added at all. If a role is changed I also get the message that the user doenst exist.

But the trusted domain to the first entry in the array of trusted domains and the domain is also reachable from within dns of the server

**Comment by ranti71** [comment]
Same here! Tried different clean installations with and without proxy. The tip with trusted domain or local availability doesn´t have effects.

**Comment by daita** [comment]
I might have found the issue, will release later today or tomorrow

**Comment by daita** [comment]
Please upgrade the app to 0.19.4, available on the app store.

**Comment by Camui87** [comment]
The Update solved the problem for me, thank you very much!! :-)

**Comment by mejo-** [comment]
Seems like there's several separate issues that broke the `add a member` function.

On my dev setup (latest NC 20 from master branch), I'm not able at all to directly add members via circles app UI. When I add a member as circles owner, they're not added yet. I have to login as the other user and `join` the circle.

**Comment by daita** [comment]
Can you run `./occ circles:test` and post me the result ? Also, do you have any entry in the nextcloud.log ?

**Comment by mejo-** [comment]
> Can you run `./occ circles:test` and post me the result ?

Interestingly that doesn't work at all:

```
www-data@36abba926559:~/html$ ./occ circles:test
- Simple request on nextcloud.local/index.php/csrftoken: 
In TRequest.php line 293:

  28 - Resolving timed out after 10000 milliseconds - {"protocols":["https"],"used_protocol":"https",  
  "host":"nextcloud.local","url":"index.php/csrftoken","timeout":10,"type":0,"data":[]}                
```

I use the [nextcloude-docker-dev](https://github.com/juliushaertl/nextcloud-docker-dev) for development. Apparently there's something broken with the circles app on this docker setup. It's basically an apache+php+nextcloud container and a nginx container as reverse proxy.

**Comment by mejo-** [comment]
> Also, do you have any entry in the nextcloud.log ?

Just the logged API call:

```
nextcloud_1          | 192.168.21.6 - - [07/Aug/2020:12:23:23 +0000] "PUT /index.php/apps/circles/v1/circles/97060dfd82aa1a/member HTTP/1.1" 201 1319 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
```

I also tried with direct API calls - with the same result. So apparently it's not a frontend problem but rather something on the backend side.

**Comment by daita** [comment]
what is the value of `overwrite.cli.url` on `config/config.php` ?

**Comment by mejo-** [comment]
> what is the value of overwrite.cli.url in config/config.php ?

```
  'overwrite.cli.url' => 'nextcloud.local',
  'allow_local_remote_servers' => true,
```

Also:

```
$ ./occ config:app:get -- circles self_signed_cert
1
```

**Comment by daita** [comment]
ok, the value should be 'http://nextcloud.local'

**Comment by mejo-** [comment]
Wow, that was fast! Thanks a lot, indeed that fixed the first problem (I set it to `https://nextcloud.local`). Now the test continues, but fails at a later stage:

```
- Simple request on https://nextcloud.local/index.php/csrftoken: 200
- Async request is sent, now waiting 5 seconds
- Pause is over, checking results for b42101c5-0ddf-48f5-859a-e47a45c35ce4
nextcloud.local fail
```

**Comment by daita** [comment]
Can you restart the command while looking at the logs your httpd, and paste any new lines generated.

**Comment by mejo-** [comment]
To be honest, that's not much. Just the `csrftoken` request (one access log entry each from nextcloud and proxy container):

```
proxy_1              | nginx.1    | nextcloud.local 192.168.21.5 - - [07/Aug/2020:15:02:39 +0000] "GET /index.php/csrftoken? HTTP/2.0" 200 103 "-" "-"
nextcloud_1          | 192.168.21.6 - - [07/Aug/2020:15:02:39 +0000] "GET /index.php/csrftoken? HTTP/1.1" 200 1388 "-" "-"
```

I also had to manually set `$request->setVerifyPeer(false);` in `Command::CirclesTest::testLocalAddress()` since it doesn't take into account the `self_signed_cert` app setting.

**Comment by SLYtiger16** [comment]
> Please upgrade the app to 0.19.4, available on the app store.

This update did not solve the issue with my instance :(

**Comment by mejo-** [comment]
> I also had to manually set $request->setVerifyPeer(false); in Command::CirclesTest::testLocalAddress() since it doesn't take into account the self_signed_cert app setting.

I now created PR #473 to fix this.

**Comment by SLYtiger16** [comment]
> Can you run `./occ circles:test` and post me the result ? Also, do you have any entry in the nextcloud.log ?
My instance:

````
./occ circles:test
- Simple request on https://192.168.xxx.xxx/index.php/csrftoken: 200
- Async request is sent, now waiting 5 seconds
- Pause is over, checking results for TOKEN_NUMBER
192.168.xxx.xxx fail
````
> Also, do you have any entry in the nextcloud.log ?
Negative

> what is the value of `overwrite.cli.url` in `config/config.php` ?

`http://192.168.xxx.xxx`

**Comment by SLYtiger16** [comment]
Update: I am behind an NGINX Reverse Proxy and altered my `overwriteprotocol` from `https` to `http` and now the `./occ circles:test` succeeds with the same output as above but with an `ok` instead of `fail`

Sadly though, this has not had any impact on the add member function

**Comment by ranti71** [comment]
Thanks a lot for the different tips! It seems, that the self_signed_cert app setting has no effect. When i changed the self signed certificate against a trusted certificate, all works fine.

**Comment by mejo-** [comment]
Ok, so after some further testing, I'm confident that my issue is related to the self-signed certificate.

I searched for all instances of `Request()` (from `daita\MySmallPhpTools\Model\Request`) in the app code and made them aware of the `self_signed_cert` app config setting. Afterwards, `./occ circles:test` succeeded and even adding members to a circle was successful again. See PR #474.

**Comment by aleadco** [comment]
Hi guys, I have already fixed the problem in my instance.
It happens that the hosts file did not have the correct parameters established in relation to the IP-Domain, therefore it was not able to solve a request in the service's own domain.
Ubuntu 18.04
`nano / etc / hosts`
Verify that the IP and domain
`192.168.0.0  cloud.domain.net  cloud`

**Comment by alx-tuilmenau** [comment]
Hi, there is another problem: the daita/my-small-php-tools do not support a proxy setting. A proxy defined in Netxcloud's config.php is not used for the circle-requests,  so these fail on installations where a proxy is needed.

**Comment by daita** [comment]
I will work on this issue asap

**Comment by SLYtiger16** [comment]
I did get mine fixed, it is related to being behind a NAT and DNS resolution locally

**Comment by Vestarija** [comment]
Hi, same problem here... Nextcloud 19.0.4 ans Circles 0.19.7. 
Where can I find log for this bug?

**Comment by Vestarija** [comment]
I followed some tutorials about this issues, and I generate a new cert in .pem 
I have followed some tutorials and I make this import:
`./occ security:certificates:import "/etc/ssl/mydomain.pem"`

Without success... I'm desperate! many hours for nothing, if someone has an idea

**Comment by Vestarija** [comment]
It's resolved, there was a problem with the intermediate certificate.
Thanks to myself 😂

**Comment by joshtrichards** [comment]
OP's matter was resolved in https://github.com/nextcloud/circles/issues/465#issuecomment-693331277 so closing. Other bits were covered in #473 and #474.

The proxy matter mentioned in https://github.com/nextcloud/circles/issues/465#issuecomment-692770490 needs confirmation it's still relevant and, if so, should go in its own issue rather than be buried in this one (that's the only reason I can see for this issue being left open). I'm going to close this out. If someone brings the proxy matter up, we'll take a look at it separately. :)

**Comment by mejo-** [comment]
Thanks so much for the issue cleanup work here @joshtrichards :heart:
