### ISSUE TITLE
Expose `LEVEL_*`, `STATUS_*` and `TYPE_*` constants in API

### ISSUE THREAD

**Issue by mejo-** [nextcloud/circles#466]
The circles app uses those constants internally and its values are required for several API-exposed functions. Therefore it would be a good idea to expose the constants in the APIs themselves, no?

**Comment by mejo-** [comment]
If you agree, then I could prepare a PR to do so.

**Comment by daita** [comment]
yes please !

**Comment by mejo-** [comment]
Perfect. PR is at #472 :blush:
