### ISSUE TITLE
Reject request through notifications doesn't work

### ISSUE THREAD

**Issue by annettekusma** [nextcloud/circles#471]
Edit: I wonder if this might be related to #211 

When I get a notification that a user wants to join a certain circle, trying to reject the request via the notification itself throws up a popup with an error message, and the user's request has in fact not been removed from the circle. Going to the circles app and rejecting the user there works fine. 

I get the notification:
![bild](https://user-images.githubusercontent.com/30964670/89566071-c9d53380-d81f-11ea-8ef8-05040e32f505.png)

I choose the "Neka"-button ("Deny"), and I get the error "Failed to execute operation":
![bild](https://user-images.githubusercontent.com/30964670/89566126-de193080-d81f-11ea-9bbb-a88faeaa8e7e.png)
(By the way, the "Acceptera"-button does nothing at all, except shift button-border-color on mouse-over; it doesn't even shift back when mouse is not over anymore; clicking does not give any error messages or logs or other results, the notification stays the exact way it is)

The user's request is still there ("Skickar begäran" - "Sending request")
![bild](https://user-images.githubusercontent.com/30964670/89566286-30f2e800-d820-11ea-896b-fdc45b46ed51.png)

And I have to remove the request in the circles app, which works fine ("Avslå begäran" - "Reject request")
![bild](https://user-images.githubusercontent.com/30964670/89566373-60095980-d820-11ea-8297-3687c76b944f.png)

Here's the log:

It doesn't seem that the copy-to-clipboard-feature copies all of it, and I can't seem to highlight the text, so, here's a screenshot as well: 

![bild](https://user-images.githubusercontent.com/30964670/89566811-ffc6e780-d820-11ea-8c75-beea0edca735.png)

I'm using Firefox 78.0.2 to access nextcloud 19.0.1 via docker; circles 0.19.3, notifications 2.7.0

**Comment by daita** [comment]
Hello and thanks for your report.

This should be fixed in the next release of Circles.
