### ISSUE TITLE
Cannot create circles...

### ISSUE THREAD

**Issue by theshades** [nextcloud/circles#475]
App Version: 0.19.4
Error: Circle '{name}' could not be created: no error message

Steps:
1) Install
2) Go to Circles tab
3) Try to create any type of circle

Settings:
Default

**Comment by daita** [comment]
A new version of the app will be release today, could you upgrade and try again. If you still have issue, would you please check if there is new entries in data/nextcloud.log ?

**Comment by theshades** [comment]
I will give this a shot tonight! Thanks for the work and sorry for the
delay... this went to an email/notification I hadnt been checking for while.
---
Thanks,

Justin Bowen

**Comment by vincentdeniau** [comment]
Hello there,
I have the same error with the latest release (0.20.4)
![image](https://user-images.githubusercontent.com/11630701/100591961-c7c74100-32f6-11eb-86c0-15c2550d5fea.png)

**Comment by jainayro** [comment]
@vincentdeniau . 
Same problem as vincent.
but did not check the log.
I noticed that once i click the logo to refresh circles everything reappears.
But upon creating a circle i receive the following error: 	Circle '{name}' could not be created: no error message

when i refresh again the circle reappears

**Comment by theshades** [comment]
Still seeing this too, similar thing where if I refresh the page it
shows... but I get the {name} error... I think it may be related to CSP

---
Thanks,

Justin Bowen, GCIH, GPEN, GCWN, GCFA
Sr. Security Engineer
Enterprise Security

**Comment by daita** [comment]
Hello everyone on this topic.

Please upgrade to last version. If you still have issue, please run `./occ circles:test`

**Comment by vincentdeniau** [comment]
Hello @daita ,
Unfortunately, same issue with v0.20.6
Result of` occ cicles:test` :

```
An unhandled exception has been thrown:
Error: Call to undefined method daita\MySmallPhpTools\Model\Request::type() in /var/www/html/apps/circles/lib/Command/CirclesTest.php:187
Stack trace:
#0 /var/www/html/apps/circles/lib/Command/CirclesTest.php(129): OCA\Circles\Command\CirclesTest->testRequest(Object(Symfony\Component\Console\Output\ConsoleOutput), 'GET', 'core.CSRFToken....')
#1 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Circles\Command\CirclesTest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(1000): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Circles\Command\CirclesTest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/console.php(100): OC\Console\Application->run()
#8 /var/www/html/occ(11): require_once('/var/www/html/c...')
www-data@SVR-NEXTCLOUD:~/html$
```

**Comment by jainayro** [comment]
Yes same error. Error same on the new version.
occ cirlces:test result
An unhandled exception has been thrown:
Error: Call to undefined method daita\MySmallPhpTools\Model\Request::type() in /var/www/nextc                                                                                                loud/apps/circles/lib/Command/CirclesTest.php:187
Stack trace:
#0 /var/www/nextcloud/apps/circles/lib/Command/CirclesTest.php(129): OCA\Circles\Command\Circ                                                                                                lesTest->testRequest()
#1 /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(258): OCA\Circles\                                                                                                Command\CirclesTest->execute()
#2 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->                                                                                                run()
#3 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\                                                                                                Base->run()
#4 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Componen                                                                                                t\Console\Application->doRunCommand()
#5 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Componen                                                                                                t\Console\Application->doRun()
#6 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\App                                                                                                lication->run()
#7 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#8 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

**Comment by daita** [comment]
can you post the result of ./occ app:list ?

**Comment by jainayro** [comment]
@daita 
`An unhandled exception has been thrown:
Error: Call to undefined method daita\MySmallPhpTools\Model\Request::type() in /var/www/nextc loud/apps/circles/lib/Command/CirclesTest.php:187
Stack trace:
#0 /var/www/nextcloud/apps/circles/lib/Command/CirclesTest.php(129): OCA\Circles\Command\Circ lesTest->testRequest()
#1 /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(258): OCA\Circles\ Command\CirclesTest->execute()
#2 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command-> run()
#3 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\ Base->run()
#4 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Componen t\Console\Application->doRunCommand()
#5 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Componen t\Console\Application->doRun()
#6 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\App lication->run()
#7 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#8 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')`

**Comment by daita** [comment]
you have this error while running `./occ app:list` ?
if so, please disable the Circles apps, and run the command again

**Comment by jainayro** [comment]
@daita .
sorry i sent you yesterdays error.
here i send you the right result.
`Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - analytics: 3.1.0
  - announcementcenter: 4.0.0
  - apporder: 0.11.0
  - audioplayer: 3.0.0
  - breezedark: 20.0.1
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - carnet: 0.23.7
  - circles: 0.20.6
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - cospend: 1.2.2
  - dashboard: 7.0.0
  - dav: 1.16.1
  - deck: 1.2.2
  - duplicatefinder: 0.0.4
  - event_update_notification: 1.1.0
  - external: 3.7.1
  - extract: 1.2.5
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.1
  - files_antivirus: 3.0.0
  - files_automatedtagging: 1.10.0
  - files_mindmap: 0.0.23
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - flowupload: 1.1.2
  - forms: 2.0.4
  - geoblocker: 0.4.0
  - groupfolders: 8.2.0
  - guests: 1.6.1
  - health: 0.1.3
  - integration_gitlab: 0.0.8
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.7.1
  - maps: 0.1.8
  - metadata: 0.12.0
  - news: 15.0.6
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.1.0
  - password_policy: 1.10.1
  - passwords: 2020.11.1
  - pdfdraw: 0.1.0
  - phonetrack: 0.6.5
  - photos: 1.2.0
  - polls: 1.6.2
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quicknotes: 0.6.3
  - quota_warning: 1.9.1
  - radio: 1.0.0
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.10
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - social: 0.4.1
  - socialsharing_email: 2.1.0
  - socialsharing_facebook: 2.1.0
  - socialsharing_twitter: 2.1.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - timemanager: 0.1.6
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - user_usage_report: 1.4.2
  - viewer: 1.4.0
  - w2g2: 3.0.3
  - weather_status: 1.0.0
  - whiteboard: 0.0.3
  - workflow_ocr: 1.20.1
  - workflow_script: 1.5.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - facerecognition
  - files_external
  - user_ldap
`

**Comment by daita** [comment]
please upgrade the social app

**Comment by jainayro** [comment]
Hi @daita ,
Seems to work now.
I will test it more in detail later and let you know.

Thanks,
George.

**Comment by magicvince** [comment]
Have the same problem, works after activate social (but I didn't use it before).

**Comment by Niclas-sol** [comment]
Have the same issue on 20.0.3. With social enabled or disabled

**Comment by daita** [comment]
please paste the result of:

`./occ circles:test`

and 

`./occ app:list`

**Comment by Niclas-sol** [comment]
**circles:test**
- GET request on ://*********/index.php/csrftoken: 200
- POST request on ://**********/index.php/apps/circles/v1/gs/broadcast/async/test-dummy-token/: 200
An unhandled exception has been thrown:
TypeError: Return value of OCA\Circles\Service\ConfigService::getLocalInstance() must be of the type string, null returned in /var/www/html/nextcloud/apps/circles/lib/Service/ConfigService.php:560
Stack trace:
#0 /var/www/html/nextcloud/apps/circles/lib/Service/GSUpstreamService.php(135): OCA\Circles\Service\ConfigService->getLocalInstance()
#1 /var/www/html/nextcloud/apps/circles/lib/Command/CirclesTest.php(146): OCA\Circles\Service\GSUpstreamService->newEvent()
#2 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Circles\Command\CirclesTest->execute()
#3 /var/www/html/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#4 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1000): OC\Core\Command\Base->run()
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#6 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#7 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#8 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#9 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')


**app:list**

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - announcementcenter: 4.0.0
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - circles: 0.20.6
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - deck: 1.2.2
  - event_update_notification: 1.1.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trackdownloads: 1.9.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - recommendations: 0.8.0
  - registration: 0.5.2
  - richdocuments: 3.7.11
  - richdocumentscode: 6.4.202
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - social: 0.4.2
  - socialsharing_email: 2.1.0
  - spreed: 10.0.3
  - support: 1.3.0
  - survey_client: 1.8.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - talk_simple_poll: 1.2.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_saml: 3.3.1
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - mail
  - user_ldap

**Comment by daita** [comment]
This is strange, can you send me a mail at maxence@nextcloud with the result of:

- `./occ config:app:get circles local_cloud_id`
- `./occ config:system:get overwrite.cli.url`
- `./occ config:system:get trusted_domains`

Thanks!

**Comment by Niclas-sol** [comment]
Changing the 'overwrite.cli.url' => 'domain.tld', to 'https://domain.tld', solves the error for me.
Big thanks to @daita for the quick solution!

**Comment by daita** [comment]
you're welcome, I will close this ticket as it looks like everyone got his issue fixed

**Comment by Sanookmakmak** [comment]
I can create circles but can't add members to any circle on Nextcloud 20.0.6 with Circles app 0.20.6.

![Snipaste_2021-01-31_04-09-46](https://user-images.githubusercontent.com/24833757/106373492-4f264480-637a-11eb-88f1-1bd33c851c9e.png)

`occ config:system:get overwrite.cli.url` goes to the https URI

`occ circles:test` is "ok"

`occ app:check-code circles` is NOT ok

```
Analysing /var/www/clients/client1/web9/web/apps/circles/files/list.php
 2 errors
    line    3: OCP\User - Static method of deprecated class must not be called
    line    3: OCP\User::checkLoggedIn - Method of deprecated class must not be called
Analysing /var/www/clients/client1/web9/web/apps/circles/lib/GlobalScale/AGlobalScaleEvent.php
 2 errors
    line  255: != - is discouraged
    line  256: != - is discouraged
App is not compliant

```

**Comment by gorsing** [comment]
sudo -u apache php occ app:check-code circles
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
Analysing /var/www/html/nextcloud/apps/circles/files/list.php
 2 errors
    line    3: OCP\User - Static method of deprecated class must not be called
    line    3: OCP\User::checkLoggedIn - Method of deprecated class must not be called
Analysing /var/www/html/nextcloud/apps/circles/lib/GlobalScale/AGlobalScaleEvent.php
 2 errors
    line  255: != - is discouraged
    line  256: != - is discouraged
App is not compliant
