### ISSUE TITLE
Feature request - user defines password for e-mail shares

### ISSUE THREAD

**Issue by sushifrick** [nextcloud/circles#478]
Dear circles team,

in our university-Nextcloud we have disabled the option to send the passwords for e-mail shares via mails for security reasons. We want our users to communicate the password via another way of communication, not unencrypted e-mails. Therefore when using the option "Password enforcement" for a circle, neither the person who shares nor the person who receives the share gets the generated password.

It would be great if the option "Password enforcement" would allow to set or generate a password which is constant for the circle and thus can be communicated to the members directly.

Kind regards and greetings from Kiel, Germany
Sascha

**Comment by daita** [comment]
Hello,

you're talking about a static password which would be the same for everyone and every shares from/to this Circle ?

**Comment by sushifrick** [comment]
Yes I do. Another way would be to set a password for each e-mail User in the member list, but I think that is much more complicated to implement. And after all that is much better than no password (or an unknown random password), as we have now.

**Comment by daita** [comment]
This should be implemented in the last version (0.19.5) that is already available on our appstore
