### ISSUE TITLE
Allow circles to be owned by multiple people

### ISSUE THREAD

**Issue by azul** [nextcloud/circles#484]
My understanding is that if the owner of a circle destroys their account
the circle will disappear.

That is unfortunate for everyone else in the circle.

There's a number of options to mitigate this:
* allow multiple owners for a circle and only clean it up when the last owner destroys their account.
* allow the users to transfer circle ownership.
* transfer the circle to one of the admins if the owner deletes their account.

My preference would be on the first option.
The second one requires the user that is about to delete their account to remember steps right at that time.
The last option requires the server to pick a successor somewhat randomly and might not be what the user deleting their account expected would happen.

**Comment by daita** [comment]
This is the current process when a Circle's owner got its account destroyed:

- the ownership is transferred to the oldest admin member;
- if no admin, ownership is transfered to the oldest moderator;
- if no moderator, ownership is transferred to the oldest member.

If you have observed a different behavior this is a bug.

**Comment by daita** [comment]
I will close this report as a feature already exist to fill the gap. However, you can re-open this one if you think you witnessed an issue.

**Comment by azul** [comment]
Thanks... so looks like the issue we were afraid of is not an issue. :smile:
