### ISSUE TITLE
App Circles - Dark Mode

### ISSUE THREAD

**Issue by tobi614** [nextcloud/circles#485]
### Steps to reproduce
Enable Dark Mode under settings -> accessibility. Go to Main App "Data".

### Expected behaviour
Background is black. Icon is white.

### Actual behaviour
Both is black.
![Error](https://user-images.githubusercontent.com/64694684/92498126-885aee00-f1fa-11ea-8aa0-a55cb4db74b4.JPG)

### Versions
Nextcloud: 19.0.1
Circles: 0.19.5

**Comment by arsounet** [comment]
circles-dark.svg file is missing.
Joined it here. Maybe you can add it to repo for future updates?
![circles-dark](https://github.com/nextcloud/circles/assets/758451/701bc727-9a44-43ed-a55d-bf25f59e4553)

**Comment by joshtrichards** [comment]
Fixed in #1560
