### ISSUE TITLE
An exception occurred while executing 'INSERT INTO

### ISSUE THREAD

**Issue by c0r3dump3d** [nextcloud/circles#487]
Hi, I have problems when I try to create a new Circle after update Nextcloud to version 18.0.7, an error in the Database:

`An exception occurred while executing 'INSERT INTO \"oc_circle_circles\" (\"creation\", \"unique_id\", \"long_id\", \"name\", \"description\", \"contact_addressbook\", \"contact_groupname\", \"settings\", \"type\") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"2020-09-25 10:52:46\", \"02a9c422425972\", \"02a9c4224259724088ddd9bdba82d228984a516a5d379ac3\", \"Prueba\", \"\", 0, \"\", \"[]\", 1]:\n\nSQLSTATE[23505]: Unique violation: 7 ERROR: llave duplicada viola restricci\u00f3n de unicidad \u00aboc_circle_circles_pkey\u00bb\nDETAIL: Ya existe la llave (id)=(48)`

Circle version: 0.18.9
Nextcloud version: 18.0.7

**Comment by c0r3dump3d** [comment]
Hi, I try to make a clean:

`sudo -u apache /usr/bin/php /var/www/html/nextcloud/occ  circles:clean`

But the error persists.

**Comment by daita** [comment]
which database are you using ?

**Comment by c0r3dump3d** [comment]
PostgresSQL database

**Comment by c0r3dump3d** [comment]
The problem has been solved by upgrading to the latest version 0.18.10.
