### ISSUE TITLE
[NC20] Circles v0.19.5 broken on NC20

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/circles#489]
Circles are not listed in the current release on latest NC20RC. Ther error does not occur with NC19.
I get a console error (Firefox and Chrome). 

Uncaught ReferenceError: escapeHTML is not defined
    generateTmplMember circles.app.elements.js:449
    displayMembers circles.app.navigation.js:380
    Ember 2
    onCallback circles.v1.js:74
    request circles.v1.js:67
    jQuery 4

Uncaught ReferenceError: resultCircles is not defined
    at new Navigation (circles.app.js?v=2a60ec7b-6:126)
    at HTMLDocument.<anonymous> (circles.app.js?v=2a60ec7b-6:236)
    at l (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at e.fn.init.m.fn.ready (jquery.js:3496)
    at circles.app.js?v=2a60ec7b-6:114

Reproduction
* Create a new circle
* Add a user
* click on a circle category

Expected: 
* List of circles is presented
Actually
* List is empty
* error in console (see above)

**Comment by dartcafe** [comment]
While looking thru the branches searching for a solution, I found https://github.com/nextcloud/circles/tree/workarounds-nc20 
Adding the patch seems to work.

**Comment by daita** [comment]
a new release for NC20 is available on the appstore (0.20.0)
