### ISSUE TITLE
NC20: Uncaught ReferenceError: resultCircles is not defined

### ISSUE THREAD

**Issue by s-rosenfeld** [nextcloud/circles#503]
Circles stopped working after upgrade to NC20. Versions:

NextCloud: 20.0.0
Circles 0.20.2

![Screenshot_20201007_100716](https://user-images.githubusercontent.com/12949115/95293752-1ae7bf00-0885-11eb-87a1-39e51db28cde.png)

**Comment by s-rosenfeld** [comment]
It happens on change current NC20 app. For example, click to Files, then click to Circles. Circles page loads partially and JS console will contains this error. Click again to Circles to full load of page without this error. Please fix it :)

**Comment by small1** [comment]
I can confirm this. Same issue on all nc20 servers i have.

**Comment by majinmo** [comment]
Issue can be confirmed with Google Chrome Version 86.0.4240.75. Firefox is working. NC20

**Comment by s-rosenfeld** [comment]
Safari (Mac) and Edge (Windows) also working ok. The problem apparently only in Chrome, both Linux,Windows, Mac. But ... in Windows and Mac _sometimes_ it working ok, about 5% :) And never in Linux :(

Google Chrome Version 86.0.4240.75
Kubuntu 20.04 LTS

**Comment by fancycode** [comment]
Problem is that the javascript files are loaded with `defer` making the order undefined. It can happen that the file defining `resultCircles` is loaded/executed after the one that uses `resultCircles`.

**Comment by sushifrick** [comment]
Same problem here, any suggestions for a fix or workaround on this topic using Google Chrome?

**Comment by s-rosenfeld** [comment]
I'm tired of waiting for this simple fix. It is below. The target file to fix: /var/www/nextcloud/apps/circles/templates/navigate.php, the patch itself below.

[navigate.php.diff.txt](https://github.com/nextcloud/circles/files/5581163/navigate.php.diff.txt)

**Comment by sushifrick** [comment]
> I'm tired of waiting for this simple fix. It is below. The target file to fix: /var/www/nextcloud/apps/circles/templates/navigate.php, the patch itself below.
> 
> [navigate.php.diff.txt](https://github.com/nextcloud/circles/files/5581163/navigate.php.diff.txt)

Hi @s-rosenfeld, 

thank you for the patch . I can confirm that changing the order within the list the problem is gone, thank you very much. I cannot see another problem due to this fix.

**Comment by s-rosenfeld** [comment]
The problem fixed in 0.20.6 release. Thank you daita.
