### ISSUE TITLE
Getting message "Error creating the share" when sharing a file despite the share is created correctly

### ISSUE THREAD

**Issue by jkahrs** [nextcloud/circles#510]
I'm getting a strange error when sharing files/folders in nextcloud 20.
On adding the share the following popup comes up:
![error_creating_the_share](https://user-images.githubusercontent.com/10754859/97292191-3b36e800-184b-11eb-8834-1875910b35c2.png)

The JavaScript Console gives the following:
![js_error](https://user-images.githubusercontent.com/10754859/97292564-aed8f500-184b-11eb-879a-0f4b48b924cc.png)

**Comment by jkahrs** [comment]
I just saw this is duplicate to: https://github.com/nextcloud/server/issues/21120

Closing

**Comment by skjnldsv** [comment]
I'll keep this one opened as this touches something slightly different in the code. Even if this is the same root issue. Thanks for the extended logs :)

**Comment by simitar** [comment]
I have the same issue over here. Is there already a solution for it? Thanks
