### ISSUE TITLE
Did the federated circles feature get removed?

### ISSUE THREAD

**Issue by chaptergy** [nextcloud/circles#511]
When reading the changelogs I noticed it saying
```
disabling federated circles in Admin UI
```
which sounds like the ability to disable federated circles for your instance. However when looking at the [commits](https://github.com/nextcloud/circles/commit/ffd9f497e259f9303058bdf3696bbea3fd150869) it seems more like federated circles are no longer supported at all? The settings from the admin UI were removed, however from the circles app nothing was removed.

**Comment by daita** [comment]
Hello,

The ability is still here, but will not be maintained anymore so I only removed the settings from the Admin UI.
As previously said, the concept is still here and the Circles App will help you connecting people from other clouds, however it will be fully rework and I hope to have something for NC21 or NC22.

I will also try as much as possible to not hurt the current state of the feature in the future version of the app.
