### ISSUE TITLE
App is not compliant. Can not add new members to the closed circle. Circles v0.19.9

### ISSUE THREAD

**Issue by git-test4** [nextcloud/circles#521]
Hello,
Have a problem with Circles. When owner of the circle invite users to the closed circle, users don't get invitation and don't have the option "Accept the invitation". Instead they have to join it themselves. After they do join it,  owner of the circle accepts request and it's shown that member is added , but when owner refreshes webpage he needs to accept request again and again. Button is triggered, but it does nothing.

**Server configuration:**

_Operating system_: Ubuntu 18.04.5 LTS
_Web server_: nginx/1.14.0
_Database_: Mysql 5.7.31
_PHP_: 7.3.23
_Nextcloud version_: 19.0.4

**sudo -u www-data php occ app:check-code circles**

Analysing /var/www/nextcloud/apps/circles/files/list.php
 2 errors
    line    3: OCP\User - Static method of deprecated class must not be called
    line    3: OCP\User::checkLoggedIn - Method of deprecated class must not be called
Analysing /var/www/nextcloud/apps/circles/lib/GlobalScale/AGlobalScaleEvent.php
 2 errors
    line  255: != - is discouraged
    line  256: != - is discouraged
App is not compliant

**Logs:**

[core] Error: TypeError: Argument 2 passed to OCA\Circles\Db\CirclesRequest::getCircle() must be of the type string, null given, called in /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php on line 271 at <<closure>>

0. /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php line 271
   OCA\Circles\Db\CirclesRequest->getCircle("11d47a920d7b4a", null, 1, "", true)
1. /var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php line 266
   OCA\Circles\Service\CirclesService->detailsCircle("11d47a920d7b4a", true)
2. /var/www/nextcloud/apps/deck/lib/Service/PermissionService.php line 266
   OCA\Circles\Api\v1\Circles::detailsCircle("11d47a920d7b4a", true)
3. /var/www/nextcloud/apps/deck/lib/Activity/ActivityManager.php line 447
   OCA\Deck\Service\PermissionService->findUsers("21")
4. /var/www/nextcloud/apps/deck/lib/Activity/ActivityManager.php line 262
   OCA\Deck\Activity\ActivityManager->sendToUsers(OC\Activity\Event {})
5. /var/www/nextcloud/apps/deck/lib/Cron/CardDescriptionActivity.php line 58
   OCA\Deck\Activity\ActivityManager->triggerEvent("deck_card", OCA\Deck\Db\Card {id: 46}, "card_update_description", {before: "",afte ... "}, "birgitta")
6. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 62
   OCA\Deck\Cron\CardDescriptionActivity->run(null)
7. /var/www/nextcloud/cron.php line 126
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

**Comment by daita** [comment]
Do you have the exact same error with the last version of the Circles app ?
Can you run `./occ circles:test` ?

**Comment by git-test4** [comment]
Sorry for the delayed response. New version of Circles app solved the problem. Thanks. I'll close this issue.
