### ISSUE TITLE
Exception: Call to undefined method daita\MySmallPhpTools\Model\Nextcloud\NC19Request::basedOnUrl()

### ISSUE THREAD

**Issue by piotr-sikora-v** [nextcloud/circles#524]
Circle produce errors
This is new empty instance based on docker latest version
Circles version: 0.20.4

full error:

`    /var/www/html/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Circles\ ... {}, "create")

    /var/www/html/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Circle ... r", "create", OC\AppFramew ... {}, { action: nu ... "})

    /var/www/html/lib/base.php - line 1009:

    OC\Route\Router->match("/apps/circles/v1/circles")

    /var/www/html/index.php - line 37:

    OC::handleRequest()

    Error: Call to undefined method daita\MySmallPhpTools\Model\Nextcloud\NC19Request::basedOnUrl()

    /var/www/html/custom_apps/circles/lib/Service/ConfigService.php - line 569:

    OCA\Circles\Service\ConfigService->configureRequestAddress(daita\MySmal ... {}, "circles.Glo ... t", { token: "b8 ... "})

    /var/www/html/custom_apps/circles/lib/Service/GlobalScaleService.php - line 142:

    OCA\Circles\Service\ConfigService->configureRequest(daita\MySmal ... {}, "circles.Glo ... t", { token: "b8 ... "})

    /var/www/html/custom_apps/circles/lib/Service/GSUpstreamService.php - line 146:

    OCA\Circles\Service\GlobalScaleService->asyncBroadcast(OCA\Circles\ ... {})

    /var/www/html/custom_apps/circles/lib/Service/CirclesService.php - line 221:

    OCA\Circles\Service\GSUpstreamService->newEvent(OCA\Circles\ ... {})

    /var/www/html/custom_apps/circles/lib/Controller/CirclesController.php - line 54:

    OCA\Circles\Service\CirclesService->createCircle(1, "test3")

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Circles\Controller\CirclesController->create("1", "test3")

    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Circles\ ... {}, "create")

    /var/www/html/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Circles\ ... {}, "create")

    /var/www/html/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Circle ... r", "create", OC\AppFramew ... {}, { action: nu ... "})

    /var/www/html/lib/base.php - line 1009:

    OC\Route\Router->match("/apps/circles/v1/circles")

    /var/www/html/index.php - line 37:

    OC::handleRequest()`

**Comment by noci2012** [comment]
indeed basedOnUrl() is missing from NC19Request

**Comment by Lanyaaki** [comment]
Me too

**Comment by TrafficJan82** [comment]
We're also getting this error when attempting to add members to a circle.

Steps to reproduce:

- Open any circle
- type part of a member's name
- select the member from the list

Observed behavior:
- Nothing happens, console shows that the `PUT` request to the backend has produced a 500 error. Logs show the error shown above

This essentially breaks the circles feature, as it is no longer possible to add members to a circle.

**Comment by CoreTechnologyAG** [comment]
We have the same problem:

Circle v0.20.6

- Create new circle and got error: "Circle {name} could not be created: no error message" 
![image](https://user-images.githubusercontent.com/7665561/100980625-cfc8f000-3545-11eb-99b2-8b5b5888abda.png)

  - Refresh the page. The created circle appears in the list.
- Delete the circle: "Cannot delete this circle: no error message"
  - Refresh the circle page: the circle is deleted.
![image](https://user-images.githubusercontent.com/7665561/100980873-35b57780-3546-11eb-83dc-6e3d4fe32499.png)

We also have installed the collectives-App [V0.2.2](https://gitlab.com/collectivecloud/collectives), which is tied to the circle app.

--- More Log information
**Create Circle
[index] Error: Exception: Call to undefined method daita\MySmallPhpTools\Model\Nextcloud\NC19Request::basedOnUrl() at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Circles\Cont ... {}, "create")
1. /var/www/html/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Circles\\C ... r", "create", OC\AppFramework\ ... {}, {action: null,_r ... "})
2. /var/www/html/lib/base.php line 1008
   OC\Route\Router->match("/apps/circles/v1/circles")
3. /var/www/html/index.php line 37
   OC::handleRequest()

PUT /apps/circles/v1/circles
from 10.0.0.2 by administrator at 2020-12-03T07:51:24+00:00

**Delete Circle
[index] Error: Exception: Call to undefined method daita\MySmallPhpTools\Model\Nextcloud\NC19Request::basedOnUrl() at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Circles\Cont ... {}, "destroy")
1. /var/www/html/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Circles\\C ... r", "destroy", OC\AppFramework\ ... {}, {action: null,un ... "})
2. /var/www/html/lib/base.php line 1008
   OC\Route\Router->match("/apps/circles/v1/circles/5d2f08360f77f8")
3. /var/www/html/index.php line 37
   OC::handleRequest()

DELETE /apps/circles/v1/circles/5d2f08360f77f8
from 10.0.0.2 by administrator at 2020-12-03T07:52:09+00:00

**Comment by daita** [comment]
upgrade the social app. and try to run:

`./occ circles:test`

if you still have issue, please send me the result of `./occ app:list`

**Comment by hcmuns** [comment]
The ./occ circles:test leaveas an error:

An unhandled exception has been thrown:
Error: Call to undefined method daita\MySmallPhpTools\Model\Request::type() in /var/www/html/custom_apps/circles/lib/Command/CirclesTest.php:187
Stack trace:
#0 /var/www/html/custom_apps/circles/lib/Command/CirclesTest.php(129): OCA\Circles\Command\CirclesTest->testRequest(Object(Symfony\Component\Console\Output\ConsoleOutput), 'GET', 'core.CSRFToken....')
#1 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Circles\Command\CirclesTest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(1000): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Circles\Command\CirclesTest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/console.php(100): OC\Console\Application->run()
#8 /var/www/html/occ(11): require_once('/var/www/html/c...')

**Comment by Lockorocko** [comment]
> upgrade the social app. and try to run:
> 
> `./occ circles:test`
> 
> if you still have issue, please send me the result of `./occ app:list`

Thx bro ... that worked for me :)

**Comment by Lanyaaki** [comment]
> upgrade the social app. and try to run:
> 
> `./occ circles:test`
> 
> if you still have issue, please send me the result of `./occ app:list`

IT WORK!!!

**Comment by hcmuns** [comment]
According to Nextcloud support this behavior is due to the combination of the app fulltextsearch/circles and will be resolved shortly. A test in another environment confirms that the issue is resolved after disabling fulltextsearch apps. So we wait patiently.

**Comment by daita** [comment]
Should be ok now!

**Comment by stwo-aix** [comment]
> Should be ok now!

In which version?

**Comment by it25fg** [comment]
Updated circles to 0.19.12 -- error "Call to undefined method daita\\MySmallPhpTools\\Model\\Nextcloud\\NC19Request::basedOnUrl()" did not go away. Is the fix included in this version (I did not find a changelog, is there one?)

**Comment by daita** [comment]
what is the result of `occ app:list` ?

**Comment by it25fg** [comment]
> what is the result of `occ app:list` ?

I should have thought before typing! There are three apps which include the 'vendor/daita/my-small-php-tools' libs but lack the NC19Request function:

files_fulltextsearch: 1.4.3
fulltextsearch: 1.4.2
fulltextsearch_elasticsearch: 1.5.2

**Comment by it25fg** [comment]
Just a followup: Deactivating the three mentioned apps cured the problem. But of course, this is not a solution, and there's not much motivation to update Nextcloud if the stream of new instabilities with new versions does not really decrease.
@daita Do you intend to fix these apps for NC 19 too?

**Comment by daita** [comment]
I will try to release a new version of those app as soon as possible

**Comment by daita** [comment]
Please upgrade your fulltextsearch's apps
