### ISSUE TITLE
Syntax error or access violation: 1055 Expression #9 of SELECT list is not in GROUP BY clause

### ISSUE THREAD

**Issue by himbeere** [nextcloud/circles#53]
Hi Devs.

Great idea the circles!

Right now i am not able to create a circle. Error messages:

{"reqId":"VSsAmL48M5GNd2wrO0BE","level":3,"time":"2017-05-02T14:27:19+00:00","remoteAddr":"151.","user":"hoppla","app":"index","metho
d":"GET","url":"\/index.php\/apps\/circles\/circles?type=all&name=&level=0","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT `c`.`id`, `c`.`name`, `c`.`description`, `c`.`type`, `c`.`creation`, `u`.`joined`, `u`.`level`, `u`.`status`, `o`.`user_id` AS `owner` FROM `oc_circles_circles` c LEFT JOIN `oc_circles_members` u ON (`c`.`id` = `u`.`circle_id`) AND (`u`.`user_id` = ?), `oc_circles_members` o WHERE (`c`.`id` = `o`.`circle_id`) AND (`o`.`level` = ?) AND (((`c`.`type` = ?) AND (`o`.`user_id` = ?)) OR ((`c`.`type` = ?) AND ((`u`.`level` >= ?) OR (`c`.`id` = ?) OR (`c`.`name` = ?))) OR (`c`.`type` = ?) OR (`c`.`type` = ?)) GROUP BY `c`.`id` ORDER BY `c`.`name` ASC' with params [\\\"hoppla\\\", 9, 1, \\\"hoppla\\\", 2, 1, -1, \\\"\\\", 4, 8]:\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #9 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'nextcloud.o.user_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `c`.`id`...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/lib\\\/private\\\/DB\\\/Connection.php(192): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `c`.`id`...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `c`.`id`...', Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(213): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/apps\\\/circles\\\/lib\\\/Db\\\/CirclesMapper.php(76): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/apps\\\/circles\\\/lib\\\/Service\\\/CirclesService.php(142): OCA\\\\Circles\\\\Db\\\\CirclesMapper->findCirclesByUser('hoppla', 15, '', 0)\\n#7 `\\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/apps\\\/circles\\\/lib\\\/Controller\\\/CirclesController.php(75):` OCA\\\\Circles\\\\Service\\\\CirclesService->listCircles(15, '', '0')\\n#8 [internal function]: OCA\\\\Circles\\\\Controller\\\\CirclesController->listing('all', '', '0')\\n#9 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Circles\\\\Controller\\\\CirclesController), 'listing')\\n#11 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Circles\\\\Controller\\\\CirclesController), 'listing')\\n#12 \\\/var\\\/www\\\/nextcloud.dev.hoppla.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('CirclesControll...', 'listing', Object(OC\\\\AppFramework\\\\Dependency

**Comment by daita** [comment]
This is fixed (#51), i'll update the version on the appstore later or tomorrow !

**Comment by daita** [comment]
new version is available on the appstore

**Comment by himbeere** [comment]
Well yes, creating now works. But select is broken too.

{"reqId":"1xsHLmNrhDJSJ32SZ17A","level":3,"time":"2017-05-03T06:20:10+00:00","remoteAddr":"151.","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/circles\/circles?type=hidden&name=&level=0","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT `c`.`id`, `c`.`name`, `c`.`description`, `c`.`type`, `c`.`creation`, `u`.`joined`, `u`.`level`, `u`.`status`, `o`.`user_id` AS `owner` FROM `oc_circles_circles` c LEFT JOIN `oc_circles_members` u ON (`c`.`id` = `u`.`circle_id`) AND (`u`.`user_id` = ?), `oc_circles_members` o WHERE (`c`.`id` = `o`.`circle_id`) AND (`o`.`level` = ?) AND ((`c`.`type` = ?) AND ((`u`.`level` >= ?) OR (`c`.`id` = ?) OR (`c`.`name` = ?))) GROUP BY `c`.`id` ORDER BY `c`.`name` ASC' with params [\\\"admin\\\", 9, 2, 1, -1, \\\"\\\"]:\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #9 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'nextcloud.o.user_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `c`.`id`...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/lib\\\/private\\\/DB\\\/Connection.php(192): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `c`.`id`...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `c`.`id`...', Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(213): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/apps\\\/circles\\\/lib\\\/Db\\\/CirclesMapper.php(76): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/apps\\\/circles\\\/lib\\\/Service\\\/CirclesService.php(142): OCA\\\\Circles\\\\Db\\\\CirclesMapper->findCirclesByUser('admin', 2, '', 0)\\n#7 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/apps\\\/circles\\\/lib\\\/Controller\\\/CirclesController.php(75): OCA\\\\Circles\\\\Service\\\\CirclesService->listCircles(2, '', '0')\\n#8 [internal function]: OCA\\\\Circles\\\\Controller\\\\CirclesController->listing('hidden', '', '0')\\n#9 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Circles\\\\Controller\\\\CirclesController), 'listing')\\n#11 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Circles\\\\Controller\\\\CirclesController), 'listing')\\n#12 \\\/var\\\/www\\\/nextcloud.dev.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('CirclesControll...', 'listing', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler:

**Comment by daita** [comment]
the last version of Circles was updated few hours ago, and not yesterday. Can you check with 0.9.4 ?

**Comment by himbeere** [comment]
0.9.4 works. Thanks.
