### ISSUE TITLE
Error add member

### ISSUE THREAD

**Issue by ThibautDavid-USMB** [nextcloud/circles#530]
Hello, 

I'm using circle version 0.20.4 on a nextcloud 20.0.2.

When I want to add members to a circle, the user seems to implement correctly but when I refresh the page it is no longer in the list of users

**Comment by daita** [comment]
please run this command: `./occ circles:test`

**Comment by ThibautDavid-USMB** [comment]
thanks, but I found the error, it came from the redirect to https which was done on nextcloud.

By not forcing the redirection, adding a member works again

**Comment by daita** [comment]
Yes, this was fixed in 0.20.6 ! you can keep the redirection and upgrade to last version of the app, it _should_ work :)
