### ISSUE TITLE
Cannot add a user

### ISSUE THREAD

**Issue by PGT29** [nextcloud/circles#538]
Hello all
DON-BOSCO Nextcloud 20.0.4
OS = Debian 10
Apache 2 + MariaDB
https with Self-signed certificate
Cercles (in French) v 0.20.6
I was able to create a privare Circle under  admin account
If I add a new user it take time then the new user is recorded but if I want to add a another one it repalce the former one and anyway after closing the session and reopen it all is vanished !
It must be untricky !
sudo -u www-data php /var/www/nextcloud/occ circles:test
- GET request on https://y.y.y.y/index.php/csrftoken: 302
If you can help !?
Thks in adavance and merry Xmas
PM

**Comment by silasroeber** [comment]
Same behavior hier with NC Version 20.0.5 and Circles Version 0.20.6 running PHP 7.3.19 if that could have anythink to do with it cause it seems to be an error in a php script.
If there is anythink we can provide or test to tackle this problem it would be a pleasure.

[circles] Error: daita\MySmallPhpTools\Exceptions\RequestNetworkException:  at <<closure>>

0. /home/akg-data/PUBLIC_HTML/apps/circles/lib/Service/GlobalScaleService.php line 146
   OCA\Circles\Service\GlobalScaleService->doRequest(daita\MySmallPhp ... {})
1. /home/akg-data/PUBLIC_HTML/apps/circles/lib/Service/GSUpstreamService.php line 145
   OCA\Circles\Service\GlobalScaleService->asyncBroadcast(OCA\Circles\Model\GlobalScale\GSEvent {})
2. /home/akg-data/PUBLIC_HTML/apps/circles/lib/Service/CirclesService.php line 394
   OCA\Circles\Service\GSUpstreamService->newEvent(OCA\Circles\Model\GlobalScale\GSEvent {})
3. /home/akg-data/PUBLIC_HTML/apps/circles/lib/Controller/CirclesController.php line 123
   OCA\Circles\Service\CirclesService->settingsCircle("2aecd7682a728c", {circle_name: "P ... "})
4. /home/akg-data/PUBLIC_HTML/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Circles\Controller\CirclesController->settings("2aecd7682a728c", {circle_name: "P ... "})
5. /home/akg-data/PUBLIC_HTML/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Circles\Cont ... {}, "settings")
6. /home/akg-data/PUBLIC_HTML/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Circles\Cont ... {}, "settings")
7. /home/akg-data/PUBLIC_HTML/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\Circles\\C ... r", "settings", OC\AppFramework\ ... {}, {uniqueId: "2aec ... "})
8. /home/akg-data/PUBLIC_HTML/lib/base.php line 1008
   OC\Route\Router->match("/apps/circles/v ... s")
9. /home/akg-data/PUBLIC_HTML/index.php line 37
   OC::handleRequest()

POST /apps/circles/v1/circles/2aecd7682a728c/settings
from 31.16.153.231 by silaroeber at 2021-01-24T13:15:18+00:00

**Comment by aleadco** [comment]
Hi, can this help
https://github.com/nextcloud/circles/issues/574#issuecomment-823750845

**Comment by joshtrichards** [comment]
This was a very long time ago. I'm cleaning up some old issues. Are you still experiencing this?

Hopefully you found help elsewhere, in the mean time, such as through the community help forum - https://help.nextcloud.com.

**Comment by silasroeber** [comment]
I think this Was fixed a lot of Updates ago 😉

Am 14. Juni 2024 15:44:48 MESZ schrieb Josh ***@***.***>:
>This was a very long time ago. I'm cleaning up some old issues. Are you still experiencing this?
>
>Hopefully you found help elsewhere, in the mean time, such as through the community help forum - https://help.nextcloud.com.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/circles/issues/538#issuecomment-2168087085
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Silas Röber
