### ISSUE TITLE
NC12 internal server error after installing Circles

### ISSUE THREAD

**Issue by dan-nkl** [nextcloud/circles#54]
Hey guys,
got Nextcloud 12 beta 1 on my apache server with php 7.0.xx and the install of circles crashed my instance :/

![image](https://cloud.githubusercontent.com/assets/26377301/25658794/f720baec-3004-11e7-8bf7-0e09f9cbeacf.png)

and after that my Nextcloud is not accessible anymore

![image](https://cloud.githubusercontent.com/assets/26377301/25658813/0fc955b8-3005-11e7-95e3-3038f26f1df6.png)

The serverlog entry: https://paste.tech-port.de/?4c1e2079b696fd00#pr4y7wsnFR3sF61dvKFpMfay0FGwFMnxTIaHGkSvVbg=

I can't help myself with the given error and hope that you have some ideas for fixing the instance

**Comment by dan-nkl** [comment]
After deactivating circles in the mysql database, the instance is reachable again
![image](https://cloud.githubusercontent.com/assets/26377301/25660245/a764193e-300b-11e7-9d7e-166d2bd2fe16.png)

**Comment by daita** [comment]
Thanks for your report, should be fixed in 0.9.5
