### ISSUE TITLE
Circle test failed  Call to undefined method daita\MySmallPhpTools\Model\Request::type()

### ISSUE THREAD

**Issue by christiansicari** [nextcloud/circles#540]
Environment:
Nextcloud v:  19.0.4
Circle v: 	0.19.11
System: Debian 9
Runtime environment: Docker version 19.03.5, build 633a0ea838
Docker image: nextcloud:19.0.4 
I did the test because I noticed some bugs:
1. Error message on create a new circle with the text: `	Circle '{name}' could not be created: no error message`, pay attention that `{name}` is returned by the system, it seems it is not able to get the name of the circle. In any case freshing the page the circle appears.
2. I am not able to add user, clicking on plus button I select a user but nothing happens.

I carried on the test using occ and I got this result:

> www-data@758335caadb4:~/html$ ./occ circles:test
An unhandled exception has been thrown:
Error: Call to undefined method daita\MySmallPhpTools\Model\Request::type() in /var/www/html/custom_apps/circles/lib/Command/CirclesTest.php:187
Stack trace:
#0 /var/www/html/custom_apps/circles/lib/Command/CirclesTest.php(129): OCA\Circles\Command\CirclesTest->testRequest(Object(Symfony\Component\Console\Output\ConsoleOutput), 'GET', 'core.CSRFToken....')
#1 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Circles\Command\CirclesTest->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Circles\Command\CirclesTest), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/console.php(100): OC\Console\Application->run()
#8 /var/www/html/occ(11): require_once('/var/www/html/c...')

**Comment by daita** [comment]
can you paste the result of `./occ app:list` ?

**Comment by christiansicari** [comment]
@daita  Yes, sure.
I'am sorry I do not know how to format well the output
`root@758335caadb4:/var/www/html# su www-data -s /bin/bash 
www-data@758335caadb4:~/html$ ./occ app:list`

> Enabled:
>   - accessibility: 1.5.0
>   - activity: 2.12.1
>   - admin_audit: 1.9.0
>   - announcementcenter: 3.8.1
>   - appointments: 1.7.15
>   - apporder: 0.11.0
>   - breezedark: 19.0.9
>   - calendar: 2.0.4
>   - carnet: 0.23.7
>   - circles: 0.19.11
>   - cloud_federation_api: 1.2.0
>   - comments: 1.9.0
>   - contacts: 3.4.2
>   - contactsinteraction: 1.0.0
>   - dav: 1.15.0
>   - deck: 1.2.2
>   - external: 3.6.0
>   - extract: 1.2.5
>   - federatedfilesharing: 1.9.0
>   - federation: 1.9.0
>   - files: 1.14.0
>   - files_external: 1.10.0
>   - files_external_dropbox: 1.4.3
>   - files_fulltextsearch: 1.4.3
>   - files_fulltextsearch_tesseract: 1.4.2
>   - files_linkeditor: 1.1.3
>   - files_markdown: 2.3.1
>   - files_pdfviewer: 1.8.0
>   - files_rightclick: 0.16.0
>   - files_sharing: 1.11.0
>   - files_trashbin: 1.9.0
>   - files_versions: 1.12.0
>   - files_videoplayer: 1.8.0
>   - firstrunwizard: 2.8.0
>   - forms: 2.0.4
>   - fulltextsearch: 1.4.2
>   - fulltextsearch_elasticsearch: 1.5.2
>   - guests: 1.6.2
>   - impersonate: 1.6.1
>   - logreader: 2.4.0
>   - lookup_server_connector: 1.7.0
>   - mail: 1.4.2
>   - music: 0.17.3
>   - notes: 3.6.4
>   - notifications: 2.7.0
>   - oauth2: 1.7.0
>   - onlyoffice: 6.2.0
>   - password_policy: 1.9.1
>   - passwords: 2020.12.0
>   - phonetrack: 0.6.4
>   - photos: 1.1.0
>   - polls: 1.6.2
>   - privacy: 1.3.0
>   - provisioning_api: 1.9.0
>   - recommendations: 0.7.0
>   - serverinfo: 1.9.0
>   - settings: 1.1.0
>   - sharebymail: 1.9.0
>   - sharepoint: 1.7.0
>   - side_menu: 1.21.0
>   - spreed: 9.0.7
>   - support: 1.2.1
>   - survey_client: 1.7.0
>   - systemtags: 1.9.0
>   - talk_simple_poll: 1.2.0
>   - tasks: 0.13.6
>   - text: 3.0.1
>   - theming: 1.10.0
>   - twofactor_backupcodes: 1.8.0
>   - updatenotification: 1.9.0
>   - viewer: 1.3.0
>   - whiteboard: 0.0.3
>   - workflow_pdf_converter: 1.4.0
>   - workflow_script: 1.4.0
>   - workflowengine: 2.1.0
> Disabled:
>   - encryption
>   - files_accesscontrol
>   - groupfolders
>   - nextcloud_announcements
>   - ocr
>   - user_ldap

**Comment by stwo-aix** [comment]
Not a fix, but a workaround: disable all "fulltextsearch" apps. 
See: https://github.com/nextcloud/circles/issues/524

**Comment by christiansicari** [comment]
@stwo-aix  Thank you, I did not see the topic.
Unfortunately, my team massive uses fulltextsearch apps, I cannot disable them... to be honest  we use also circle.
Wait for fix.
