### ISSUE TITLE
Add circle in circle

### ISSUE THREAD

**Issue by tcoupin** [nextcloud/circles#556]
It would be great to be able to add a circle in circle. Not users from a circle to an other but the circle itself.

**Comment by azul** [comment]
Can you elaborate why you would want this? 
Can you give an example of what the circles would be?

One problem with this approach is that it allows building complex structures of circles.
So what would happen if you add circle A to circle B and circle B to circle A?
You'd basically create an infinite loop which is quite hard to deal with in a consistent way that does not break things.

**Comment by daita** [comment]
This will be available in [NC22](https://github.com/nextcloud/circles/pull/551)

And nothing would happens if you loop circle together.
