### ISSUE TITLE
Missing primary keys for DB clusters

### ISSUE THREAD

**Issue by rullzer** [nextcloud/circles#559]
The table `oc_circle_gsevents` is missing a primary key.
Some DB setups **require** each table to have a primary key

**Comment by acsfer** [comment]
Duplicate of https://github.com/nextcloud/circles/issues/534

**Comment by acsfer** [comment]
`oc_circles_event` is also missing a PK

**Comment by ArtificialOwl** [comment]
this is fixed in next release

**Comment by solracsf** [comment]
Hi @ArtificialOwl in my setup (v22.2.7) these are missing a PK:

```
oc_circles_event
oc_circle_gsevents
```

what release do you mean?
