### ISSUE TITLE
Unable to add users manually

### ISSUE THREAD

**Issue by aleadco** [nextcloud/circles#574]
The only way to use this tool is to create public access circles.
If you create a private, secret or closed circle, you cannot add anyone manually.
If someone requests to join a circle, a persistent notification arrives and despite approving the access, it is not added and the request comes out again.

**You get three error logs for each exception**

### daita\MySmallPhpTools\Exceptions\RequestNetworkException:

`{"reqId":"Rl9OClAP40jjS5dovHl7","level":3,"time":"2021-04-16T19:14:59-04:00","remoteAddr":"152.207.146.86","user":"alejandrod","app":"circles","method":"GET","url":"/apps/circles/v1/circles/c82cd6dff28a50/leave","message":{"Exception":"daita\\MySmallPhpTools\\Exceptions\\RequestNetworkException","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/circles/lib/Service/GlobalScaleService.php","line":146,"function":"doRequest","class":"OCA\\Circles\\Service\\GlobalScaleService","type":"->"},{"file":"/var/www/nextcloud/apps/circles/lib/Service/GSUpstreamService.php","line":145,"function":"asyncBroadcast","class":"OCA\\Circles\\Service\\GlobalScaleService","type":"->"},{"file":"/var/www/nextcloud/apps/circles/lib/Service/CirclesService.php","line":454,"function":"newEvent","class":"OCA\\Circles\\Service\\GSUpstreamService","type":"->"},{"file":"/var/www/nextcloud/apps/circles/lib/Controller/CirclesController.php","line":167,"function":"leaveCircle","class":"OCA\\Circles\\Service\\CirclesService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"leave","class":"OCA\\Circles\\Controller\\CirclesController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/circles/vendor/daita/my-small-php-tools/lib/Traits/Nextcloud/TNC19Request.php","Line":124,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36","version":"21.0.1.1","id":"607a1a73cb09a"}`

```
[no app in context] Error: issue while useClient(): GuzzleHttp\Exception\ClientException; Client error: `POST http://my.domain.com/apps/circles/v1/gs/broadcast/async/aef77633-26e8-4aea-beb0-acefc41929ec/` resulted in a `403 Forbidden` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copy (truncated...)
; 0

GET /apps/circles/v1/circles/c82cd6dff28a50/leave
from 152.207.146.86 by alejandrod at 2021-04-16T19:14:59-04:00
```
```
[no app in context] Error: issue while useClient(): GuzzleHttp\Exception\RequestException; cURL error 56: Received HTTP code 403 from proxy after CONNECT (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.domain.com/apps/circles/v1/gs/broadcast/async/aef77633-26e8-4aea-beb0-acefc41929ec/; 0

GET /apps/circles/v1/circles/c82cd6dff28a50/leave
from 152.207.146.86 by alejandrod at 2021-04-16T19:14:59-04:00
```

**Comment by aleadco** [comment]
I found the solution to the problem.
Basically everything is summarized to which circle the DNS itself must resolve. In my case, I use the `proxy` parameter in config.php to connect the service to the internet. The solution was to add `proxyexclude` and specify the same domain and other local resources on the network.

**Comment by dev-zero** [comment]
@aleadco thanks for the solution, but this only applies if the server itself needs to use a proxy to get an internet connect, correct?
E.g. if my `proxy` parameter is empty but I see the same (or very similar) error, it likely is a different problem?
