### ISSUE TITLE
no federated sharing and public link of circles

### ISSUE THREAD

**Issue by weinic** [nextcloud/circles#575]
Hello,

i have the following two Problems:

for the first, i can´t create federated sharing. 
See the following Picture: 

![Screenshot 2021-04-17 180519](https://user-images.githubusercontent.com/57099502/115119344-2ccebb00-9fa8-11eb-91d1-5069c15057ee.png)

for the second, can´t create a public link:

![Screenshot 2021-04-17 180828](https://user-images.githubusercontent.com/57099502/115119380-61427700-9fa8-11eb-8ac1-c07c83d8ac38.png)

On the Picture by apps.nextcloud.com i can see the link Symbol.
[https://raw.githubusercontent.com/nextcloud/circles/master/screenshots/0.12.0.png](url)

How can i do here

**Comment by top-logic** [comment]
Same issue here. NC 21, Circles 0.21.0.

**Comment by daita** [comment]
Federated Sharing is not available anymore and will be replaced by Federated Circles in NC23 (should be available in Alpha in NC22)

Regards,

Maxence

**Comment by weinic** [comment]
Ohh schade,

Danke für den Hinweis.

Dann muss man wenigstens nicht ewig nach einem Fehler suchen. 🤪

Aber es wäre gut / schön, wenn sich der Hinweis auch irgendwo in der App oder im Admin bereich finden würde, dann würden sich andere User nicht mit Fehlersuche plagen müssen.

Gruß Weinic
