### ISSUE TITLE
Circles 0.21.1 with NC 21.0.1 and Calendar 2.2.0 Results in Calendar App Broken

### ISSUE THREAD

**Issue by armouredking** [nextcloud/circles#576]
Like the title says. I upgraded to version 0.21.1 today for the Circles app. I have NC 21.0.1 and Calendar 2.2.0. This results in the calendar being inaccessible from the browser. I cannot see events in the dashboard, and clicking on the calendar results in spinning wheel that never resolves. NextCloud throws errors on every refresh attempt. I could see the calendar still from the Windows app (configured to view NC), but I'm unsure what caching (if any) the Windows app uses.

Downgrading the Circles app to version 0.21.0 corrects this problem.

This should be a cleaned error log from one of the refresh events:
[err.txt](https://github.com/nextcloud/circles/files/6381112/err.txt)

**Comment by alx-tuilmenau** [comment]
Same problem on 0.20.8 with Calendar 2.2.0.

It looks like it is caused by #566 .

<details>
<summary>My log</summary>
[webdav] Fatal: Error: Call to a member function isLevel() on null at <<closure>>

 0. /data/nextcloud_20/apps/circles/lib/Api/v1/Circles.php line 265
    OCA\Circles\Service\CirclesService->detailsCircle("15a68471a4250b", true)
 1. /data/nextcloud_20/apps/dav/lib/Connector/Sabre/Principal.php line 495
    OCA\Circles\Api\v1\Circles::detailsCircle("15a68471a4250b", true)
 2. /data/nextcloud_20/apps/dav/lib/Connector/Sabre/Principal.php line 186
    OCA\DAV\Connector\Sabre\Principal->circleToPrincipal("15a68471a4250b")
 3. /data/nextcloud_20/apps/dav/lib/DAV/Sharing/Backend.php line 202
    OCA\DAV\Connector\Sabre\Principal->getPrincipalByPath("principals/circles/15a68471a4250b")
 4. /data/nextcloud_20/apps/dav/lib/DAV/Sharing/Backend.php line 224
    OCA\DAV\DAV\Sharing\Backend->getShares("720")
 5. /data/nextcloud_20/apps/dav/lib/CalDAV/CalDavBackend.php line 2589
    OCA\DAV\DAV\Sharing\Backend->applyShareAcl("720", [{privilege: "{D ... "])
 6. /data/nextcloud_20/apps/dav/lib/CalDAV/Calendar.php line 221
    OCA\DAV\CalDAV\CalDavBackend->applyShareAcl("720", [{privilege: "{D ... "])
 7. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAVACL/Plugin.php line 576
    OCA\DAV\CalDAV\Calendar->getACL()
 8. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAVACL/Plugin.php line 606
    Sabre\DAVACL\Plugin->getAcl(OCA\DAV\CalDAV\Calendar {})
 9. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAVACL/Plugin.php line 199
    Sabre\DAVACL\Plugin->getCurrentUserPrivilegeSet(OCA\DAV\CalDAV\Calendar {})
10. /data/nextcloud_20/apps/dav/lib/Connector/Sabre/DavAclPlugin.php line 53
    Sabre\DAVACL\Plugin->checkPrivileges("calendars/user1 ... 6", ["{DAV:}read"], 1, false)
11. /data/nextcloud_20/apps/dav/lib/Connector/Sabre/DavAclPlugin.php line 83
    OCA\DAV\Connector\Sabre\DavAclPlugin->checkPrivileges("calendars/user1 ... 6", "{DAV:}read", 1, false)
12. /data/nextcloud_20/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Connector\Sabre\DavAclPlugin->propFind(Sabre\DAV\PropFind {}, OCA\DAV\CalDAV\Calendar {})
13. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAV/Server.php line 1066
    Sabre\DAV\Server->emit("propFind", [Sabre\DAV\PropF ... }])
14. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAV/Server.php line 992
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\DAV\CalDAV\Calendar {})
15. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAV/Server.php line 1681
    Sabre\DAV\Server->getPropertiesIteratorForPath("calendars/user1", ["{DAV:}current- ... "], 1)
16. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAV/Server.php line 1664
    Sabre\DAV\Server->writeMultiStatus(Sabre\Xml\Writer ... ]}, Generator {}, true)
17. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 363
    Sabre\DAV\Server->generateMultiStatus(Generator {}, true)
18. /data/nextcloud_20/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
19. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
20. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
21. /data/nextcloud_20/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
22. /data/nextcloud_20/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
23. /data/nextcloud_20/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
24. /data/nextcloud_20/remote.php line 167
    require_once("/data/nextcloud ... p")

PROPFIND /remote.php/dav/calendars/user1/
from 10.0.0.1 by user1 at 2021-04-27T01:58:25+00:00
</details>

**Comment by osm-frasch** [comment]
> Like the title says. I upgraded to version 0.21.1 today for the Circles app. I have NC 21.0.1 and Calendar 2.2.0. This results in the calendar being inaccessible from the browser. I cannot see events in the dashboard, and clicking on the calendar results in spinning wheel that never resolves. NextCloud throws errors on every refresh attempt. I could see the calendar still from the Windows app (configured to view NC), but I'm unsure what caching (if any) the Windows app uses.
> 
> Downgrading the Circles app to version 0.21.0 corrects this problem.
> 
> This should be a cleaned error log from one of the refresh events:
> [err.txt](https://github.com/nextcloud/circles/files/6381112/err.txt)

I have the same issue here. Calendar being inaccessible from the browser.

**Comment by osm-frasch** [comment]
In our complete education centre, calendars shared via circles are no longer accessible. For example, when I subscribe to a new circle that is accessed with a calendar, all the calendars in the left bar of the Calendar app disappear.

I have created a new calendar and tried to add a circle. This is also not possible. 
This problem only occurred with the update of the calendar app on 26.04. The last version still worked

Calendar Version 2.2.0 
PhP: Version: 7.3.16
Nextcloud: 21.0.1

**Comment by fnetX** [comment]
We've run into such an issue on Nextcloud 20.0.9, but we weren't able to roll back to the previous versions from our backup. The error is gone, but the calendar remains broken :disappointed:

Is there any further debug information we can provide?

**Comment by ksteinb** [comment]
I see the following error in the logs:

"message":{"Exception":"Error","Message":"Call to a member function isLevel() on null","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/circles/lib/Api/v1/Circles.php","line":265,"function":"detailsCircle","class":"OCA\\Circles\\Service\\CirclesService","type":"->","args":["5bce3e1924614f",true]},{"file":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Principal.php","line":495,"function":"detailsCircle","class":"OCA\\Circles\\Api\\v1\\Circles","type":"::","args":["5bce3e1924614f",true]},{"file":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Principal.php","line":186,"function":"circleToPrincipal","class":"OCA\\DAV\\Connector\\Sabre\\Principal","type":"->","args":["5bce3e1924614f"]},{"file":"/var/www/html/nextcloud/apps/dav/lib/DAV/Sharing/Backend.php","line":202,"function":"getPrincipalByPath","class":"OCA\\DAV\\Connector\\Sabre\\Principal",

**Comment by m4us1ne** [comment]
also affects 0.20.8

**Comment by fenvarien** [comment]
All calendars of my school, class-calendars and administration-calendars, are not accessible anymore. Is downgrading the app working reliable or are there database issues to expect?

**Comment by osm-frasch** [comment]
I would wait until hopefully a quick bug fix comes. Sometimes the fix comes after a few days. We are in the same situation here

**Comment by fenvarien** [comment]
> I would wait until hopefully a quick bug fix comes. Sometimes the fix comes after a few days. We are in the same situation here

Reverting this change on my production server did the trick: https://github.com/nextcloud/circles/pull/566/files
All calendars are accessible again. :)

**Comment by RaceX58** [comment]
Hi,

We also have an issue with Circle 0.20.8 and Deck 1.2.7

[https://github.com/nextcloud/deck/issues/3024]

Network console Response :

`{"status":500,"message":"Call to a member function isLevel() on null","exception":{"\u0000*\u0000message":"Call to a member function isLevel() on null","\u0000Exception\u0000string":"","\u0000*\u0000code":0,"\u0000*\u0000file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","\u0000*\u0000line":110,"\u0000Exception\u0000trace":[{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"-\u003E","args":[{},"index"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\BoardController","index",{},{"_route":"deck.board.index"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"-\u003E","args":["\/apps\/deck\/boards"]},{"file":"\/var\/www\/html\/nextcloud\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"\u0000Exception\u0000previous":{}}}`

Both issues looks related to Circles.

**Comment by ksteinb** [comment]
> > I would wait until hopefully a quick bug fix comes. Sometimes the fix comes after a few days. We are in the same situation here
> 
> Reverting this change on my production server did the trick: https://github.com/nextcloud/circles/pull/566/files
> All calendars are accessible again. :)

Yes this did it for me also

**Comment by RaceX58** [comment]
> > > I would wait until hopefully a quick bug fix comes. Sometimes the fix comes after a few days. We are in the same situation here
> > 
> > 
> > Reverting this change on my production server did the trick: https://github.com/nextcloud/circles/pull/566/files
> > All calendars are accessible again. :)
> 
> Yes this did it for me also

Same for me and the Deck app !

**Comment by luckyhandler** [comment]
@armouredking how can I downgrade the app again?

**Comment by fnetX** [comment]
> how can I downgrade the app again?

You will have to install an older version + update the database with something like ``UPDATE `oc_appconfig` SET `configvalue` = '0.20.7' WHERE `appid` = 'circles' AND `configkey` = 'installed_version'``. If the database config does not match the app version, it'll automatically upgrade to the configured version. (You could also check if damaging the app installation + updating the app version in database does a proper downgrade, but I would not want to rely on this)

Make sure to only do a minimal downgrade + ideally put the site into maintenance mode during the operation to avoid anyone automatically upgrading the app to the version in appconfig table again. Also, use this at your own risk and maybe test in an isolated environment first to become familiar with the procedure. You should also check if there have been any database migrations (there is an oc_migrations table with app and timestamp). This probably depends on which version you used before updating the app.

I hope this helps, I recommend waiting a while if someone objects to my description, I might be mistaken on some points.

**Comment by osm-frasch** [comment]
Excuse me, even though this does not belong in a bug report, I would like to express my displeasure here. I don't understand why such bugs are fixed as quickly as possible and an app update is published. Such bugs, as well as the Fido2 bug, cause massive disappointment in corporate environments, as complete workflows are paralysed.

**Comment by kiilo** [comment]
> Excuse me, even though this does not belong in a bug report, I would like to express my displeasure here. I don't understand why such bugs are fixed as quickly as possible and an app update is published. Such bugs, as well as the Fido2 bug, cause massive disappointment in corporate environments, as complete workflows are paralysed. In general, I suspect that the development speed in Nextcloud is now simply too high and the developers no longer find the time to correct the bugs quickly enough.

As much as i could agree with you here - the tip @fenvarien gave https://github.com/nextcloud/circles/issues/576#issuecomment-828322516 solved the issue. But its not for the fainthearted.

Best

**Comment by daita** [comment]
> Excuse me, even though this does not belong in a bug report, I would like to express my displeasure here. I don't understand why such bugs are fixed as quickly as possible and an app update is published. Such bugs, as well as the Fido2 bug, cause massive disappointment in corporate environments, as complete workflows are paralysed. In general, I suspect that the development speed in Nextcloud is now simply too high and the developers no longer find the time to correct the bugs quickly enough.

In a more positive note, I would like to thank people from the community that takes time to help in any way: pull request, documentation, answers on report, pinpointing issue, quick hack, ...

**Comment by daita** [comment]
Anyone willing to test https://github.com/nextcloud/circles/pull/577 ?

**Comment by armouredking** [comment]
I tested #577 and it did not change anything. Impact remains the same; calendars are inaccessible. I have left the version at 0.21.1 and performed the reversion first pointed out by @fenvarien instead of downgrading to 0.21.0 again.

**Comment by luckyhandler** [comment]
Did the workaround by @fenvarien and it also worked in my side

**Comment by devz3r0** [comment]
I needed to revert the https://github.com/nextcloud/circles/pull/566/files too, after that it's working again with Deck

**Comment by armouredking** [comment]
#577 does not fix, even with adjustments from second commit.

Process followed:

Uninstall Circles. Download and install version 0.21.1 (to ensure all files returned to unmodified state).
Make modifications as follows:
```
	/**
	 * returns details on circle and its members if this->userId is a member itself.
	 *
	 * @param string $circleUniqueId
	 * @param bool $forceAll
	 *
	 * @return Circle
	 * @throws Exception
	 */
	public function detailsCircle($circleUniqueId, $forceAll = false) {

		try {
			if (!$forceAll) {
				$circle = $this->circlesRequest->getCircle(
					$circleUniqueId, $this->userId, Member::TYPE_USER, '', $forceAll
				);
			} else {
				$circle = $this->circlesRequest->getCircleFromUniqueId($circleUniqueId);
			}
			if ($forceAll === true || $this->viewerIsAdmin()
				|| $circle->getHigherViewer()
						  ->isLevel(Member::LEVEL_MEMBER)
			) {
				$this->detailsCircleMembers($circle, $forceAll);
				$this->detailsCircleLinkedGroups($circle);
				$this->detailsCircleFederatedCircles($circle);
			}
		} catch (Exception $e) {
			throw $e;
		}

		return $circle;
	}


	/**
	 * get the Members list and add the result to the Circle.
	 *
	 * @param Circle $circle
	 *
	 * @throws Exception
	 */
	private function detailsCircleMembers(Circle $circle, $forceAll = false) {
		if ($forceAll || $this->viewerIsAdmin()) {
			$members = $this->membersRequest->forceGetMembers($circle->getUniqueId(), 0);
		} else {
			$members = $this->membersRequest->getMembers(
				$circle->getUniqueId(), $circle->getHigherViewer()
			);
		}

		$circle->setMembers($members);
	}
```
Load Calendar in Browser. No calendars work. Log shows:
```
TypeError: Argument 2 passed to OCA\Circles\Db\MembersRequest::getGroupsFromCircle() must be an instance of OCA\Circles\Model\Member, null given, called in /var/www/nextcloud/apps/circles/lib/Service/CirclesService.php on line 332
```

Rolling back #566 again to get calendar functionality.

**Comment by osm-frasch** [comment]
Nothing has changed in this situation so far: https://github.com/nextcloud/circles/issues/576#issuecomment-827546304

**Comment by osm-frasch** [comment]
> Nothing has changed in this situation so far: [#576 (comment)](https://github.com/nextcloud/circles/issues/576#issuecomment-827546304)
Is there any progress on this or do the developers still need more feedback on this?

**Comment by daita** [comment]
@osm-frasch did you try #581 ?

**Comment by osm-frasch** [comment]
> @osm-frasch did you try #581 ?
No we do not host ourselves. I only have a productive environment here with 200 users and can't try anything other than reporting.

**Comment by Steg1971** [comment]
Good day!
For four days there has been a problem with Deck about when Circles is installed.
All boards are visible, but cannot be opened.
Nextcloud log file shows error message:

Error | deck | Error: Call to a member function isLevel() on null
1.	/var/www/nextcloud/apps/circles/lib/Api/v1/Circles.php - line 265: 
OCA\Circles\Service\CirclesService->detailsCircle()
2.	/var/www/nextcloud/apps/deck/lib/Db/BoardMapper.php - line 270: 
OCA\Circles\Api\v1\Circles::detailsCircle()
3.	/var/www/nextcloud/apps/deck/lib/Db/RelationalEntity.php - line 117: 
OCA\Deck\Db\BoardMapper->OCA\Deck\Db\{closure}("*** sensiti ... *")
4.	/var/www/nextcloud/apps/deck/lib/Db/BoardMapper.php - line 281: 
OCA\Deck\Db\RelationalEntity->resolveRelation()
5.	/var/www/nextcloud/apps/deck/lib/Service/BoardService.php - line 183: 
OCA\Deck\Db\BoardMapper->mapAcl()
6.	/var/www/nextcloud/apps/deck/lib/Controller/BoardController.php - line 57: 
OCA\Deck\Service\BoardService->find()
7.	/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: 
OCA\Deck\Controller\BoardController->read()
8.	/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: 
OC\AppFramework\Http\Dispatcher->executeController()
9.	/var/www/nextcloud/lib/private/AppFramework/App.php - line 157: 
OC\AppFramework\Http\Dispatcher->dispatch()
10.	/var/www/nextcloud/lib/private/Route/Router.php - line 302: 
OC\AppFramework\App::main()
11.	/var/www/nextcloud/lib/base.php - line 993: 
OC\Route\Router->match()
12.	/var/www/nextcloud/index.php - line 37: 
OC::handleRequest()

Thank you in advance for solving this problem.

**Comment by ndurchx** [comment]
> 
> 
> @osm-frasch did you try #581 ?

With these changes, calendar and deck are working for me again

**Comment by daita** [comment]
please upgrade to last version of Circles and create a new ticket including server logs if you still have issues!

**Comment by osm-frasch** [comment]
Circles Version 0.21.2 solves the issue with NC21.1 and broken calender. Many thanks!!
