### ISSUE TITLE
Make Circles compatible with Spreed/Calendar and Contacts

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/circles#58]
...would be nice, if it would be possible to use circles for video calls and calendar/contacts sharing 😉 

@daita

**Comment by daita** [comment]
Contacts and circles will merge in a (near ?) future.

**Comment by marxistvegan** [comment]
@daita Is that true?

**Comment by daita** [comment]
If we find a way to nicely integrate Circles in the Contacts App, yes. The idea is to not spread too much the user/friend management (between the group, the contacts and the circle apps)

**Comment by daita** [comment]
Circles 0.13.0 is now compatible with Contacts in the way that you can add contacts to a Circle

**Comment by oparoz** [comment]
Awesome :)

**Comment by Loki3000** [comment]
Is it possible to share contacts in a circle?

**Comment by tomas-chrastina** [comment]
Good to know you guys/gals are working on this. Thank you.
It would be really helpful to have option to share Calendar to Circle.

**Comment by ying-sun** [comment]
agree with @tomas-chrastina 100%.

**Comment by duub** [comment]
> Circles 0.13.0 is now compatible with Contacts in the way that you can add contacts to a Circle

not shure what does this means... Is it possible to share users contacts with a circle?

**Comment by llttugraz** [comment]
Hello,
any news on the progress of this?
Thanks!

**Comment by sunjam** [comment]
[Calendar sharing to Circles](https://github.com/nextcloud/calendar/pull/602) has just been added.  Looks like it will appear in Nextcloud 16!  Sweet.
[Nextcloud Talk/Spreed support for Circles](https://github.com/nextcloud/spreed/issues/860) is still a feature request.
As an a cool side note, [Deck app also now supports sharing to the Circles app](https://github.com/nextcloud/deck/pull/923) as of yesterday.

**Comment by nickvergessen** [comment]
Talk 8 has this, so it seems all from the list are done.
