### ISSUE TITLE
Difference between personal, hidden, and private circles?

### ISSUE THREAD

**Issue by tflidd** [nextcloud/circles#59]
I just installed NC 12 and enabled the circles app. Without digging into the documentation it is not clear:

- What is the difference between the types of circles (there is only an explanation for personal circles)?
- How do I create a circle other than personal?
![screenshot from 2017-05-08 23-39-39](https://cloud.githubusercontent.com/assets/8111200/25826752/45d3870e-3448-11e7-8667-49f91e0c1e7c.png)
Both buttons ("create personal circle" and "creation") create a personal circle. If I click on "hidden circles" first, this doesn't create a hidden circle when I'm clicking the "creation" button after.

Do I need other apps to be enabled to make this work properly?
Enabled:
 - activity: 2.5.1
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - calendar: 1.5.2
 - circles: 0.9.5
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.1.4
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.3
 - files_automatedtagging: 1.2.2
 - files_external: 1.3.0
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.0.2
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - news: 11.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.0
 - twofactor_totp: 1.3.0
 - twofactor_u2f: 1.2.0
 - updatenotification: 1.2.0
 - user_external: 0.4
 - workflowengine: 1.2.0

**Comment by daita** [comment]
This is an interesting report !

The _Create a hidden circle_ is a droplist, you should be able to choose your type of circle here. I will have a look make it more obvious :]

**Comment by tflidd** [comment]
That's a droplist, I wouldn't have guessed that. You could use a box like for the language selection on your personal page.

I even got the explanations for the other circle types. However, the differences are still not clear. Public is just public, everybody can see and join the circle. All the others are not public, so you can't easily join. 

Perhaps you could use some sort of pictogram to visualize the permissions (myself, people within the circle, people outside) and a color code for functions (green = full access, blue = read only, ...), a small plus if they can add users, ...

**Comment by daita** [comment]
fixed in next major release
