### ISSUE TITLE
As an admin, I can not promote other member to admin level

### ISSUE THREAD

**Issue by tcoupin** [nextcloud/circles#596]
With NC 17 and 21, admin members of a circle can not change level of other members to admin, only to moderator.

Bug or feature ?

**Comment by skjnldsv** [comment]
Feature. But I agree, this should most likely be available.

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yup, agree from a user perspective there's no reason this should not be possible. :)

**Comment by skjnldsv** [comment]
@daita

**Comment by daita** [comment]
from an owner perspective, there is no reason this should be possible. :]

**Comment by daita** [comment]
This is not a bug or a feature, this is how the Circles App is designed. You cannot promote/revoke rights at the same level than you.
