### ISSUE TITLE
General error: 1 index ifilci already exists

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/circles#599]
* install 22.0.0 beta 1
* install and enabled the circles app from the appstore (it's 22.0.0-alpha3 IIRC)
* change to beta channel to get the 22.0.0 beta 2 update (that ships circles)
* upgrade
* actual: `An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 index ifilci already exists`
* expected: no issue

@skjnldsv This seems to only cause issues when circles was enabled before, but I see this as a blocker for the beta 2 as circles might have high usage.

cc @daita

**Comment by MorrisJobke** [comment]
Tested with 21.0.2 and circles 0.21.2 and then upgraded to 22.0.0 beta 2: ✅ 

So this seems to be an issue of the upgrade from a nightly release.

**Comment by skjnldsv** [comment]
relieved! :sweat_smile:

**Comment by daita** [comment]
fixed in alpha.5
