### ISSUE TITLE
syntax error, unexpected 'new' (T_NEW), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by Laupe** [nextcloud/circles#60]
Immediately after running the application it throws error 500

`{"reqId":"0IcRJmNvNsHvoTNAQUcW","level":3,"time":"2017-05-09T23:59:50+00:00","remoteAddr":"80.9xxxx","user":"Laupe","app":"PHP","method":"GET","url":"\/apps\/circles\/","message":"syntax error, unexpected 'new' (T_NEW), expecting identifier (T_STRING) at \/home\/apps\/cloud\/apps\/circles\/lib\/Service\/SharesService.php#65","userAgent":"Mozilla\/5.0 (Windows NT 6.3; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/57.0.2987.133 Safari\/537.36","version":"12.0.0.18"}`

**Comment by daita** [comment]
What is your PHP Version ?

**Comment by Laupe** [comment]
@daita PHP Version => 5.6.30-0+deb8u1

**Comment by daita** [comment]
Should be fixed next release
