### ISSUE TITLE
Update to NC 22.0.0 beta 2

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/circles#600]
After upgrading your Nextcloud instance to 22.0.0 beta 2, after logging in, only a white page appears in the browser.

Logs:

`Declaration of OCA\Circles\Service\RemoteStreamService::retrieveSignatory(string $keyId, bool $refresh = true): OCA\Circles\Model\Federated\RemoteInstance must be compatible with daita\MySmallPhpTools\ActivityPub\Nextcloud\nc22\NC22Signature::retrieveSignatory(string $keyId, bool $refresh = false): daita\MySmallPhpTools\Model\Nextcloud\nc22\NC22Signatory at /home/xxx/public_html/xxx/apps/circles/lib/Service/RemoteStreamService.php#72`

Apps:
Nextcloud: 22.0.0 beta 2
Circles:  22.0.0-alpha.4

**Comment by daita** [comment]
fixed in beta 3
