### ISSUE TITLE
Cannot know if a CLI admin did an action or a member

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/circles#606]
We need to be able to differentiate mutliple different cases for the Talk integration:

* If user A was added to a circle by user B in the contacts app => user B
* If user A was added to a circle via CLI => null/cli
* If user A was invited to a circle by user B and user A accepts the invite => user B
* If user A was invited to a circle via CLI and user A accepts the invite => null/cli
* If user A joins a public circle => user A
* If user A requests to join a circle and user B approved => user B
* If user A requests to join a circle and it is approved via CLI => null/cli

**Comment by daita** [comment]
#609 adds Member::getInvitedBy() that returns a FederatedUser with details. use ./occ circles:members:list circleId --output=json for more details about it

This will not work nice on GlobalScale, I need to store remote FederatedUser on local instance for better coverage. This should not be an issue on big setup as the circles_member table is not use for request out of the Circles Management (front-end, occ command)

**Comment by daita** [comment]
We can see that the occ command get its own singleId :]
