### ISSUE TITLE
User still in circles after deletion from userlist

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/circles#61]
If you add an user into a circle the admin deletes it from the userlist, the user in the circle is still there.
Then if the User with the same Username is readded, even he might be another person, he will get the shares you did via the circles.

Expectation: if the admin deletes the user, he must be removed from all circles, or the new user with the same username will see shares, which might not his/her business.

**Comment by tflidd** [comment]
Probably related to this one:
https://github.com/nextcloud/circles/issues/26

**Comment by daita** [comment]
Fixed next release
