### ISSUE TITLE
Android App produce OCA\Circles\Exceptions\FederatedUserNotFoundException for LDAP-User

### ISSUE THREAD

**Issue by AndyFx12** [nextcloud/circles#672]
Android-App stops syncing and produces an OCA\Circles\Exceptions\FederatedUserNotFoundException error at server´s logfile if Circles-App is activated.

Tested with:
- NC22rc2 with LDAP-backend (to Windows Server 2016)
- Android-App 3.16.1

No problems with disabled Circles-App.
No problems with "real" Users. 
-> Name-resolving to LDAP-Users-ID seems to be broken. Affected username is seen in plain-text instead of its UID at logfile.

![grafik](https://user-images.githubusercontent.com/35779271/124278477-99d50400-db46-11eb-948d-7d19fd5744df.png)

regards, Andy

**Comment by effitient** [comment]
I'm having the same issue with Nextcloud 22.0.0 using an OpenLDAP backend for user authentication. It seems circles does the user lookup using the login-name (in my case the mail address) instead of the UUID Nextcloud assigns to LDAP-users as username.

**Comment by bjoern-photo** [comment]
Have the Same issue. Running nextcloud 22 with AD on windows server 2016. when the Circles-App is enabled.

**Comment by tobiasKaminsky** [comment]
When does this happen on Android side, so that we can try to trigger it?

**Comment by ArtificialOwl** [comment]
Can I have a more details log than the one from the webclient/admin page ?

Like, do you have anything in the nextcloud.log ?

**Comment by AndyFx12** [comment]
@tobiasKaminsky:
- issues occurs on every access by an ldap-user via Android-App. Fresh installed app shows a blank page only.

@ArtificialOwl 
see part of 
[nextcloud.log](https://github.com/nextcloud/circles/files/6850337/nextcloud.log)

**Comment by ke-lin** [comment]
Same issue here. Upgraded to NC22 and Android client stopped working. Disabling Circle App, resolves the bug!

**Comment by ArtificialOwl** [comment]
Anyone willing to patch its nextcloud can give a try to @juliushaertl's pull request?

**Comment by AndyFx12** [comment]
@juliushaertl ´s patch works fine on our system. Circles + Android-Client = no issue so far. 
regards, Andy

**Comment by casasfernando** [comment]
Just for the record this problem also affects iOS client app.
Files cannot be listed anymore, while other tabs like "Media" works just fine.

Workaround: disable the Circles app.

Thanks

**Comment by ArtificialOwl** [comment]
NC22.1.0-rc1 is available and should fix this: https://download.nextcloud.com/server/prereleases/

**Comment by Quix0r** [comment]
I better wait for a stable release. I mean, I have only a few users (family members and girlfriend) but still they like to use Nextcloud.

**Comment by ArtificialOwl** [comment]
this is fixed in NC22.1.0
