### ISSUE TITLE
Debug message with every cron call

### ISSUE THREAD

**Issue by anoymouserver** [nextcloud/circles#686]
I've recently upgraded to NC 22.0.0 RC2 (which bundles Circles 22.0.0-rc1) and since then every execution of cron.php outputs `running maintenance(1)` to stdout, which then sends a log mail from my server.
For now I've appended `>/dev/null` to the cron call, but this probably isn't the best solution.

https://github.com/nextcloud/circles/blob/881ff0f824ca8f74b7c5ad2229330cf533632185/lib/Service/MaintenanceService.php#L143

In my opinion this message should be send into the `debug` logging category instead or removed entirely.

**Comment by Henk57** [comment]
I've done this since this problem affects most NC22.0.0 installations. I did not see this with RC1.

/**		echo 'running maintenance(' . $level . ')' . "\n";
*/
So I disabled this line completely in the source code.

**Comment by webracer999** [comment]
> I've done this since this problem affects most NC22.0.0 installations. I did not see this with RC1.
> 
> /** echo 'running maintenance(' . $level . ')' . "\n";
> */
> So I disabled this line completely in the source code. Other cron mails won't be affected then.

I also did this as a workaround for my NC 22.0.0 installation.
