### ISSUE TITLE
Error creating the share Popup

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/circles#689]
In a fresh install:
1. enable the Circles app
2. create a public circle (but Circle type may not be relevant)
3. share with that circle

![error-creating-the-share](https://user-images.githubusercontent.com/85954408/124624924-a2e30f80-de7d-11eb-867c-b58a8fd0ef0e.gif)
4. A pop-up message is shown with "Error creating the share".
5. The share is nonetheless successfully created.

Nextcloud server version: 21.0.3
Circle App version: 0.21.3

**Comment by ArtificialOwl** [comment]
please run `./occ circles:test` and give me the result. 

Are you using an http or https ?

**Comment by pmarini-nc** [comment]
I'm using https with a [mkcert](https://github.com/FiloSottile/mkcert)-generated certificate. 
```
$ sudo -u www-data php ./occ circles:test
[sudo] password for unextcloud: 
- GET request on http://localhost/index.php/csrftoken: 301
```

I cannot replicate the issue on the same instance now.

**Comment by ArtificialOwl** [comment]
mkcert is self-signed certificates ?

if so try this: `./occ config:app:set --value '1' circles self_signed_cert`

**Comment by pmarini-nc** [comment]
mkcert installs a local Certificate Authority to avoid self-signed warnings and errors.

```
$ sudo -u www-data php ./occ config:app:set --value '1' circles self_signed_cert
$ sudo -u www-data php ./occ circles:test
- GET request on http://localhost/index.php/csrftoken: 200
- POST request on http://localhost/index.php/apps/circles/v1/gs/broadcast/async/test-dummy-token/: 200
- Async request is sent, now waiting 5 seconds
- Pause is over, checking results for 12b5acd3-f920-49e4-916d-ac01896fa303
localhost ok
```

As mentioned I do not get the error "Error creating the share Popup" as of now and cannot guarantee that the mkcert has changed in the meanwhile.

**Comment by ArtificialOwl** [comment]
ok, looks good!
