### ISSUE TITLE
Corrupt layout for adding new member

### ISSUE THREAD

**Issue by oparoz** [nextcloud/circles#69]
<img width="508" alt="layout circles" src="https://cloud.githubusercontent.com/assets/323220/26248548/29eb9366-3ca3-11e7-94be-a05f574f6579.png">

**Comment by daita** [comment]
I will render few stuff smaller, but the idea in the end is that this layout will be replaced when integrating Circles to Contact

**Comment by daita** [comment]
https://gfycat.com/PhysicalSameGreyhounddog
