### ISSUE TITLE
Icon in settings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/circles#703]
In the settings for the application, the icon is invisible on a white background.

![obraz](https://user-images.githubusercontent.com/47037905/125444355-1ccbf241-fcd4-4a3b-a43d-71569f751661.png)

![obraz](https://user-images.githubusercontent.com/47037905/125444269-ed7c3925-dde8-41f4-a4b7-00d0dc430c03.png)

Apps:
Nextcloud 22.0.0
Circles 22.0.0

**Comment by AndyFx12** [comment]
Same here - and after activation, no icon on top bar -> unusable.
![grafik](https://user-images.githubusercontent.com/35779271/126598145-b50b7724-631d-42cb-ab83-bfd7c9c1a8ef.png)

**Comment by AndyFx12** [comment]
Issue still exists with 22.1.0 - it´s no loopback-address problem, occ circles:check works fine.

**Comment by raimund-schluessler** [comment]
> Same here - and after activation, no icon on top bar -> unusable. ![grafik](https://user-images.githubusercontent.com/35779271/126598145-b50b7724-631d-42cb-ab83-bfd7c9c1a8ef.png)

Circles is integrated in the Contacts App since a while already. I am not sure if it's the case for NC22 already, but at least on NC23 you find the GUI for circles there.

**Comment by Jerome-Herbinet** [comment]
Same issue for me. 
Circles 23.1.1
Nextcloud Hub II 23.0.4

**Comment by joshtrichards** [comment]
No longer the case today. Closing.
