### ISSUE TITLE
[NC22]occ circles:check fails to determine loopback address

### ISSUE THREAD

**Issue by aleadco** [nextcloud/circles#725]
### How to use GitHub

After upgrading to NC22 occ circles:check fails to determine loopback address

### Steps to reproduce
`sudo -u www-data php /var/www/nextcloud/occ circles:check`
Post method check failed
```
### Checking loopback address.
. The loopback setting is mandatory and can be checked locally.
. The address you need to define here must be a reachable url of your Nextcloud from the hosting server itself.
. By default, the App will use the entry 'overwrite.cli.url' from 'config/config.php'.

* testing current address: https://example.com
- GET request on https://example.com/index.php/csrftoken: 200
- POST request on https://example.com/index.php/apps/circles/async/test-dummy-token/: fail

- You do not have a valid loopback address setup right now.
```

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache2

**Database:** Mariadb 10.6.3

**PHP version:**  7.4.20

**Nextcloud version:** NC22

**Where did you install Nextcloud from:** tar

**Comment by Henk57** [comment]
Same issue with my NC22 install.
Could this be related to the login 'server error' when activating Deck?

**Comment by smyds** [comment]
Yep, changing the sleep on [this line](https://github.com/nextcloud/circles/blob/fff42e5823c0157b22d7277e5cc8c7843ea46f84/lib/Controller/EventWrapperController.php#L137) to something smaller than 5 will cause `occ circles:check` to succeed.

**Comment by SitalexUniversel** [comment]
circles не работают
circles not work
Deleting circles fail


occ circles:check fails

Два шага.

Шаг первый:
мой вариант:
'overwrite.cli.url' => 'https://your-server.ru/nextcloud/',

Шаг второй:
проверьте как отзывается ваш сервер
ping your-server.ru 

ответ должен быть:
your-server.ru   (ваш ip)   , если это не так, тогда изменить /etc/hosts
127.0.0.1    localhost
xxx.xxx.xxx.xxx     your-server.ru

xxx.xxx.xxx.xxx --- это ваш ip.

**Comment by SitalexUniversel** [comment]
Доброго времени.Это возможно. Но почему я не могу писать на родном языке ?Есть ведь переводчик. Good time.It is possible. But why can't I write in my native language?There is a translator.    07.10.2021, 02:07, "Martin Patz" ***@***.***>: ??? English please?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   Здравствуйте.С Уважением Александр Ситников.

**Comment by joshtrichards** [comment]
Fixed in #811
