### ISSUE TITLE
Error enabling app on PostgreSQL

### ISSUE THREAD

**Issue by hukoeth** [nextcloud/circles#74]
When trying to enable the Circles app, I get 

`Error: this app cannot be enabled because it makes the server unstable`

I tried this on my production install and on a completely fresh install with the same result.
I'm using PostgreSQL 9.6.2

This is what the log shows:
    
    Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT s.*, "f"."fileid", "f"."path", "f"."permissions" as "f_permissions", "f"."storage", "f"."path_hash", "f"."parent" as "f_parent", "f"."name", "f"."mimetype", "f"."mimepart", "f"."size", "f"."mtime", "f"."storage_mtime", "f"."encrypted", "f"."unencrypted_size", "f"."etag", "f"."checksum", "s2"."id" as "parent_id", "s2"."file_target" as "parent_target", "s2"."permissions" as "parent_perms", "st"."id" AS "storage_string_id" FROM "oc_share" s LEFT JOIN "oc_filecache" f ON "s"."file_source" = "f"."fileid" LEFT JOIN "oc_share" s2 ON ("s"."id" = "s2"."parent") AND ("s2"."share_with" = ?) LEFT JOIN "oc_storages" st ON "f"."storage" = "st"."numeric_id", "oc_circles_members" m WHERE ("s"."share_type" = ?) AND (("s"."item_type" = ?) OR ("s"."item_type" = ?)) AND ("s"."share_with" = "m"."circle_id") AND ("m"."user_id" = ?) AND ("m"."level" >= ?) OFFSET 0' with params ["user", 7, "file", "folder", "user", 1]: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying = integer LINE 1: ... OR ("s"."item_type" = $4)) AND ("s"."share_with" = "m"."cir... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

    /var/www/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
    /var/www/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 855: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT s.*, "f"...', Array)
    /var/www/lib/private/DB/Connection.php - line 192: Doctrine\DBAL\Connection->executeQuery('SELECT s.*, "f"...', Array, Array, NULL)
    /var/www/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 206: OC\DB\Connection->executeQuery('SELECT s.*, "f"...', Array, Array)
    /var/www/lib/private/DB/QueryBuilder/QueryBuilder.php - line 213: Doctrine\DBAL\Query\QueryBuilder->execute()
    /var/www/apps/circles/lib/ShareByCircleProvider.php - line 413: OC\DB\QueryBuilder\QueryBuilder->execute()
    /var/www/lib/private/Share20/Manager.php - line 1002: OCA\Circles\ShareByCircleProvider->getSharedWith('user', 7, NULL, -1, 0)
    /var/www/apps/files_sharing/lib/MountProvider.php - line 74: OC\Share20\Manager->getSharedWith('user', 7, NULL, -1)
    /var/www/lib/private/Files/Config/MountProviderCollection.php - line 108: OCA\Files_Sharing\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
    /var/www/lib/private/Files/Filesystem.php - line 445: OC\Files\Config\MountProviderCollection->addMountForUser(Object(OC\User\User), Object(OC\Files\Mount\Manager))
    /var/www/lib/private/Files/Filesystem.php - line 374: OC\Files\Filesystem initMountPoints('user')
    /var/www/lib/private/legacy/util.php - line 280: OC\Files\Filesystem init('user', '/user/files')
    /var/www/lib/base.php - line 999: OC_Util setupFS()
    /var/www/index.php - line 40: OC handleRequest()
    {main}

**Comment by daita** [comment]
Unfortunately, it needs a patch on nextcloud's libs:

https://github.com/nextcloud/server/pull/5076

**Comment by daita** [comment]
Good news: the version 0.10.0 fix this ! (and is available)
