### ISSUE TITLE
Circles does work correctly with spaces in the name

### ISSUE THREAD

**Issue by radoeka** [nextcloud/circles#78]
I created two circles like this:
- proj mgt
- proj mgt read only

After the succesful creation and addition of users, I assigned the circles to the same directory.

As one circle should be read only and the other should have all the read only must be modified after sharing directory.

Each time I wanted to change the "proj mgt read only" the other circle "proj mgt" was selected / changed.

I worked around this behavior using underscores for spaces:
- proj_mgt
- proj_mgt_read_only

When spaces are allowed (I hope) make it work.  When spaces (and perhaps other characters are not allowe d in names), prevent the creation of circle names with unwanter/not working characters.

**Comment by daita** [comment]
Thanks for your report, I hope to fix it for NC 12.0.1

**Comment by daita** [comment]
circle part: dda21751ea99529b75e07f1415d189e1261f9727
nextcloud part: https://github.com/nextcloud/server/commit/34b180ba96f2dad76e591fface17e40ec075bc59

**Comment by radoeka** [comment]
Thanks for the (very) quick fix.

Can you elaborate what has changed?  I can't determine from the code what has changed (sorry).  Are spaces from now on, accepted?  Or are spaces no longer allowed?
The nextcloud part patch does not seem to be related to this issue, or am I seeing that wrong?

Question: In the file overview when I hoover at the right of file that has been shared, a pop up window appear showing the sharing characteristics.  Only an small part is shown, the second part (at the right) showing the circle name is not shown completely.  This makes it hard to determine which circle is in effect for that file.  Can you confirm this behavior, do you want me to open another issue for this?

**Comment by daita** [comment]
Circles was using a hacky way to integrate itself into the Sharing List. Nextcloud 12.0.1 will allow more options when displaying the Shares in the right panel. 

Spaces will work better. 

In fact, with your current version of Nextcloud/Circles, it might work to change the read/write settings to your circles, do not care of the UI glitch and refresh the page to have the real sharing settings

**Comment by daita** [comment]
This will be available only on NC 13.0.0

**Comment by joshtrichards** [comment]
This appears to have been long ago fixed. Closing, but ping us if still experiencing this.
