### ISSUE TITLE
deleting a circle does not work - same name recreate results in two same circles

### ISSUE THREAD

**Issue by cbwoog** [nextcloud/circles#821]
**description**
A once created circle can't be deleted.
The delete option appears and the circle seems to be deleted.
When creating a circle with the same name again there are two circles with the same name - the second one gets a number extension.
There is no difference if you wait 5 minutes or any time longer.
The two circles are also visible two the member(s) of the circles.

**Steps to reproduce**
1. create a circle
2. add a user
3. the newly created circles do not show the folder which have been shared at the added user site
4. delete the circle with the delete option in the three dots
5. confirm the deletion in the popup
6. create a new circle with the same name
7. two circles with the same name are shown
8. same behaviour after deleting a circle and refreshing the page shows the deleted circle again

![grafik](https://user-images.githubusercontent.com/78084955/136436112-6413d217-2825-416d-945b-f83664f51392.png)

**Server Configuration**

_operating system_
FreeBSD 12.2-RELEASE-p9 
TRUENAS amd64
16.00 GB ram

_nextcloud_
22.2.0

_php version_
PHP Version => 7.4.23

_database_
mysql 8.0.26

**Comment by ArtificialOwl** [comment]
please run `./occ circles:check`

**Comment by pat-githubber** [comment]
@cbwoog, I have the same issue. I delete the circle.. then it disappears but when I reload Nextcloud, it is there again.

@ArtificialOwl, I am a nooby and I am still not able to execute the `occ` command in Nextcloud using PuTTY even though I spent lots of time on that. By executing your command, I receive ` ./occ: No such file or directory`.

My Nextcloud 22.2.3 runs on a RaspberryPi installed from https://ownyourbits.com/nextcloudpi/

Thank you for any help!

**Comment by cbwoog** [comment]
> please run `./occ circles:check`

https://dd.xxxcloud.de is an inactive old cloud

on truenas( freebsd console with putty) I did a 
su -m www -c "php ./occ circles:check"

### Checking loopback address.
. The loopback setting is mandatory and can be checked locally.
. The address you need to define here must be a reachable url of your Nextcloud from the hosting server itself.
. By default, the App will use the entry 'overwrite.cli.url' from 'config/config.php'.

* testing current address: https://dd.xxxcloud.de
- GET request on https://dd.xxxcloud.de/nextcloud/index.php/csrftoken: 200
- POST request on https://dd.xxxcloud.de/nextcloud/index.php/apps/circles/async/test-dummy-token/: 200
- Creating async FederatedEvent 8e123456-xxxx-xxxx-xxxx-987654321968
- Waiting for async process to finish (5s)
- Checking status on FederatedEvent verify=17 manage=42
* Loopback address looks good


### Testing internal address.
. The internal setting is mandatory only if you are willing to use Circles in a GlobalScale setup on a local network.
. The address you need to define here is the local address of your Nextcloud, reachable by all other instances of our GlobalScale.
- Do you want to enable this feature ? (y/N)
- Do you want to enable this feature ? (y/N) y

Please write down a new internal address to test: 192.168.188.30
format must be http[s]://domain.name[:post][/path]

Please write down a new internal address to test: http://cc.zzzcloud.de
Do you want to check the validity of this internal address? (Y/n) Y

You will need to run this curl command from a terminal on your local network and paste its result:
     curl -L "http://cc.zzzcloud.de/.well-known/webfinger?resource=http://nextcloud.com/&test=cwuzeG3igsUon8K"
paste the result here:
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>
Cannot extract SUBJECT from the pasted data

**Comment by cbwoog** [comment]
> @cbwoog, I have the same issue. I delete the circle.. then it disappears but when I reload Nextcloud, it is there again.
> 
> @ArtificialOwl, I am a nooby and I am still not able to execute the `occ` command in Nextcloud using PuTTY even though I spent lots of time on that. By executing your command, I receive ` ./occ: No such file or directory`.
> 
> My Nextcloud 22.2.3 runs on a RaspberryPi installed from https://ownyourbits.com/nextcloudpi/
> 
> Thank you for any help!

I think you have to check where your occ is located and how to execute it on your system.
As I wrote in my comment before I had to execute it like 
`su -m www -c "php ./occ circles:check"`
but this is due to the way freebsd is accepting the commands.

**Comment by pat-githubber** [comment]
Wow @cbwoog, you are my hero! It worked with your guidance but this was a crazy investigation for me. Tomorrow, I will document everything precisely what I did. Big thanks!!

**Comment by punkyard** [comment]
hi, i'm very interested with this concern.
when I type circles:check, i get:

```
### Checking loopback address.
. The loopback setting is mandatory and can be checked locally.
. The address you need to define here must be a reachable url of your Nextcloud from the hosting server itself.
. By default, the App will use the entry 'overwrite.cli.url' from 'config/config.php'.

* testing current address: http://localhost
- GET request on http://localhost/index.php/csrftoken: fail

- You do not have a valid loopback address setup right now.

Please write down a new loopback address to test: https://my.domain.net
* testing address: http://my.domain.net

Please write down a new loopback address to test: (empty)
exiting.

In CirclesCheck.php line 264:
                                          
  Your Circles App is not fully configured.  
                                            
circles:check [--output [OUTPUT]] [--capabilities] [--type TYPE] [--alpha] [--test TEST]
```

Then I changed localhost in config.php for my actual URL.
I get the same type of message :

`### Checking loopback address.
. The loopback setting is mandatory and can be checked locally.
. The address you need to define here must be a reachable url of your Nextcloud from the hosting server itself.
. By default, the App will use the entry 'overwrite.cli.url' from 'config/config.php'.

* testing current address: http://my.domain.net
- GET request on http://my.domain.net/index.php/csrftoken: 301

- You do not have a valid loopback address setup right now.

Please write down a new loopback address to test: 
`

Does one have a lead to get rid of that .. loop ..?
