### ISSUE TITLE
Missing field for adding new user after update to 0.11.0

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/circles#84]
Hi,

thank all of you for such a nice app.

After update to 0.11.0, I can't find the field to add a new user to the circle.

The browser (firefox/chromium) logs show nothing important.

Thanks, the server info is bellow:

### Server configuration
**Operating system**: Linux 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64

**Web server:** nginx/1.13.1 (fpm-fcgi)

**Database:** pgsql PostgreSQL 9.6.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.2.1) 6.2.1 20160822, 64-bit

**PHP version:** 7.1.6
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, intl, ldap, mcrypt, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 Build:2017-06-14T07:34:13+00:00 426a4c11d6700f011897d17330f2364f1c9b04ee - 12.0.0.29

**Where did you install Nextcloud from:** Docker image wonderfall/nextcloud:daily

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - audioplayer: 2.0.2
 - bookmarks: 0.10.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - checksum: 0.3.4
 - circles: 0.11.0
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.0
 - drawio: 0.8.8
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_markdown: 1.0.1
 - files_opds: 0.8.2
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.6
 - gpxpod: 2.1.2
 - groupfolders: 1.0.2
 - impersonate: 1.0.1
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - mood: 0.2.0
 - news: 11.0.5
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.0
 - ownbackup: 17.5.0
 - passman: 2.1.2
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - qownnotesapi: 17.5.0
 - quota_warning: 1.0.0
 - registration: 0.2.3
 - richdocuments: 1.12.33
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_diaspora: 1.0.1
 - socialsharing_email: 1.0.1
 - socialsharing_facebook: 1.0.1
 - socialsharing_googleplus: 1.0.1
 - socialsharing_twitter: 1.0.1
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - telephoneprovider: 1.0.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - twofactor_u2f: 1.3.2
 - updatenotification: 1.2.0
 - weather: 1.4.2
 - workflowengine: 1.2.0
 - workin2gether: 0.9.6

Disabled:
 - apporder
 - encryption
 - external
 - files_snapshots
 - keeweb
 - ojsxc
 - ownpad
 - previewgenerator
 - rainloop
 - user_external
 - user_ldap
```
</details>

**Are you using encryption:** no

### Client configuration
**Browser:**
- `Mozilla Firefox`: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
- `Chromium`: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Operating system:** Fedora Rawhide

**Comment by lachmanfrantisek** [comment]
The screenshot of the app:

![nextcloud-circles](https://user-images.githubusercontent.com/20214043/27324903-f531eb62-55a6-11e7-9d1e-3d58c2318220.png)

**Comment by daita** [comment]
Thanks for your report, do you have any error in the Javascript console ?

**Comment by lachmanfrantisek** [comment]
No, there is only a log info about the selected circle and following deprecation warning:
```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

**Comment by lachmanfrantisek** [comment]
Now, I've tried it with the fresh install (`12` and `daily` on SQLite) with the same result.

**Comment by lachmanfrantisek** [comment]
I've found it!

Only the icon is missing. If I click next to the trashbin, the field occurs.

**Comment by lachmanfrantisek** [comment]
The trashbin icon is loaded from `../../core/css/../img/actions/delete.svg?v=1`, but the `add-user` icon is loaded from `/apps/circles/img/add-user.svg` (which is not present).

**Comment by daita** [comment]
This should do the trick, if you want to give it a try.

**Comment by lachmanfrantisek** [comment]
@daita Yes, it woks, thank you.

**Comment by lachmanfrantisek** [comment]
@daita Thanks for the quick response and solution.

In which version this will be released? No hurry, just curious.

**Comment by daita** [comment]
I will release a minor update 0.11.1 before the end of the month

**Comment by lachmanfrantisek** [comment]
Nice, thank you.
