### ISSUE TITLE
Message in Log: Exception: str_replace(): Argument #2 ($replace) must be of type array|string

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/circles#844]
NC23 RC2 + circles 23.0.0

![image](https://user-images.githubusercontent.com/24530680/141742238-f4dad80a-5d65-47a5-9415-28c001d61874.png)

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/backup/issues/69#issuecomment-973192652
