### ISSUE TITLE
Adding users to a group in bulk

### ISSUE THREAD

**Issue by hirunatan** [nextcloud/circles#855]
Not sure this is an issue, but cannot find any other channel to ask this.

I have started using circles in a nextcloud instance that already has around 800 users. I have several lists of people, that previously were organizing in a different way, and we'd like to convert into circles.

But apparently there is no way of populating the circles than typing by hand each one of the members, one by one. Could be possible to add them automatically with a script? By using some kind of REST api or occ commands, for example?

I can see in the wiki (https://github.com/nextcloud/circles/wiki/Javascript-API-v1) that there are two programming apis, but they seem to be intended for writing your own nextcloud app, not for the use I want, is it correct? Thanks.

**Comment by acsfer** [comment]
Check https://github.com/nextcloud/circles/wiki/PHP-API-v1#using-the-api-to-manage-members

**Comment by ArtificialOwl** [comment]
which version of Nextcloud are you using ? if 22+, you can do `ocs` request, like the one used by the Contacts app to add multiple users

**Comment by hirunatan** [comment]
Thanks. Finally we have managed to organize the circles manually, sharing the work between a bunch of people.

But if we need this in the future, we can use your suggestions.
