### ISSUE TITLE
NC 22: occ circles:sync not migrating all Circles

### ISSUE THREAD

**Issue by svenseeberg** [nextcloud/circles#858]
After upgrading to Nextcloud 22.2.3 from 21.x and running `occ circles:sync --migration` a majority of Circles have not been migrated.

```
SELECT COUNT(unique_id) FROM oc_circle_circles WHERE unique_id NOT IN (SELECT unique_id FROM oc_circles_circle);
+------------------+
| COUNT(unique_id) |
+------------------+
|             1324 |
+------------------+
1 row in set (0.013 sec)

SELECT COUNT(unique_id) FROM oc_circle_circles WHERE unique_id IN (SELECT unique_id FROM oc_circles_circle);
+------------------+
| COUNT(unique_id) |
+------------------+
|              548 |
+------------------+
1 row in set (0.011 sec)
```

The migration script claims that the migration is done:
```
occ circles:sync --migration

Migration done
```

It seems that this can be resolved by executing the migration multiple times with the `--force` parameter:
```
occ circles:sync --migration --force
```

**Comment by ArtificialOwl** [comment]
Did you end up having all your circles after using `--force` ?

**Comment by svenseeberg** [comment]
Yes, the circles where migrated after using the `--force` flag. We now noticed that our `oc_circles_membership` table feels short of entries and many users are not seeing folders shared with them.

```
MariaDB [nextcloud]> SELECT COUNT(*) FROM oc_circles_membership;
+----------+
| COUNT(*) |
+----------+
|    74888 |
+----------+
1 row in set (0.024 sec)

MariaDB [nextcloud]> SELECT COUNT(*) FROM oc_circles_member;
+----------+
| COUNT(*) |
+----------+
|   217435 |
+----------+
1 row in set (0.051 sec)
```

**Comment by ArtificialOwl** [comment]
maybe some process are stop during heavy load, you can fill the `oc_circles_membership` using `./occ circles:memberships --all`
(might takes some time)

**Comment by svenseeberg** [comment]
Thanks. I'll run `./occ circles:memberships --all` and provide feedback. But it seems the table content is now growing quickly.

**Comment by svenseeberg** [comment]
It seems that our text server is migrating the memberships over time and reached 90k memberships after about 3 weeks. With `./occ circles:memberships --all` the count is now rising by the thousands per minute. I'll add this note (including the signoff ;-) ) to my PR. Thanks for the feedback.
