### ISSUE TITLE
hidden circle

### ISSUE THREAD

**Issue by ddanielww** [nextcloud/circles#86]
An hidden circle is an open group that can be protected by a password. Users won't be able to find this Circle using Nextcloud search engine.

How do you assign a password?

 Users won't be able to find this Circle using Nextcloud search engine?

People who are added to the hidden circle can still add files so what does this mean exactly?

This circle makes no sense can someone explain?

**Comment by ddanielww** [comment]
Also how is it open as no one can see it unless I add them to the circle ?

**Comment by daita** [comment]
Hidden circles are those you do not want to be listed in the global/official list of Circles of a cloud. The only way to find it is to search for its complete name in the Circles search bar. 

The idea was to let the possibility of creating circles that does not 'pollute' the official list of circles

Even if it has no use for you, this feature still makes sense !
