### ISSUE TITLE
Private circles (name and author) viewable by all users

### ISSUE THREAD

**Issue by muppeth** [nextcloud/circles#87]
I noticed that private circles are viewable by anyone on nextcloud (meaning the name and author). I think the name is misleading and people think those are private circles no one can see. Also they have no chance to verify that unless they have an extra account. 

I've contacted few users on my nextcloud instance that have made "private" circles that were clearly not intended to be viewed by the others, and they were surprised to hear that anyone could see such circle exist. 
I think either the name should be changed to something else or (preferable option) those private circles should not be viewable by anyone, unless invited to (so they are truly private).

**Comment by daita** [comment]
You are looking for Hidden Circle or Personal Circle. But it is true that Closed Circle might be a better name.

**Comment by muppeth** [comment]
Closed Circle sounds better indeed (though you should still mention in 
the description that this circle can be seen by anyone).

thanks for looking into it.

**Comment by daita** [comment]
fixed in next major release
