### ISSUE TITLE
Types of circles incorrect (0.11.0)

### ISSUE THREAD

**Issue by jgrete** [nextcloud/circles#89]
Choosing a type on creation of a circle leads to a combo dialog which let's you choose between 4 entries. The first/second and the third/fourth entry are equal named (see picture). It's just the names which are wrong, I can choose all of the four different types

Regards
Juergen

![circletypes](https://user-images.githubusercontent.com/14105933/27723093-8d329378-5d6b-11e7-9f36-3991645ade60.png)

**Comment by daita** [comment]
Looks like a translation issue, which language is that ? ;]

**Comment by jgrete** [comment]
German

**Comment by daita** [comment]
Bug has been reported to the translation team. Will be fixed next minor release.

Remenber that you can also join the german translation team on transifex.com !
