### ISSUE TITLE
Unable to check checkboxes in the settings (0.11.0)

### ISSUE THREAD

**Issue by jgrete** [nextcloud/circles#90]
I'm not able to check the settings in the settings dialog (see picture). Also, they are barely perceptible, contrast is much too low.
Regards
Juergen

![circlesettings](https://user-images.githubusercontent.com/14105933/27723271-88d8b8ba-5d6c-11e7-93a5-d2053091161f.png)

**Comment by daita** [comment]
You will need to activate the Federated Circles in your Admin Settings first.
