### ISSUE TITLE
Oracle database compatibility

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/circles#901]
## SQL in statements don't support more than 1000 entries

Issue found in:

- [ ] Db\CircleProviderRequestBuilder::limitToFiles
- [ ] Db\CircleProviderRequestBuilder::limitToCircles
- [ ] artificial-owl/my-small-php-tools/lib Db/Nextcloud/nc22/NC22ExtendedQueryBuilder::exprLimitInArray

## Comparaison with CLOB (==, group by)

- [ ]  https://github.com/nextcloud/circles/blob/master/lib/Db/CircleRequestBuilder.php#L80

**Comment by ArtificialOwl** [comment]
all done
