### ISSUE TITLE
Auto-Add Memebers to public circles based on groups

### ISSUE THREAD

**Issue by fsedarkalex** [nextcloud/circles#91]
I would love to see an option to automatically add users to public circles if they are member of a specific group.
This option should only be available to admins.
Auto-added users should not be able to leave a circle or be removed from it in any way if this option is used for a specific circle.

e.g. One could add a Circle called "NC Admins" and select "admin" group then every member of "admin" group is automatically member of that circle.

**Comment by daita** [comment]
This first patch let you add a full group to a circle and will be release with 0.11.1 (with no specific limit to admins, users should be able to invite group members into their circle)

However, I am not sure an option to prevent your members from leaving a circle is really necessary.

**Comment by fsedarkalex** [comment]
What is important for my request is that also new members of the group get auto-added into the circle.

**Comment by daita** [comment]
This is slightly different from the original message :]

**Comment by fsedarkalex** [comment]
Well I said ...every member ... is automatically member of the circle... I thought it was clear what I was trying to say :(

When it comes to private circles... Well I just understood some things wrong

**Comment by daita** [comment]
Next major release of Circles will allow you to link groups to a circle and assign a level up to any members of the group (up to Administrator).

Group members should be able to have access to shared files and receive frame on broadcast (like a mood message or anything using Circles API). 

There is still few thing that needs to be add/fix, but if you're willing to test this feature you can get the source from the github

**Comment by fsedarkalex** [comment]
At the moment I am a bit busy but will try this asap

**Comment by daita** [comment]
will be available in 0.12.0
