### ISSUE TITLE
Spelling: What does this mean?

### ISSUE THREAD

**Issue by comradekingu** [nextcloud/circles#92]
> On event in a <strong>Circle</strong> you are a member, or a potential member

in [https://github.com/nextcloud/circles/edit/master/lib/Activity/SettingAsMember.php](url)

From my understanding,
"In case something happens in a <strong>Circle</strong> you are a member or potential member of"

But the context is lacking.

**Comment by daita** [comment]
For example, If you are invited into a circle, you're not yes a member but a potential one :] Maybe replacing it with 'future' or 'eventual'.

**Comment by comradekingu** [comment]
@daita I think i understood, is it? 
"Triggered by an event happening in a circle you are a member or potential member of" ?

**Comment by daita** [comment]
English is not my mother tongue, you might be better than me to judge if your sentence is better than mine. I can edit myself and replace with yours, or you can edit yourself and make a pull request. 

Your choice !
