### ISSUE TITLE
Move non time critical background tasks to maintenance window

### ISSUE THREAD

**Issue by PVince81** [nextcloud/circles#927]
With https://github.com/nextcloud/server/pull/30945 it will be possible to move background jobs to times where the server is less busy. We have some tasks that currently run at a fixed interval, where it might make sense to move them for the chance of yielding better performance.

- [ ] apps/circles/lib/Cron/ContactsExistingShares.php
- [ ] apps/circles/lib/Cron/GlobalSync.php
- [ ] apps/circles/lib/Cron/Maintenance.php

For each **TimedJob**, add the `TIME_INSENSITIVE` flag, when:
- if can be run once a day only
- and if it causes a high load

perhaps the Maintenance one could be relevant ?

@ArtificialOwl

**Comment by ArtificialOwl** [comment]
I will need to split `Cron/Maintenance` as it manage small and big tasks
