### ISSUE TITLE
Missing icons...

### ISSUE THREAD

**Issue by jgrete** [nextcloud/circles#93]
I'm missing some icons within the circle app. The icon for adding members to a circle isn't in place (see screenshot) but clicking there opens an input field. I'm having this effect on two different nextcloud installations with two different browsers (Firefox, Chrome).
Any hints? 
Regards
Juergen

![2017-07-04 08_30_39-nextcloud](https://user-images.githubusercontent.com/14105933/27817991-16f2c6c0-6094-11e7-8f89-3147bfccb45f.png)

**Comment by daita** [comment]
https://github.com/nextcloud/circles/commit/68b3e513fedb55e4fe0d8018a527ab09b1e0b3c3

fixed in 0.11.1
