### ISSUE TITLE
Adding new Circle: Duplicate and missing entries in circle type (twice private, twice personal, but now public or hidden)

### ISSUE THREAD

**Issue by Schmuuu** [nextcloud/circles#96]
Hi,

### My issue
When I create a new circle, I type in the circle name and want to select the circle type afterwards.
I have the choice between:
* create a personal circle
* create a personal circle
* create a private circle
* create a private circle

So I can't select "public" or "hidden" circle in the drop down list:
![grafik](https://user-images.githubusercontent.com/26191454/27987303-ccc8d906-640b-11e7-9ca1-e848592573ee.png)

### Server configuration
**Operating system**: Linux nextcloud 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.18

**PHP version:** 7.0.18-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, smbclient, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from NC11

**Circles:** 0.11.0

**Comment by daita** [comment]
Yes, this is fixed already in the next release of Circles; thanks for your report !

#89
