### ISSUE TITLE
Cannot add more than exactly 50 members

### ISSUE THREAD

**Issue by osm-frasch** [nextcloud/circles#962]
Our circles app also only goes up to 50 users per circle created. 
Currently running  Circles, 22.1.1, NC 22.2.2, PHP: 7.3.16,  mysql 10.4.12 , 

The command “…occ config:app:get circles members_limit” outputs 50. 
Can I change this or is it a fixed size? 
Not sure whether this is more a setting thing or a bug?

**Comment by ArtificialOwl** [comment]
you can set:

>      ./occ circles:app:set circles members_list --value -1

`-1` means no limit, or set an integer as limit

**Comment by osm-frasch** [comment]
Thanks for the hint.
 
After I have entered the following "sudo -u apache php occ circles:app:set circles members_list --value -1"

I get this message back:
There are no commands defined in the "circles:app" namespace.                                                                  
  Did you mean one of these?                                     
      circles                                                    
      circles:manage                                             
      circles:members                                            
      circles:shares                                             
      config:app     

Has anything changed with regard to the OCC command?

**Comment by CarlSchwan** [comment]
It's config:app:set

**Comment by osm-frasch** [comment]
OK, thank you this command will be accepted.
sudo -u apache php occ config:app:set circles members_list --value 200
But after the check with: "sudo -u apache php occ config:app:get circles members_limit" I still get 50 back
Do I have to restart the server for this?

**Comment by ArtificialOwl** [comment]
Alright, my bad, `members_limit` and not `members_list`

>      ./occ config:app:set circles members_limit --value 200

To set the value to -1 (default):

>      ./occ config:app:delete circles members_limit

**Comment by osm-frasch** [comment]
Yes that works fine. 
Found out myself just this second. Thanks to everyone though, especially as this is not a support forum. But I will post it again in the appropriate thread in the NC support forum so that everyone can benefit from it.
