### ISSUE TITLE
Adding a group to a circle makes it "readonly" for the owner

### ISSUE THREAD

**Issue by marcotrevisan** [nextcloud/circles#973]
Version: 22.3 (just upgraded NC server from 22.2.5 to 22.2.6)

STEPS TO REPRO
- Create a new circle
- [UPDATED] Add a group to that circle (I mean a group in the "Users" page, not a group created in the Circles app) that contains tha current user
- Navigate in another app i.e. Calendar
- Go back to circles and select the just created circle

EXPECTED BEHAVIOUR
The user can add/remove groups and members as usual

OBSERVED BEHAVIOUR
The UI changes as if the current user is not the owner of the circle anymore.
Until before upgrading NC server I was able to edit any circle I created.

<img width="1019" alt="Schermata 2022-03-23 alle 08 14 04" src="https://user-images.githubusercontent.com/5240630/159643846-1f62b462-b2c4-48a2-9b7a-b192f056e0d3.png">

**Comment by marcotrevisan** [comment]
I upgraded to NC 23 the instance on which I filed this issue. 
The behaviour has unfortunately not changed.  However I found what is perhaps causing it:

- The group added to the circle includes myself (the owner)
- If I click on the "Leave circle" action and refresh the page, the circle shows up and is back to editable.

So perhaps the root cause is that the UI is checking my belonging to the group and forgets to check that I'm also the owner of the circle.

**Comment by maximelehericy** [comment]
Same issue here, with NC 22.2.5

WHEN User A is owner of the circle C
AND User A belongs to Group Z
AND Group Z is added to the circle C
THEN User A has no longer owner permissions on the circle C

**Comment by XueSheng-GIT** [comment]
I can confirm this issue on NC 23.0.3. Any workaround yet?

**Comment by ArtificialOwl** [comment]
It seems it only affect group, not sub-circles ?

**Comment by marcotrevisan** [comment]
Just tested. The same behaiour holds if you add another circle instead of a group.
To see the effect on the available UI controls you need to reload the page.

**Comment by marcotrevisan** [comment]
Thanks for your  further feedback @ArtificialOwl. I testeed more thoroughly and I wasn't aware of a subtle condition that is actually triggering it.

If, using only the Contacts app, I create _Circle 1_, then _Circle 2_  (so I'm the owner of both) and then add _Circle 2_ to _1_ or vice versa, it works.
But, if say _Circle 1_ is associated to a Collective, then adding _Circle 2_ (that contains me as owner) to it triggers the issue.

As a Collectives administrator user this behaviour is unwanted because it forces me to add people one by one to the circle instead of reusing my existing groups.

**Comment by ArtificialOwl** [comment]
#999 should fix this issue
